import { SeedService } from "./seed-services-part1.js";

export const seedServicesPart4: SeedService[] = [
  // MIGRATION & TRANSFER
  {
    serviceCode: "mgn",
    name: "Application Migration Service",
    slug: "aws-application-migration-service",
    categorySlug: "migration",
    shortDescription: "Lift-and-shift server replication migration to AWS.",
    fullDescription: "AWS Application Migration Service (AWS MGN) simplifies and expedites your migration to AWS by allowing you to lift-and-shift physical, virtual, or cloud servers.",
    characteristics: ["Continuous agent-level server replication", "Automated migration testing drills", "Supports Windows and Linux OS"],
    features: ["Continuous block-level disk replication", "Launch template conversion filters", "Non-disruptive migration tests", "Failback recovery options"],
    useCases: ["Migrating physical datacenters to EC2", "Replicating VMware VMs to the cloud", "Moving workloads from Azure/GCP to AWS"],
    pricingModels: ["Free (First 90 days per server)", "Replicated Server hourly rate thereafter"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "AWS Migration Hub", slug: "aws-migration-hub" }],
    keywords: ["mgn", "migration", "lift and shift", "server replication", "datacenter move"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/mgn/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1730,
    comparisonTags: ["Cloud Migration", "Replication Engine"]
  },
  {
    serviceCode: "datasync",
    name: "AWS DataSync",
    slug: "aws-datasync",
    categorySlug: "migration",
    shortDescription: "Fast, automated data transfer between local storage and S3.",
    fullDescription: "AWS DataSync is a secure online data transfer service that simplifies, automates, and accelerates moving terabytes of data between on-premises storage and AWS storage.",
    characteristics: ["High-speed network transfer optimization", "Local agent data synchronizer", "Automatic encryption and validation"],
    features: ["File system protocol support (NFS/SMB)", "S3 and EFS direct integration", "Scheduled sync task triggers", "VPC network endpoint support"],
    useCases: ["Migrating local NAS files to S3 buckets", "Continuous backup syncs of local storage", "Syncing media assets to cloud for processing"],
    pricingModels: ["Data Transferred per GB Volume"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon EFS", slug: "amazon-efs" }],
    keywords: ["datasync", "data transfer", "nfs sync", "smb transfer", "nas sync"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/datasync/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1740,
    comparisonTags: ["Data Replication", "Migration Utility"]
  },
  {
    serviceCode: "applicationdiscovery",
    name: "Application Discovery Service",
    slug: "aws-application-discovery-service",
    categorySlug: "migration",
    shortDescription: "Discover on-premises servers and map dependencies.",
    fullDescription: "AWS Application Discovery Service helps enterprise customers plan migration projects by gathering information about their on-premises datacenters, including CPU, memory, and network dependencies.",
    characteristics: ["On-premises server discovery agents", "Workload dependency mapping graphs", "Cost estimation builder inputs"],
    features: ["Agentless VMware discovery collector", "OS agent telemetry monitoring", "Migration Hub dashboard visualization", "Database schema analysis feeds"],
    useCases: ["Inventorying on-prem datacenter servers", "Mapping app server to database dependencies", "Estimating AWS pricing requirements before migration"],
    pricingModels: ["Free (Core migration planning utility)"],
    relatedServices: [{ name: "AWS Migration Hub", slug: "aws-migration-hub" }],
    keywords: ["discovery service", "datacenter audit", "dependency mapping", "migration planning"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/application-discovery/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1750,
    comparisonTags: ["Discovery Service", "Migration Utility"]
  },
  {
    serviceCode: "mainframemodernization",
    name: "AWS Mainframe Modernization",
    slug: "aws-mainframe-modernization",
    categorySlug: "migration",
    shortDescription: "Migrate and modernize mainframe applications to AWS.",
    fullDescription: "AWS Mainframe Modernization is a fully managed service that allows you to migrate, modernize, test, and run your mainframe workloads on a secure cloud infrastructure.",
    characteristics: ["Mainframe runtime environment emulation", "COBOL and PL/I code compiler engines", "Decoupled cloud architecture conversion"],
    features: ["Re-platforming runtime (Micro Focus)", "Automated code conversion tools", "Managed compute runtime instances", "VPC security integration"],
    useCases: ["Migrating legacy banking COBOL code to Java", "Decommissioning on-prem physical mainframe units", "Re-hosting mainframe apps on scalable cloud subnets"],
    pricingModels: ["Managed Mainframe Instance Hourly rate"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["mainframe", "cobol", "modernization", "legacy migration", "replatforming"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/mainframe-modernization/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1760,
    comparisonTags: ["Cloud Migration", "Legacy Modernization"]
  },

  // MEDIA SERVICES
  {
    serviceCode: "medialive",
    name: "AWS Elemental MediaLive",
    slug: "aws-elemental-medialive",
    categorySlug: "media",
    shortDescription: "Broadcast-grade live video processing and encoding.",
    fullDescription: "AWS Elemental MediaLive is a broadcast-grade live video processing service. It lets you create high-quality live video streams for delivery to broadcast televisions and internet-connected devices.",
    characteristics: ["High availability dual-channel ingestion", "Real-time video compression encoding", "Supports major broadcast input protocols"],
    features: ["RTMP/RTP/SRT protocol input ingest", "Multi-bitrate output encoding (H.264/H.265)", "Dynamic graphic logo overlays", "Static DRM encryption hooks"],
    useCases: ["Streaming live sporting events online", "Encoding television channels for OTT apps", "Broadcasting corporate live events globally"],
    pricingModels: ["Active Input channel Hour", "Output resolution stream rate"],
    relatedServices: [{ name: "AWS Elemental MediaPackage", slug: "aws-elemental-mediapackage" }],
    keywords: ["medialive", "live stream", "video encoder", "broadcast tv", "rtmp ingest"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/medialive/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1770,
    comparisonTags: ["Video Processing", "Media Ingestion"]
  },
  {
    serviceCode: "mediaconvert",
    name: "AWS Elemental MediaConvert",
    slug: "aws-elemental-mediaconvert",
    categorySlug: "media",
    shortDescription: "File-based video transcoding with broadcast features.",
    fullDescription: "AWS Elemental MediaConvert is a file-based video transcoding service with broadcast-grade features. It allows you to easily create video-on-demand (VOD) content.",
    characteristics: ["High-speed serverless file transcoding", "Wide codec and container support", "Broadcast quality visual processing"],
    features: ["HEVC, AVC, AV1 video encoding codecs", "Closed caption and subtitle inserts", "Dolby Atmos audio encoding", "Watermarking and logo overlays"],
    useCases: ["Transcoding raw camera footage to web formats", "Preparing VOD movie files for streaming platforms", "Adding captions to video directories"],
    pricingModels: ["Transcoded video output minute rate (based on codec/resolution)"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["mediaconvert", "transcoder", "vod encode", "video converter", "mp4 h264"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/mediaconvert/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1780,
    comparisonTags: ["Video Transcoder", "Media Ingestion"]
  },
  {
    serviceCode: "mediapackage",
    name: "AWS Elemental MediaPackage",
    slug: "aws-elemental-mediapackage",
    categorySlug: "media",
    shortDescription: "Prepare and protect video streams for internet delivery.",
    fullDescription: "AWS Elemental MediaPackage reliably prepares and protects your video streams for delivery over the internet, formatting streams dynamically on request.",
    characteristics: ["Just-In-Time packaging engines", "Multi-format VOD and Live outputs", "Robust digital rights management"],
    features: ["Dynamic HLS/DASH output packaging", "DRM key integrations (Widevine/FairPlay)", "Time-shifted TV (Pause/Rewind live feeds)", "Integrated CloudFront origin shield configurations"],
    useCases: ["Dynamic packaging of live streams for Apple/Android", "Enforcing DRM protection on premium VOD assets", "Providing DVR rewind capabilities in video apps"],
    pricingModels: ["Video volume ingested per GB", "Video volume packaged and sent per GB"],
    relatedServices: [{ name: "AWS Elemental MediaLive", slug: "aws-elemental-medialive" }, { name: "Amazon CloudFront", slug: "amazon-cloudfront" }],
    keywords: ["mediapackage", "video package", "hls dash", "drm protect", "dvr rewind"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/mediapackage/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1790,
    comparisonTags: ["Media Packager", "Web Protection"]
  },
  {
    serviceCode: "mediastore",
    name: "AWS Elemental MediaStore",
    slug: "aws-elemental-mediastore",
    categorySlug: "media",
    shortDescription: "Optimized storage for low-latency media delivery.",
    fullDescription: "AWS Elemental MediaStore is an AWS storage service optimized for media. It provides the performance, low latency, and immediate read-after-write consistency required for VOD/Live video origin servers.",
    characteristics: ["Immediate read-after-write file consistency", "Optimized media asset caching", "High concurrent request support"],
    features: ["S3 baseline storage engines", "HTTP object interface caching", "VPC private access networks", "KMS media encryption"],
    useCases: ["Origin server hosting for live video fragments", "Low latency VOD asset storage hubs", "Direct ingestion targets for encoders"],
    pricingModels: ["Media storage consumed per GB", "HTTP request operations volume"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["mediastore", "media storage", "video origin", "live chunk store"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/mediastore/",
    isFeatured: false,
    status: "GA",
    displayOrder: 180,
    comparisonTags: ["Object Storage", "Media Origin Storage"]
  },
  {
    serviceCode: "mediatailor",
    name: "AWS Elemental MediaTailor",
    slug: "aws-elemental-mediatailor",
    categorySlug: "media",
    shortDescription: "Insert personalized advertising into video streams.",
    fullDescription: "AWS Elemental MediaTailor is a channel assembly and personalized ad insertion service, allowing you to monetize video streams using server-side ad insertions.",
    characteristics: ["Server-side ad insertion (SSAI)", "Client-side ad blocker bypass", "Personalized ad decision hooks"],
    features: ["Just-in-time ad transcoding insertion", "Ad-decision server protocol support (VAST/VMAP)", "Channel Assembly program scheduler", "Dynamic tracking beacons outputs"],
    useCases: ["Monetizing live streaming television channels", "Inserting VOD movie stream ads", "Building virtual linear channels from asset catalogs"],
    pricingModels: ["Ad insertions volume (per thousand)", "Data volume parsed and sent per GB"],
    relatedServices: [{ name: "AWS Elemental MediaPackage", slug: "aws-elemental-mediapackage" }],
    keywords: ["mediatailor", "ad insertion", "monetize video", "ssai", "channel assembly"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/mediatailor/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1810,
    comparisonTags: ["Ad Insertion Engine", "Media Packager"]
  },
  {
    serviceCode: "ivs",
    name: "Amazon Interactive Video Service",
    slug: "amazon-interactive-video-service",
    categorySlug: "media",
    shortDescription: "Managed live video platform with low latency.",
    fullDescription: "Amazon Interactive Video Service (Amazon IVS) is a managed live video streaming platform that makes it easy to build interactive live video experiences with sub-3 second latency.",
    characteristics: ["Sub-3 second live video latency", "Ready-to-use player SDK widgets", "Scale dynamic viewer support"],
    features: ["RTMP stream ingestion keys", "Timed metadata payload injections", "Live chat room APIs", "Automated VOD record-to-S3 configs"],
    useCases: ["Building Twitch-style live streaming apps", "Adding live retail sales streams to websites", "Interactive online classroom webinars"],
    pricingModels: ["Video input duration hours", "Video output delivery duration hours (per viewer)"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["ivs", "live video platform", "twitch engine", "low latency video", "interactive streams"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/ivs/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1820,
    comparisonTags: ["Live Streaming Platform", "PaaS Media"]
  },
  {
    serviceCode: "kinesisvideo",
    name: "Amazon Kinesis Video Streams",
    slug: "amazon-kinesis-video-streams",
    categorySlug: "media",
    shortDescription: "Stream live video from devices for analytics and ML.",
    fullDescription: "Amazon Kinesis Video Streams makes it easy to securely stream video from connected devices to AWS for real-time video analytics, machine learning, and playback.",
    characteristics: ["Device camera video ingestion streams", "WebRTC dynamic endpoint connections", "Durable storage and analytics links"],
    features: ["WebRTC peer-to-peer connection tunnels", "Kinesis Video SDK camera agents", "Rekognition computer vision integrations", "Time-indexed video data indexing"],
    useCases: ["Streaming home security camera feeds to cloud", "Manufacturing line quality control camera ingestions", "Building baby monitor streaming applications"],
    pricingModels: ["Data volume ingested per GB", "Data volume consumed/retrieved per GB", "WebRTC active signaling channels"],
    relatedServices: [{ name: "Amazon Rekognition", slug: "amazon-rekognition" }],
    keywords: ["kinesis video", "webrtc", "camera stream", "video analytics store"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/kinesisvideostreams/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1830,
    comparisonTags: ["Video Ingestion", "Real-Time Streaming", "WebRTC Gateway"]
  },
  {
    serviceCode: "nimblestudio",
    name: "Amazon Nimble Studio",
    slug: "amazon-nimble-studio",
    categorySlug: "media",
    shortDescription: "Deploy virtual workstations for animation and VFX.",
    fullDescription: "Amazon Nimble Studio empowers creative studios to produce visual effects, animation, and interactive content entirely in the cloud, deploying virtual workstations.",
    characteristics: ["High performance GPU workspace virtualization", "Low latency streaming protocol links", "Shared creative asset file clusters"],
    features: ["Virtual VFX Workstations (NVIDIA GPUs)", "AWS FSx shared cache mounts", "Creative app deployment presets", "SSO account credentials manager"],
    useCases: ["Remote animation studio creative workspaces", "High throughput VOD Vfx rendering", "Collaborative video editing pipelines"],
    pricingModels: ["Virtual Workstation Instance Hourly rate", "FSx storage consumed"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Amazon FSx", slug: "amazon-fsx" }],
    keywords: ["nimble", "vfx workstation", "animation workspace", "rendering instance"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/nimble-studio/",
    isFeatured: false,
    status: "Retired",
    displayOrder: 1840,
    comparisonTags: ["Virtual Workstation", "GPU Computing"]
  },

  // INTERNET OF THINGS (IoT)
  {
    serviceCode: "iotcore",
    name: "AWS IoT Core",
    slug: "aws-iot-core",
    categorySlug: "iot",
    shortDescription: "Connect IoT devices securely to the cloud with MQTT.",
    fullDescription: "AWS IoT Core lets you connect IoT devices to the AWS Cloud without provisioning servers. It supports secure MQTT message routing and device shadow registries.",
    characteristics: ["MQTT lightweight protocol gateways", "Device state shadows registers", "Serverless metric ingestion scaling"],
    features: ["MQTT/Websockets gateway interfaces", "Device shadow JSON state files", "IoT SQL Rule Engine database routing", "X.509 client certificate checks"],
    useCases: ["Ingesting smart thermostat telemetry logs", "Routing factory machinery metrics to databases", "Managing remote fleet config settings"],
    pricingModels: ["Messages processed volume (per million)", "Device shadow dynamic state syncs"],
    relatedServices: [{ name: "AWS IoT Device Management", slug: "aws-iot-device-management" }, { name: "Amazon Timestream", slug: "amazon-timestream" }],
    keywords: ["mqtt", "iot core", "smart devices", "device shadow", "sensor data", "message gateway"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iot/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1850,
    comparisonTags: ["IoT Platform", "Message Broker"]
  },
  {
    serviceCode: "iotdevicemanagement",
    name: "AWS IoT Device Management",
    slug: "aws-iot-device-management",
    categorySlug: "iot",
    shortDescription: "Track, monitor, and manage IoT device fleets.",
    fullDescription: "AWS IoT Device Management makes it easy to securely register, organize, monitor, and remotely manage IoT devices at scale throughout their lifecycles.",
    characteristics: ["Fleet-wide remote control pipelines", "Device inventory indexes registers", "Automated OTA update rollouts"],
    features: ["OTA firmware update job profiles", "Bulk device registration imports", "Fleet Indexing search search queries", "Secure Tunneling remote SSH paths"],
    useCases: ["Pushing firmware updates to 10,000 smart meters", "Searching device logs for system errors", "Creating secure console connections to smart gates"],
    pricingModels: ["Active registered device Monthly rate", "OTA Job execution task counts"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }],
    keywords: ["device management", "ota update", "fleet registry", "secure tunnel"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iot-device-management/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1860,
    comparisonTags: ["IoT Device Management", "Systems Management"]
  },
  {
    serviceCode: "iotdevicedefender",
    name: "AWS IoT Device Defender",
    slug: "aws-iot-device-defender",
    categorySlug: "iot",
    shortDescription: "Secure your IoT device fleet with security audits.",
    fullDescription: "AWS IoT Device Defender is a fully managed security service that allows you to secure your fleet of IoT devices, performing continuous security audits.",
    characteristics: ["Fleet anomaly detection alerts", "Best practices security checks", "Automated remediation setups"],
    features: ["Device behavior anomaly checks", "Client certificate expiry scans", "Shared network socket audits", "Alert notifications routing (SNS)"],
    useCases: ["Detecting if a smart lock connects to raw IPs", "Auditing client certificates security keys expiration", "Detecting spikes in device network traffic"],
    pricingModels: ["Active monitored device per Month fee", "Security checks run volume"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }, { name: "Amazon SNS", slug: "amazon-sns" }],
    keywords: ["iot defender", "device security", "certificate audit", "iot anomaly check"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iot-device-defender/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1870,
    comparisonTags: ["Security Audit", "IoT Device Management"]
  },
  {
    serviceCode: "iotanalytics",
    name: "AWS IoT Analytics",
    slug: "aws-iot-analytics",
    categorySlug: "iot",
    shortDescription: "Run analytics on massive volumes of IoT data.",
    fullDescription: "AWS IoT Analytics is a fully managed service that makes it easy to run and operationalize sophisticated analytics on massive volumes of IoT data.",
    characteristics: ["Time-series optimized data lakes", "No-code clean and format pipelines", "SQL query interfaces analytical center"],
    features: ["Data pipeline filtering modules", "Time-series database tables structures", "SQL analytical query console", "QuickSight analytics dashboard integrations"],
    useCases: ["Cleaning dirty smart meter telemetry formats", "Calculating rolling averages of sensor data", "Reporting factory machine efficiency analytics"],
    pricingModels: ["Data Processed volume per GB", "Data stored in analytics repository per GB"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }, { name: "Amazon QuickSight", slug: "amazon-quicksight" }],
    keywords: ["iot analytics", "sensor database", "telemetry etl", "sensor dashboard"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iotanalytics/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1880,
    comparisonTags: ["IoT Solution", "Data Lake", "Analytics Engine"]
  },
  {
    serviceCode: "iotsitewise",
    name: "AWS IoT SiteWise",
    slug: "aws-iot-sitewise",
    categorySlug: "iot",
    shortDescription: "Collect, organize, and analyze industrial equipment data.",
    fullDescription: "AWS IoT SiteWise is a managed service that makes it easy to collect, store, organize, and monitor data from industrial equipment at scale to make better decisions.",
    characteristics: ["Industrial protocol gateways compatibility", "Structured physical asset models templates", "Built-in visual dashboards panels"],
    features: ["SiteWise Edge Gateway software setup", "OPC-UA industrial protocol parser support", "Asset asset parameter dashboards creation", "L4S system alert configurations"],
    useCases: ["Collecting factory floor sensor data databases", "Visualizing assembly line equipment temperatures", "Calculating Overall Equipment Effectiveness (OEE) parameters"],
    pricingModels: ["Data volume ingested per GB", "Data processed per GB", "SiteWise active dashboard users"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }],
    keywords: ["sitewise", "opc ua", "factory analytics", "oee metric", "industrial metrics"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iot-sitewise/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1890,
    comparisonTags: ["IoT Solution", "Predictive Maintenance", "Visualization"]
  },
  {
    serviceCode: "iotevents",
    name: "AWS IoT Events",
    slug: "aws-iot-events",
    categorySlug: "iot",
    shortDescription: "Detect and respond to events from IoT sensors.",
    fullDescription: "AWS IoT Events is a fully managed service that makes it easy to detect and respond to events from IoT sensors and applications, using state logic.",
    characteristics: ["Real-time state logic engines", "Multi-sensor telemetry logic evaluation", "Serverless alert triggers scaling"],
    features: ["Event detector model state diagrams", "Alert condition threshold definitions", "Trigger actions rules (Lambda, SQS, SNS)", "Console state tracker debugger"],
    useCases: ["Alerting when a pipe sensor reports low pressure", "Triggering sprinkler valves when temperature hits 100", "Managing robotic state change logs alarms"],
    pricingModels: ["Event evaluations volume (per million)"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }, { name: "Amazon SNS", slug: "amazon-sns" }],
    keywords: ["iot events", "event detector", "sensor threshold", "alert system"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iotevents/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1900,
    comparisonTags: ["IoT Solution", "Event Router"]
  },
  {
    serviceCode: "iotgreengrass",
    name: "AWS IoT Greengrass",
    slug: "aws-iot-greengrass",
    categorySlug: "iot",
    shortDescription: "Run local compute and ML on IoT devices offline.",
    fullDescription: "AWS IoT Greengrass is an open-source IoT edge runtime and cloud service that helps you build, deploy, and manage device software on local hardware units.",
    characteristics: ["Local physical device execution runtime", "Offline operation capabilities", "Local MQTT routing logic"],
    features: ["Local Lambda/Container execution frameworks", "Machine learning local inference maps", "Greengrass software component packaging", "AWS IoT Core state shadow syncs"],
    useCases: ["Running anomaly model tests on factory cameras", "Operating smart home hubs during Internet outages", "Filtering local sensor logs before cloud uploads"],
    pricingModels: ["Active Greengrass core registered device per Month"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }],
    keywords: ["greengrass", "edge compute", "offline iot", "local lambda", "device container"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/greengrass/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1910,
    comparisonTags: ["Edge Compute", "IoT Platform", "Open Source Engine"]
  },
  {
    serviceCode: "iotlorawan",
    name: "AWS IoT Core for LoRaWAN",
    slug: "aws-iot-core-for-lorawan",
    categorySlug: "iot",
    shortDescription: "Connect wireless LoRaWAN devices to AWS IoT Core.",
    fullDescription: "AWS IoT Core for LoRaWAN allows you to connect private wireless LoRaWAN (Low-Power Long-Range WAN) devices and gateways directly to AWS IoT Core without a local LoRa network server.",
    characteristics: ["Long-range wireless protocol gateways", "Low-power device connectivity supports", "Serverless network server setups"],
    features: ["LoRaWAN Gateway registration templates", "Device profile configuration databases", "MQTT packet decoders (Lambda hooks)", "Console network join statistics"],
    useCases: ["Collecting soil moisture sensor arrays data", "Tracking street light status logs over campuses", "Monitoring smart agriculture greenhouse meters"],
    pricingModels: ["Active LoRaWAN Gateway Hourly rate", "LoRaWAN Uplink message counts"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }],
    keywords: ["lorawan", "lora gateway", "wireless iot", "low power sensor"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iot/latest/developerguide/iot-lorawan.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 1920,
    comparisonTags: ["IoT Platform", "Networking Hub"]
  },
  {
    serviceCode: "iotroborunner",
    name: "AWS IoT RoboRunner",
    slug: "aws-iot-roborunner",
    categorySlug: "iot",
    shortDescription: "Orchestrate robot fleets and optimize warehouse routing.",
    fullDescription: "AWS IoT RoboRunner is a managed service that helps you build and run applications that orchestrate fleets of automated guided vehicles (AGVs) and autonomous mobile robots (AMRs).",
    characteristics: ["Robotics fleet orchestration interfaces", "Standardized message payload formats", "Real-time routing optimization logic"],
    features: ["Robot status telemetry registers", "Collision prevention path rules", "Shared path routing matrices", "RoboRunner developer API integrations"],
    useCases: ["Managing automated forklift paths in warehouses", "Preventing robotic unit collisions on factory floors", "Consolidating robot status metrics to one dashboard"],
    pricingModels: ["Active managed Robotic Unit Monthly fee"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }],
    keywords: ["roborunner", "robotics", "amr fleet", "warehouse automation"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iotroborunner/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1930,
    comparisonTags: ["IoT Solution", "Robotics Orchestration"]
  },
  {
    serviceCode: "iotfleetwise",
    name: "AWS IoT FleetWise",
    slug: "aws-iot-fleetwise",
    categorySlug: "iot",
    shortDescription: "Collect and transfer vehicle telemetry data at scale.",
    fullDescription: "AWS IoT FleetWise is a managed service that makes it easy for automotive companies to collect, transform, and transfer vehicle telemetry data to the cloud at scale.",
    characteristics: ["Automotive CAN-bus protocol compatibility", "Targeted telemetry log collection rules", "High-volume data pipeline scaling"],
    features: ["Vehicle CAN-bus sensor mapping models", "Edge filtering collect logic policies", "Dynamic target upload conditions (Wifi/Cellular)", "VPC S3 data lake direct connections"],
    useCases: ["Collecting electric car battery telemetry logs", "Scanning vehicle sensor logs for engine errors", "Ingesting smart car driving assistance metadata"],
    pricingModels: ["Active registered Vehicle Monthly fee", "Data volume processed per GB"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["fleetwise", "automotive iot", "can bus", "car telemetry", "vehicle sensor"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iot-fleetwise/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1940,
    comparisonTags: ["IoT Solution", "Data Replication"]
  },

  // END USER COMPUTING
  {
    serviceCode: "workspaces",
    name: "Amazon WorkSpaces",
    slug: "amazon-workspaces",
    categorySlug: "end-user-computing",
    shortDescription: "Managed, secure cloud desktops for remote employees.",
    fullDescription: "Amazon WorkSpaces is a fully managed, secure cloud desktop service. It helps you provision Windows or Linux desktops in just a few minutes, scaling globally.",
    characteristics: ["Persistent virtual desktop instances (VDI)", "Enterprise directory link integrations", "Low latency streaming protocols"],
    features: ["Windows and Linux OS setups options", "SSO Active Directory configurations", "MFA profile access control", "Personal cloud storage mounts sync"],
    useCases: ["Providing virtual workspaces for remote contractors", "Securing developer workstations against local downloads", "Setting up call center agent workspaces quickly"],
    pricingModels: ["Predictable Monthly bundle fee", "Hourly auto-stop usage billing"],
    relatedServices: [{ name: "AWS Directory Service", slug: "aws-directory-service" }],
    keywords: ["vdi", "workspaces", "cloud desktop", "virtual windows", "remote workplace"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/workspaces/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1950,
    comparisonTags: ["Virtual Desktop", "DaaS"]
  },
  {
    serviceCode: "workspacesweb",
    name: "Amazon WorkSpaces Web",
    slug: "amazon-workspaces-web",
    categorySlug: "end-user-computing",
    shortDescription: "Secure browser access to private internal websites.",
    fullDescription: "Amazon WorkSpaces Web is a low-cost, fully managed workspace solution that enables secure browser access to internal corporate websites and SaaS applications.",
    characteristics: ["Non-persistent remote browser sessions", "Strict local data download blockers", "Zero endpoint client software setups"],
    features: ["Managed secure browser container instances", "VPC private route access rules", "SSO identity credentials maps integration", "Client clipboard copy restrict rules"],
    useCases: ["Allowing employees secure access to intranet sites", "Blocking contractors from downloading CRM database tables", "Secure web portal access from personal computers"],
    pricingModels: ["Per Active User per Month ($7.00)"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["browser workspaces", "workspaces web", "intranet access", "secure browser container"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/workspaces-web/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1960,
    comparisonTags: ["Secure Browser", "DaaS"]
  },
  {
    serviceCode: "appstream",
    name: "Amazon AppStream 2.0",
    slug: "amazon-appstream-2",
    categorySlug: "end-user-computing",
    shortDescription: "Stream desktop applications securely to any device.",
    fullDescription: "Amazon AppStream 2.0 is a fully managed non-persistent application delivery service that streams desktop applications to HTML5 browsers on any device.",
    characteristics: ["Non-persistent app streaming instances", "High performance GPU application support", "Browser-based application access"],
    features: ["HTML5 web browser client compatibility", "Active Directory credentials syncs", "User file storage connectors (S3/Google Drive)", "Application installer image builder tools"],
    useCases: ["Streaming complex 3D CAD apps to browser tabs", "Running legacy tax apps on Chromebook computers", "Deploying digital classrooms application environments"],
    pricingModels: ["AppStream Instance Hourly execution rate", "Microsoft RDS User license fee"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["appstream", "app streaming", "legacy app browser", "virtual applications"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/appstream2/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1970,
    comparisonTags: ["Application Delivery", "DaaS"]
  },

  // BUSINESS APPLICATIONS
  {
    serviceCode: "chime",
    name: "Amazon Chime",
    slug: "amazon-chime",
    categorySlug: "business-applications",
    shortDescription: "Frustration-free video conferencing and corporate chat.",
    fullDescription: "Amazon Chime is a secure communication service that lets you meet, chat, and place business calls inside and outside your organization, with high quality audio.",
    characteristics: ["Corporate chat and audio channels", "High definition video conference screens", "Standard corporate directory integrations"],
    features: ["Video meeting schedules console", "Interactive screen sharing controls", "SIP phone trunk phone lines", "Active directory single sign-on"],
    useCases: ["Conducting corporate video conference meetings", "Employee team text conversations", "Routing corporate office phone calls"],
    pricingModels: ["Pro User per Day rate", "Standard phone connection minutes rates"],
    relatedServices: [{ name: "Amazon Chime SDK", slug: "amazon-chime-sdk" }],
    keywords: ["chime", "video conference", "business call", "chat app"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/chime/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1980,
    comparisonTags: ["Corporate Chat", "Video Conferencing"]
  },
  {
    serviceCode: "chimesdk",
    name: "Amazon Chime SDK",
    slug: "amazon-chime-sdk",
    categorySlug: "business-applications",
    shortDescription: "Build real-time video, audio, and messaging into apps.",
    fullDescription: "Amazon Chime SDK lets developers add real-time audio, video, screen sharing, and messaging capabilities directly to their web and mobile applications.",
    characteristics: ["Developer communication components package", "High-quality WebRTC audio/video endpoints", "Serverless messaging scaling"],
    features: ["WebRTC audio/video meeting APIs", "Data channel message syncs", "Amazon Lex chatbot integrations support", "Voice transcription pipelines links"],
    useCases: ["Adding customer support video chat to web apps", "Building custom telehealth video portals", "Adding live audio conference rooms to apps"],
    pricingModels: ["Meeting participant connection minute fee", "Messaging API operations volume"],
    relatedServices: [{ name: "Amazon Chime", slug: "amazon-chime" }, { name: "Amazon Transcribe", slug: "amazon-transcribe" }],
    keywords: ["chime sdk", "video api", "webrtc audio", "chat messaging sdk"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/chime-sdk/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1990,
    comparisonTags: ["Communication API", "WebRTC Gateway"]
  },
  {
    serviceCode: "workmail",
    name: "Amazon WorkMail",
    slug: "amazon-workmail",
    categorySlug: "business-applications",
    shortDescription: "Secure, managed business email and calendar service.",
    fullDescription: "Amazon WorkMail is a secure, managed business email and calendar service with support for existing desktop and mobile email client applications.",
    characteristics: ["Managed secure email servers", "Standard email client protocols support (IMAP/Exchange)", "Directory integration permissions"],
    features: ["Microsoft Outlook client compatibility", "Spam and malware scanning rules", "KMS email storage encryption keys", "VPC private email network routing"],
    useCases: ["Setting up corporate employee email address domains", "Managing shared corporate team calendar bookings", "Enforcing secure email storage rules"],
    pricingModels: ["Per User mailbox per Month ($4.00)"],
    relatedServices: [{ name: "AWS Directory Service", slug: "aws-directory-service" }],
    keywords: ["workmail", "business email", "outlook cloud", "calendar service"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/workmail/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2000,
    comparisonTags: ["Corporate Email", "Calendar Service"]
  },
  {
    serviceCode: "connect",
    name: "Amazon Connect",
    slug: "amazon-connect",
    categorySlug: "business-applications",
    shortDescription: "Cloud-based omnichannel contact center platform.",
    fullDescription: "Amazon Connect is an easy-to-use, cloud-based, omnichannel contact center service that helps businesses provide customer service at lower cost.",
    characteristics: ["Visual IVR routing flows builder", "Omnichannel chat/voice/tasks queues", "Serverless agent count scaling"],
    features: ["Contact Flow drag-and-drop designer", "Lex NLU voice bot integrations", "Customer profile database cards", "Real-time call sentiment analytics"],
    useCases: ["Deploying large corporate support call centers", "Automating user checkouts over phone IVR", "Managing customer support agent chat queues"],
    pricingModels: ["Per Customer Connection Minute", "Active Agent connection hour"],
    relatedServices: [{ name: "Amazon Lex", slug: "amazon-lex" }, { name: "Amazon Polly", slug: "amazon-polly" }],
    keywords: ["contact center", "ivr", "connect phone", "customer support line", "agent queue"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/connect/",
    isFeatured: true,
    status: "GA",
    displayOrder: 2010,
    comparisonTags: ["Contact Center Platform", "Communication API"]
  },
  {
    serviceCode: "wickr",
    name: "AWS Wickr",
    slug: "aws-wickr",
    categorySlug: "business-applications",
    shortDescription: "Secure, end-to-end encrypted enterprise chat app.",
    fullDescription: "AWS Wickr is an end-to-end encrypted collaboration service that helps secure enterprise communications with messaging, calling, and file sharing.",
    characteristics: ["Zero-trust cryptography parameters", "Ephemeral message timer setups", "Secure enterprise network access profiles"],
    features: ["End-to-end encrypted text chat", "Encrypted document attachments share", "Administrative message retention policies", "SSO Active Directory logins"],
    useCases: ["Secure team communication for military operations", "Confidential company corporate merger discussion channels", "Protected patient health discussion chat spaces"],
    pricingModels: ["Active User per Month subscription plans"],
    relatedServices: [{ name: "AWS Directory Service", slug: "aws-directory-service" }],
    keywords: ["wickr", "encrypted chat", "ephemeral message", "secure talk"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/wickr/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2020,
    comparisonTags: ["Corporate Chat", "Data Privacy"]
  },
  {
    serviceCode: "supplychain",
    name: "AWS Supply Chain",
    slug: "aws-supply-chain",
    categorySlug: "business-applications",
    shortDescription: "ML-powered supply chain visibility application.",
    fullDescription: "AWS Supply Chain is an application that helps businesses increase visibility, mitigate inventory stockout risks, and optimize supply chains using ML models.",
    characteristics: ["Aggregated supply data lake views", "ML stock outage predictions", "Team workflow collaborations center"],
    features: ["ERP database import connector links", "Inventory level anomaly checks", "Lead time predictor metrics reports", "Inventory transfer action workflows"],
    useCases: ["Tracking warehouse stock level shortages", "Predicting delivery delays from factories", "Optimizing logistics routes between stores"],
    pricingModels: ["Active User per Month subscription"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["supply chain", "inventory tracking", "logistics ml", "stock alert"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/supplychain/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2030,
    comparisonTags: ["ERP Application", "Predictive Analytics"]
  },

  // CUSTOMER ENGAGEMENT
  {
    serviceCode: "pinpoint",
    name: "Amazon Pinpoint",
    slug: "amazon-pinpoint",
    categorySlug: "customer-engagement",
    shortDescription: "Engage customers across push, email, SMS, and voice.",
    fullDescription: "Amazon Pinpoint is a flexible and scalable multichannel communication service that helps you connect with your customers over email, SMS, push notifications, or voice.",
    characteristics: ["Customer segment target builders", "Multichannel alert delivery routing", "Campaign success analytics reports"],
    features: ["User segment database imports", "A/B testing campaign planners", "HTML email templates editor", "SNS outbound SMS integration"],
    useCases: ["Sending corporate promotional email campaigns", "Sending user push alerts for app updates", "Configuring target marketing SMS groups"],
    pricingModels: ["Active Targeted Users Monthly fee", "Emails sent volume", "SMS Messages sent rates"],
    relatedServices: [{ name: "Amazon SES", slug: "amazon-ses" }, { name: "Amazon SNS", slug: "amazon-sns" }],
    keywords: ["marketing", "pinpoint", "sms campaign", "push notifications", "ab test", "campaigns"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/pinpoint/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2040,
    comparisonTags: ["Marketing Automation", "Communication API"]
  },
  {
    serviceCode: "ses",
    name: "Amazon SES",
    slug: "amazon-ses",
    categorySlug: "customer-engagement",
    shortDescription: "High-volume, scalable, and secure email sending service.",
    fullDescription: "Amazon Simple Email Service (SES) is a cost-effective, flexible, and scalable email service that enables developers to send mail from within any application.",
    characteristics: ["High email inbox delivery ratings", "High-volume SMTP endpoints", "Dynamic email sender reputations monitors"],
    features: ["SMTP server interface credentials", "DKIM/SPF domain verification keys", "Dedicated IP address allocations", "Inbound email processing endpoints (S3 links)"],
    useCases: ["Sending password reset transaction emails", "High-volume customer email marketing runs", "Processing inbound user support emails in code"],
    pricingModels: ["Emails sent volume (per thousand) (Free if sent from EC2)"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["smtp", "ses email", "email sender", "mail server", "bulk mail", "ses"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/ses/",
    isFeatured: true,
    status: "GA",
    displayOrder: 2050,
    comparisonTags: ["SMTP Service", "Communication API"]
  },
  {
    serviceCode: "pinpointpush",
    name: "Amazon Pinpoint SMS & Voice",
    slug: "amazon-pinpoint-sms-voice",
    categorySlug: "customer-engagement",
    shortDescription: "Managed API for sending high-volume text and voice messages.",
    fullDescription: "Amazon Pinpoint SMS and Voice provides a dedicated API workspace to send SMS text and voice messages directly, bypass marketing segment consoles.",
    characteristics: ["Developer-centric messaging APIs", "Global phone number registration registries", "Strict operational routing filters"],
    features: ["Long code / Short code registration interfaces", "Sender ID verification keys", "Two-Factor Auth text verification presets", "Audio voice call synthesis (Polly)"],
    useCases: ["Sending authentication PIN codes via SMS", "Automated telephone text alert messages", "High throughput transactional notifications"],
    pricingModels: ["Dedicated Phone Number Monthly registration fee", "SMS sent rates per Country"],
    relatedServices: [{ name: "Amazon Pinpoint", slug: "amazon-pinpoint" }],
    keywords: ["sms api", "text code", "voice call api", "pinpoint sms"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/pinpoint/latest/developerguide/welcome-sms-voice.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2060,
    comparisonTags: ["Communication API", "SMS Gateway"]
  },

  // BLOCKCHAIN
  {
    serviceCode: "managedblockchain",
    name: "Amazon Managed Blockchain",
    slug: "amazon-managed-blockchain",
    categorySlug: "blockchain",
    shortDescription: "Configure and manage public and private blockchain networks.",
    fullDescription: "Amazon Managed Blockchain is a fully managed service that makes it easy to join public networks or create and manage scalable private blockchain networks.",
    characteristics: ["Hyperledger Fabric and Ethereum frameworks support", "Automated network node provisioning", "Secure shared ledger database logic"],
    features: ["Blockchain node instance configurations", "Consensus protocol automation modules", "VPC endpoint networking integration", "Managed blockchain query APIs"],
    useCases: ["Running private supply chain ledger nodes", "Interacting with public Ethereum testnets", "Developing secure smart contract application layers"],
    pricingModels: ["Active Blockchain Node Hourly rate", "Data processed per GB Volume"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["blockchain", "ethereum", "hyperledger", "smart contracts", "ledger node"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/managed-blockchain/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2070,
    comparisonTags: ["Blockchain Infrastructure", "Database Service"]
  },
  {
    serviceCode: "qldb",
    name: "Amazon QLDB",
    slug: "amazon-qldb",
    categorySlug: "blockchain",
    shortDescription: "Fully managed ledger database providing cryptographic transaction history.",
    fullDescription: "Amazon Quantum Ledger Database (QLDB) is a fully managed ledger database that provides a transparent, immutable, and cryptographically verifiable transaction log.",
    characteristics: ["Immutable database journal logs", "Cryptographic verification proofs", "Central database authority configuration"],
    features: ["SQL-like query syntax (PartiQL)", "Data hash chains verification tables", "Automatic journal data replication", "No-schema JSON document inputs"],
    useCases: ["Tracking banking transaction balance ledgers", "Recording supply chain hardware ownership records", "Maintaining system access log registries"],
    pricingModels: ["Read/Write database operations volume", "Journal storage consumed GB/Month"],
    relatedServices: [{ name: "AWS KMS", slug: "aws-kms" }],
    keywords: ["qldb", "ledger database", "immutable log", "cryptographic history", "audit log db"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/qldb/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2080,
    comparisonTags: ["Ledger Database", "NoSQL Database"]
  },

  // QUANTUM TECHNOLOGIES
  {
    serviceCode: "braket",
    name: "Amazon Braket",
    slug: "amazon-braket",
    categorySlug: "quantum",
    shortDescription: "Access quantum computing hardware and simulator engines.",
    fullDescription: "Amazon Braket is a fully managed quantum computing service designed to help researchers and developers build, test, and run quantum algorithms.",
    characteristics: ["Physical QPU hardware access interfaces", "Serverless simulator runtimes", "Unified quantum SDK bindings"],
    features: ["Access to IonQ, Rigetti, OQC QPUs", "Quantum circuit builder interfaces", "Hybrid quantum-classical algorithms (PennyLane)", "Jupyter notebooks testing dashboards"],
    useCases: ["Running chemistry molecule simulator tests", "Researching quantum optimization algorithms", "Testing quantum circuit error calculations"],
    pricingModels: ["QPU Task execution fee", "QPU Shot fee (per run)", "Simulator node execution hour"],
    relatedServices: [{ name: "Amazon SageMaker", slug: "amazon-sagemaker" }],
    keywords: ["braket", "quantum computer", "qpu", "qubit", "ionq rigetti"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/braket/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2090,
    comparisonTags: ["Quantum Computing", "HPC Processing"]
  },

  // SATELLITE
  {
    serviceCode: "groundstation",
    name: "AWS Ground Station",
    slug: "aws-ground-station",
    categorySlug: "satellite",
    shortDescription: "Managed satellite communication ground stations network.",
    fullDescription: "AWS Ground Station is a fully managed service that lets you control satellite communications, process downlink telemetry data, and scale your satellite operations.",
    characteristics: ["Global physical parabolic antenna grids", "Direct VPC data downlink routing", "Dynamic antenna reservation scheduling"],
    features: ["Antenna scheduling console calendars", "Digital signal processing software filters", "Encrypted downlink data networks", "VPC subnet receiver endpoints"],
    useCases: ["Scheduling weather satellite data downloads", "Routing earth-imaging satellite telemetry to S3", "Controlling private corporate satellite orbits parameters"],
    pricingModels: ["Antenna connection reservation minutes"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["ground station", "satellite receiver", "antenna downlink", "space telemetry"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/ground-station/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2100,
    comparisonTags: ["Satellite Ground Station", "On-Premises Infrastructure"]
  },

  // FRONT-END WEB & MOBILE
  {
    serviceCode: "amplify",
    name: "AWS Amplify",
    slug: "aws-amplify",
    categorySlug: "frontend-mobile",
    shortDescription: "Fast web/mobile backends builder framework.",
    fullDescription: "AWS Amplify is a set of purpose-built tools and features that lets frontend web and mobile developers quickly and easily build full-stack applications.",
    characteristics: ["Developer-centric backend scaffolding", "Direct code framework UI libraries", "Serverless resources compiler"],
    features: ["Amplify CLI configuration setup", "Authentication screens UI widgets", "GraphQL/REST api schemas constructor", "Amplify Admin UI visual databases console"],
    useCases: ["Fast backend setups for React web apps", "Adding user authentication to mobile apps in codes", "Structuring serverless backends for web dashboards"],
    pricingModels: ["No extra charge (pay for underlying Cognito/AppSync/S3 resources)"],
    relatedServices: [{ name: "Amazon Cognito", slug: "amazon-cognito" }, { name: "AWS AppSync", slug: "aws-appsync" }],
    keywords: ["amplify", "frontend backend", "react aws", "mobile backend", "graphql amplify", "fullstack"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/amplify/",
    isFeatured: true,
    status: "GA",
    displayOrder: 2110,
    comparisonTags: ["Frontend BaaS", "Application Management"]
  },
  {
    serviceCode: "devicefarm",
    name: "AWS Device Farm",
    slug: "aws-device-farm",
    categorySlug: "frontend-mobile",
    shortDescription: "Test web and mobile apps on real physical cloud devices.",
    fullDescription: "AWS Device Farm is an application testing service that lets you test and interact with your Android, iOS, and web apps against real physical devices.",
    characteristics: ["Real physical phone/tablet racks", "Automated test script executor sandboxes", "Remote interactive debug sessions"],
    features: ["Android and iOS test runs", "Appium, Espresso, XCTest testing packages support", "VPC network endpoint connections", "VOD screen recording capture profiles"],
    useCases: ["Testing mobile app UI flows on 50+ phone models", "Automating app build test pipelines", "Remote debugging mobile app crashes on specific tablet versions"],
    pricingModels: ["Device testing minutes volume", "Private Dedicated Device Slot per Month ($200.00)"],
    relatedServices: [{ name: "AWS CodePipeline", slug: "aws-code-pipeline" }],
    keywords: ["device farm", "mobile testing", "ios testing", "real devices", "appium test"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/devicefarm/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2120,
    comparisonTags: ["Testing Tool", "DaaS"]
  },
  {
    serviceCode: "locationservice",
    name: "Amazon Location Service",
    slug: "amazon-location-service",
    categorySlug: "frontend-mobile",
    shortDescription: "Add maps, geocoding, and tracking to applications.",
    fullDescription: "Amazon Location Service makes it easy for developers to add location functionality, such as maps, points of interest, geocoding, routing, and tracking.",
    characteristics: ["GDPR compliant location databases", "High-speed maps server tiles", "Third-party map providers (Esri/HERE)"],
    features: ["Interactive map tile servers", "Address geocoding/reverse-geocoding APIs", "Geofence boundary alerts configuration", "Device trackers historical points logging"],
    useCases: ["Adding map displays to websites", "Calculating drive route distances between delivery points", "Triggering alerts when delivery vehicles cross geofence gates"],
    pricingModels: ["Map tiles requested volume", "Geocoding API queries volume", "Geofence evaluations count"],
    relatedServices: [{ name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["maps", "geofencing", "location service", "gps tracker", "address search"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/location/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2130,
    comparisonTags: ["Location API", "Front-End Web & Mobile", "API AI Service"]
  },
  {
    serviceCode: "amplifyhosting",
    name: "AWS Amplify Hosting",
    slug: "aws-amplify-hosting",
    categorySlug: "frontend-mobile",
    shortDescription: "Fully managed static and SSR web hosting service.",
    fullDescription: "AWS Amplify Hosting is a fully managed static website and server-side rendered (SSR) web hosting service, featuring continuous deployment pipelines.",
    characteristics: ["Git repository auto-deploy pipelines", "Global CDN file caching speedups", "Server-side rendering runtime configurations"],
    features: ["Github/Gitlab repository connector hooks", "Dynamic Next.js SSR build environments", "Free public SSL certificates", "Custom redirect and rewrite rules"],
    useCases: ["Hosting React/Next.js/Vue static websites", "Deploying Next.js server-side rendered web portals", "Fast landing page deployments with continuous deployments"],
    pricingModels: ["Build minutes volume", "Static Data Storage consumed GB/Month", "Data Transfer Out Egress"],
    relatedServices: [{ name: "AWS Amplify", slug: "aws-amplify" }, { name: "Amazon CloudFront", slug: "amazon-cloudfront" }],
    keywords: ["amplify hosting", "web host", "nextjs ssr deploy", "static web deploy", "nextjs hosting"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/amplify/latest/userguide/hosting.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2140,
    comparisonTags: ["Frontend Web Hosting", "CDN Service"]
  }
];
