import { SeedService } from "./seed-services-part1.js";

export const seedServicesPart5: SeedService[] = [
  // GAME DEVELOPMENT
  {
    serviceCode: "gamelift",
    name: "Amazon GameLift",
    slug: "amazon-gamelift",
    categorySlug: "compute",
    shortDescription: "Managed dedicated game server hosting for multiplayer matches.",
    fullDescription: "Amazon GameLift is a fully managed service for deploying, operating, and scaling dedicated, low-latency game servers for multiplayer games.",
    characteristics: ["Multiplayer dedicated server hosting", "Sub-second matchmaking routing", "Automated fleet scaling based on player demand"],
    features: ["GameLift FlexMatch matchmaking", "Spot Instance server cost savings", "Real-time game session metrics dashboards", "Multi-region fleet queues"],
    useCases: ["Hosting Session-based multiplayer games", "Global player matchmaking queues", "Deploying game server updates automatically"],
    pricingModels: ["GameLift Instance Hourly rate", "Data Transfer Egress Out"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["gamelift", "game server", "matchmaking", "multiplayer host", "gamelift hosting"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/gamelift/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2150,
    comparisonTags: ["Game Server Hosting", "Compute Platform"]
  },

  // ROBOTICS
  {
    serviceCode: "robomaker",
    name: "AWS RoboMaker",
    slug: "aws-robomaker",
    categorySlug: "iot",
    shortDescription: "Cloud-based simulation platform for robotics developers.",
    fullDescription: "AWS RoboMaker is a cloud-based simulation service that allows robotics developers to run, scale, and automate simulations without managing infrastructure.",
    characteristics: ["ROS/ROS2 application compatible", "Managed 3D simulation worlds", "Automated robotics testing cycles"],
    features: ["Gazebo, Open-Source Robot simulator support", "Robotics world building templates", "Multi-robot simulation runs", "ROS application packaging scripts"],
    useCases: ["Testing robot navigation algorithms in virtual worlds", "Running automated regression tests for robotic code", "Training robotic AI models in simulations"],
    pricingModels: ["Simulation Unit (SU) Hour execution rate"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }],
    keywords: ["robomaker", "robotics simulation", "ros2", "gazebo simulator", "robotics testing"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/robomaker/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2160,
    comparisonTags: ["Robotics Simulation", "IoT Solution"]
  },

  // ADDITIONAL SERVICES & ENGINE VARIANTS
  {
    serviceCode: "simspaceweaver",
    name: "AWS SimSpace Weaver",
    slug: "aws-simspace-weaver",
    categorySlug: "compute",
    shortDescription: "Run massive spatial simulations in the cloud.",
    fullDescription: "AWS SimSpace Weaver is a managed service that lets you build and run massive-scale spatial simulations, expanding virtual environments across multiple EC2 compute nodes.",
    characteristics: ["Multi-node simulation scaling", "Real-time spatial data routing", "Unreal and Unity engine compatibility"],
    features: ["Spatial grid partitioning rules", "EC2 node interconnect controllers", "SimSpace Weaver SDK integrations", "Dynamic entity simulation tracking"],
    useCases: ["Simulating metropolitan city traffic flows", "Building crowd-dynamic safety simulations", "Virtual sandbox environment scaling"],
    pricingModels: ["SimSpace Weaver compute capacity hour"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["spatial simulation", "simspace", "unreal engine", "city simulation"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/simspaceweaver/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2170,
    comparisonTags: ["High Performance Compute", "Spatial Simulation"]
  },
  {
    serviceCode: "app2container",
    name: "AWS App2Container",
    slug: "aws-app-2-container",
    categorySlug: "compute",
    shortDescription: "Migrate legacy IIS and Java apps into Docker containers.",
    fullDescription: "AWS App2Container is a command line tool that analyzes legacy Java and IIS applications, packaging them directly into Docker images for ECS/EKS.",
    characteristics: ["Automated legacy code packaging", "Container manifest compiler", "CLI-driven workspace tools"],
    features: ["IIS application configuration analyzers", "Docker image builder actions", "ECS/EKS task template generators", "ECR repository push tools"],
    useCases: ["Converting legacy .NET web apps to Docker", "Migrating Java server apps to AWS Fargate", "Containerizing corporate backend applications"],
    pricingModels: ["Free CLI Tool (Pay for deployed resources)"],
    relatedServices: [{ name: "Amazon ECS", slug: "amazon-ecs" }, { name: "Amazon EKS", slug: "amazon-eks" }],
    keywords: ["app2container", "iis migration", "java container", "docker packaging"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/app2container/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2180,
    comparisonTags: ["Legacy Migration", "Container Tool"]
  },
  {
    serviceCode: "portingassistant",
    name: "Porting Assistant for .NET",
    slug: "porting-assistant-for-net",
    categorySlug: "developer-tools",
    shortDescription: "Analyze .NET Framework code for Linux compatibility.",
    fullDescription: "Porting Assistant for .NET is an open-source analysis tool that scans .NET Framework applications and detects NuGet dependency conflicts with .NET Core on Linux.",
    characteristics: ["Source code dependency analyzers", "Linux compatibility check reports", "NuGet package replacement recommendations"],
    features: ["Source code scanner parses", "NuGet package version check database", "Porting replacement recommendation engines", "IDE extension plug-ins"],
    useCases: ["Migrating Windows .NET apps to Linux EC2", "Upgrading legacy .NET Framework to modern .NET Core", "Auditing application dependencies compatibilities"],
    pricingModels: ["Free Open-Source Developer Tool"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["porting", "dotnet migration", "linux dotnet", "nuget compat"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/porting-assistant-dotnet/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2190,
    comparisonTags: ["Migration Utility", "Code Assistant"]
  },
  {
    serviceCode: "parallelcluster",
    name: "AWS ParallelCluster",
    slug: "aws-parallelcluster",
    categorySlug: "compute",
    shortDescription: "Deploy and manage HPC clusters on AWS.",
    fullDescription: "AWS ParallelCluster is an open-source cluster management tool that makes it easy to deploy and manage High Performance Computing (HPC) clusters on AWS.",
    characteristics: ["Slurm scheduler integrations", "Dynamic HPC compute node provisioning", "Shared storage cluster architectures"],
    features: ["Automated Slurm master setups", "Multi-AZ placement group allocations", "EFS/FSx storage mount scripts", "VPC private computing subnet templates"],
    useCases: ["Running academic weather prediction computations", "Simulating aerospace model CFD runs", "Managing enterprise research HPC queues"],
    pricingModels: ["Free tool (Pay for created EC2/FSx resources)"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Amazon FSx", slug: "amazon-fsx" }],
    keywords: ["parallelcluster", "hpc cluster", "slurm", "supercomputer", "cfd simulation"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/parallelcluster/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2200,
    comparisonTags: ["HPC Processing", "Cluster Management"]
  },
  {
    serviceCode: "auroraserverless",
    name: "Amazon Aurora Serverless v2",
    slug: "amazon-aurora-serverless-v2",
    categorySlug: "database",
    shortDescription: "Scale relational database capacity in fractions of a second.",
    fullDescription: "Amazon Aurora Serverless v2 scales database capacity up or down instantly based on application demand, allowing you to run enterprise databases without instance management.",
    characteristics: ["Sub-second database capacity adjustments", "Maintains database connection pools", "Multi-AZ failover and replication support"],
    features: ["Aurora Capacity Unit (ACU) dynamic scaling", "MySQL and PostgreSQL engine support", "Read Replica scaling integration", "Global database replication support"],
    useCases: ["SaaS applications with highly variable traffic", "Low cost development and testing database servers", "Enterprise apps with intermittent peak loads"],
    pricingModels: ["Aurora Capacity Unit (ACU) Hour", "Storage consumed GB/Month"],
    relatedServices: [{ name: "Amazon Aurora", slug: "amazon-aurora" }],
    keywords: ["aurora serverless", "serverless mysql", "serverless postgres", "dynamic db scaling"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html",
    isFeatured: true,
    status: "GA",
    displayOrder: 2210,
    comparisonTags: ["Serverless Database", "Relational Database", "SQL Database"]
  },
  {
    serviceCode: "elasticacheredis",
    name: "ElastiCache for Redis",
    slug: "amazon-elasticache-for-redis",
    categorySlug: "database",
    shortDescription: "Managed Redis caching database for fast data access.",
    fullDescription: "Amazon ElastiCache for Redis provides a fully managed, Redis-compatible in-memory data store for microsecond-latency caching and data streaming.",
    characteristics: ["Microsecond data retrieval responses", "Managed cluster scaling", "Persistent dataset backups option"],
    features: ["Redis cluster mode support", "Multi-AZ replication failovers", "Auto-failover dynamic endpoints", "KMS data encrypt options"],
    useCases: ["SQL query caching buffers", "User session state databases", "Real-time game player leaderboards"],
    pricingModels: ["Cache Node Instance Hourly rate"],
    relatedServices: [{ name: "Amazon ElastiCache", slug: "amazon-elasticache" }],
    keywords: ["redis", "elasticache redis", "in-memory redis", "redis cache"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2220,
    comparisonTags: ["In-Memory Database", "Caching Engine"]
  },
  {
    serviceCode: "elasticachememcached",
    name: "ElastiCache for Memcached",
    slug: "amazon-elasticache-for-memcached",
    categorySlug: "database",
    shortDescription: "Simple managed Memcached in-memory key-value caching.",
    fullDescription: "Amazon ElastiCache for Memcached provides a managed Memcached engine to scale simple in-memory key-value stores and database cache layers.",
    characteristics: ["Sub-millisecond data caching", "Horizontal cache node scaling", "Simple key-value retrieval logic"],
    features: ["Multi-node cluster partitioning", "Memcached protocol client compatibility", "Auto discovery client endpoints", "VPC network cache isolation"],
    useCases: ["Caching web page fragment resources", "Reducing database load on heavy read queries", "Storing simple configuration states"],
    pricingModels: ["Cache Node Instance Hourly rate"],
    relatedServices: [{ name: "Amazon ElastiCache", slug: "amazon-elasticache" }],
    keywords: ["memcached", "elasticache memcached", "caching db", "memcached cluster"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/WhatIs.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2230,
    comparisonTags: ["Caching Engine", "In-Memory Database"]
  },
  {
    serviceCode: "neptuneserverless",
    name: "Amazon Neptune Serverless",
    slug: "amazon-neptune-serverless",
    categorySlug: "database",
    shortDescription: "Scale graph database compute capacity dynamically.",
    fullDescription: "Amazon Neptune Serverless automatically adjusts graph database capacity based on application demand, simplifying graph database management for variable workloads.",
    characteristics: ["Serverless graph traversal scaling", "Compatible with Gremlin and SPARQL", "High availability Multi-AZ database setup"],
    features: ["Neptune Capacity Unit (NCU) dynamic scaling", "Graph database memory auto-allocation", "Read replicas autoscale nodes", "KMS-backed database encryption"],
    useCases: ["Dynamic fraud detection graph checking", "Social network maps with variable queries", "SaaS graph-based knowledge engines"],
    pricingModels: ["Neptune Capacity Unit (NCU) Hour", "Storage consumed GB/Month"],
    relatedServices: [{ name: "Amazon Neptune", slug: "amazon-neptune" }],
    keywords: ["neptune serverless", "serverless graph", "gremlin serverless", "graph scaling"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/neptune/latest/userguide/neptune-serverless.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2240,
    comparisonTags: ["Graph Database", "NoSQL Database", "Serverless Database"]
  },
  {
    serviceCode: "documentdbelastic",
    name: "DocumentDB Elastic Clusters",
    slug: "amazon-documentdb-elastic-clusters",
    categorySlug: "database",
    shortDescription: "Scale JSON document database throughput to millions of writes.",
    fullDescription: "Amazon DocumentDB Elastic Clusters allows you to scale your document database to handle millions of reads and writes per second, partitioning datasets automatically.",
    characteristics: ["Distributed MongoDB API scaling", "Automatic database shard partitioning", "Decoupled compute and storage pools"],
    features: ["Elastic cluster shard controllers", "Support for massive JSON query loads", "Auto-scaling database storage volumes", "Multi-AZ high availability deployments"],
    useCases: ["High volume user profiles JSON archives", "Global e-commerce catalogs document storage", "High scale logging registers"],
    pricingModels: ["Elastic Cluster Compute Hourly rate", "Storage consumed per GB/Month"],
    relatedServices: [{ name: "Amazon DocumentDB", slug: "amazon-documentdb" }],
    keywords: ["documentdb elastic", "mongodb scale", "json shard", "elastic document db"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/documentdb/latest/developerguide/elastic-clusters.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2250,
    comparisonTags: ["NoSQL Database", "Document Database"]
  },
  {
    serviceCode: "transitgatewaypeering",
    name: "Transit Gateway Peering",
    slug: "aws-transit-gateway-peering",
    categorySlug: "networking",
    shortDescription: "Peer Transit Gateways across separate regions.",
    fullDescription: "AWS Transit Gateway Peering allows you to establish peering connections between Transit Gateways in different AWS regions, routing inter-region traffic privately.",
    characteristics: ["Cross-region private network bridge", "Utilizes global AWS high performance network", "Central routing policy integration"],
    features: ["Inter-region routing tables sync", "Encrypted network packet transit", "VPC endpoint network integrations", "Organizations cross-account support"],
    useCases: ["Interconnecting multi-region VPC accounts", "Unified corporate routing topologies", "Global database replication network setups"],
    pricingModels: ["Transit Gateway Peering connection hour", "Data processed per GB Volume"],
    relatedServices: [{ name: "AWS Transit Gateway", slug: "aws-transit-gateway" }],
    keywords: ["peering", "transit gateway peering", "cross region network", "router peering"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2260,
    comparisonTags: ["Cloud Router", "Global Network Routing"]
  },
  {
    serviceCode: "vpcpeering",
    name: "VPC Peering",
    slug: "aws-vpc-peering",
    categorySlug: "networking",
    shortDescription: "Direct private routing connection between two VPCs.",
    fullDescription: "AWS VPC Peering establishes a direct networking connection between two Virtual Private Clouds, enabling private IP traffic routing between them.",
    characteristics: ["Direct private network connection", "Bypasses external gateway bottlenecks", "No single point of network failure"],
    features: ["Intra-region and Inter-region peering", "VPC route table configurations", "Security Group cross-reference rules", "IPv4 and IPv6 traffic support"],
    useCases: ["Connecting app VPC to database VPC", "Sharing resources across partner company accounts", "Low cost multi-VPC infrastructure networks"],
    pricingModels: ["Free (Data Transfer within AZ is free; inter-AZ is normal rate)"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["vpc peering", "peering link", "direct connect vpc", "private peer"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2270,
    comparisonTags: ["Private Connection", "Cloud Routing"]
  },
  {
    serviceCode: "vpcnatgateway",
    name: "VPC NAT Gateway",
    slug: "amazon-vpc-nat-gateway",
    categorySlug: "networking",
    shortDescription: "Allow private subnet instances outbound internet access.",
    fullDescription: "Amazon VPC NAT Gateway is a managed Network Address Translation service that enables resources in private subnets to connect to the internet, while preventing inbound connections.",
    characteristics: ["Managed outbound NAT translation", "Highly available per-AZ scaling", "Simplified routing configuration"],
    features: ["Elastic IP address assignments", "NAT translation mapping tables", "Support for up to 45 Gbps throughput", "VPC route table redirect support"],
    useCases: ["Allowing private EC2 instances database updates", "Permitting private containers API callbacks", "Securing application subnet boundaries"],
    pricingModels: ["NAT Gateway Hourly deployment rate", "Data processed per GB Volume"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["nat gateway", "outbound nat", "private subnet net", "internet gateway"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2280,
    comparisonTags: ["Network Gateway", "VPC Security"]
  },
  {
    serviceCode: "vpcinternetgateway",
    name: "VPC Internet Gateway",
    slug: "amazon-vpc-internet-gateway",
    categorySlug: "networking",
    shortDescription: "Enable public network communications for VPC subnets.",
    fullDescription: "Amazon VPC Internet Gateway is a redundant, highly available VPC component that enables direct public communication between instances in your VPC and the internet.",
    characteristics: ["Two-way public routing bridge", "Zero throughput limits scaling", "No extra configuration setups"],
    features: ["VPC attach/detach CLI actions", "Public IPv4 routing mappings", "IPv6 target routing (Egress-Only)", "Security Group target associations"],
    useCases: ["Enabling web server public routing access", "Providing NAT Gateways internet path access", "Exposing public application load balancers"],
    pricingModels: ["Free (Included with Amazon VPC)"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["internet gateway", "igw", "public route", "vpc gateway", "internet access"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2290,
    comparisonTags: ["Network Gateway", "Cloud Routing"]
  },
  {
    serviceCode: "route53resolver",
    name: "Route 53 Resolver",
    slug: "amazon-route-53-resolver",
    categorySlug: "networking",
    shortDescription: "Forward DNS queries between local networks and VPCs.",
    fullDescription: "Amazon Route 53 Resolver (DNS Bindings) provides a hybrid DNS routing system, enabling name resolution between corporate datacenters and cloud VPCs.",
    characteristics: ["Hybrid DNS resolver endpoint", "Custom DNS forward rules policies", "VPC private DNS integrations"],
    features: ["Inbound DNS endpoints (on-prem query VPC)", "Outbound DNS endpoints (VPC query on-prem)", "Route 53 resolver rule shares (RAM)", "VPC DNS query logging audits"],
    useCases: ["Resolving on-prem server names from EC2 instances", "Forwarding company intranet lookups to local servers", "Auditing VPC DNS queries for malicious lookups"],
    pricingModels: ["Active Resolver Endpoint IP Hour", "DNS Queries resolved volume"],
    relatedServices: [{ name: "Amazon Route 53", slug: "amazon-route-53" }],
    keywords: ["resolver", "dns resolver", "hybrid dns", "dns forwarder", "route 53 resolver"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2300,
    comparisonTags: ["DNS Service", "Domain Management"]
  },
  {
    serviceCode: "route53arc",
    name: "Route 53 Application Recovery Controller",
    slug: "amazon-route-53-application-recovery-controller",
    categorySlug: "networking",
    shortDescription: "Manage active-active application recovery and failover checkpoints.",
    fullDescription: "Amazon Route 53 Application Recovery Controller provides routing control and readiness checks to automate multi-region application recovery failovers.",
    characteristics: ["Active-active recovery managers", "Continuous readiness check diagnostics", "One-click failover execution dashboards"],
    features: ["Routing control switches (DNS switches)", "Workload readiness audit metrics", "Multi-AZ replication status monitors", "IAM backup administrator actions"],
    useCases: ["Managing global multi-region app database failovers", "Auditing cross-region configuration readiness metrics", "Triggering one-click disaster recovery procedures"],
    pricingModels: ["Readiness Checks executed per Month", "Routing Control switches hour"],
    relatedServices: [{ name: "Amazon Route 53", slug: "amazon-route-53" }],
    keywords: ["arc", "recovery controller", "disaster failover", "readiness check", "dns failover"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/r53recovery/latest/dg/what-is-route-53-application-recovery-controller.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2310,
    comparisonTags: ["Disaster Recovery", "Business Continuity", "DNS Service"]
  },
  {
    serviceCode: "verifiedaccess",
    name: "AWS Verified Access",
    slug: "aws-verified-access",
    categorySlug: "security",
    shortDescription: "Provide secure corporate app access without client VPNs.",
    fullDescription: "AWS Verified Access provides secure corporate application access based on Zero Trust principles, validating identities without requiring client VPN software tunnels.",
    characteristics: ["Zero Trust security configurations", "No client software installs required", "Identity provider integration configurations"],
    features: ["OIDC identity provider connectors", "Cedar policy validation engines", "VPC network endpoint connections", "Access request audit logs output"],
    useCases: ["Providing contractors access to intranet sites", "Enforcing device security checks before app login", "Replacing corporate client VPN endpoints"],
    pricingModels: ["Active Verified Access Endpoint Hour", "Data processed per GB Volume"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }, { name: "AWS IAM Identity Center", slug: "aws-iam-identity-center" }],
    keywords: ["verified access", "zero trust", "vpn alternative", "secure portal access"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/verified-access/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2320,
    comparisonTags: ["Access Control", "Identity Management", "Web Protection"]
  },
  {
    serviceCode: "cognitouserpools",
    name: "Cognito User Pools",
    slug: "amazon-cognito-user-pools",
    categorySlug: "security",
    shortDescription: "Managed user identity directory database for apps.",
    fullDescription: "Amazon Cognito User Pools is a managed user directory database that handles app sign-up, sign-in, user profiles, and multi-factor authentication.",
    characteristics: ["Self-service user login portal pages", "Dynamic sign-up profile workflows", "OAuth 2.0 endpoint configurations"],
    features: ["Built-in sign-up hosted Console pages", "OIDC/SAML federated login links", "MFA SMS and email codes scripts", "Custom user attribute database fields"],
    useCases: ["Managing user account login directories", "Verifying customer email addresses automatically", "Enabling user login via Google/Apple credentials"],
    pricingModels: ["Monthly Active Users (MAU) volume tiers (First 50,000 Free)"],
    relatedServices: [{ name: "Amazon Cognito", slug: "amazon-cognito" }],
    keywords: ["user pool", "user database", "login directory", "cognito login"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2330,
    comparisonTags: ["Identity Directory", "Access Control"]
  },
  {
    serviceCode: "cognitoidentitypools",
    name: "Cognito Identity Pools",
    slug: "amazon-cognito-identity-pools",
    categorySlug: "security",
    shortDescription: "Dispense temporary AWS IAM credentials to users.",
    fullDescription: "Amazon Cognito Identity Pools (Federated Identities) enables you to authorize users to access AWS resources directly, dispensing temporary AWS STS credentials.",
    characteristics: ["AWS credentials token dispenser", "Multi-identity provider connector links", "Guest user anonymous access support"],
    features: ["IAM role integration bindings", "STS temporary credentials dispensers", "Developer authenticated identity profiles", "VPC network endpoint connections"],
    useCases: ["Allowing logged-in users to write photo files to S3", "Granting app users DynamoDB table read rights", "Providing guest users temporary access to S3"],
    pricingModels: ["Free (Core IAM access mapping utility)"],
    relatedServices: [{ name: "Amazon Cognito", slug: "amazon-cognito" }, { name: "AWS IAM", slug: "aws-iam" }],
    keywords: ["identity pool", "sts credentials", "temporary keys", "federated identity"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-identity-pools.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2340,
    comparisonTags: ["Identity Management", "Access Control"]
  },
  {
    serviceCode: "comprehendmedical",
    name: "Amazon Comprehend Medical",
    slug: "amazon-comprehend-medical",
    categorySlug: "machine-learning",
    shortDescription: "Extract clinical information from unstructured medical text.",
    fullDescription: "Amazon Comprehend Medical is a HIPAA-eligible natural language processing (NLP) service that extracts clinical information from unstructured electronic health records.",
    characteristics: ["HIPAA compliant medical text parsers", "Pre-trained clinical entity extractors", "No machine learning experience required"],
    features: ["Medical diagnoses (ICD-10) classifications check", "Prescribed drug (RxNorm) data extracts", "PII/PHI patient identity redact checkers", "Medical relationship links tracing"],
    useCases: ["Extracting patient diagnoses from doctor letters", "Analyzing clinical drug dose scripts records", "Redacting PHI from medical datasets for research"],
    pricingModels: ["Medical text characters evaluated volume"],
    relatedServices: [{ name: "Amazon Comprehend", slug: "amazon-comprehend" }],
    keywords: ["comprehend medical", "medical nlp", "fhir text parse", "phi redaction"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/comprehend/latest/dg/medical-comprehend.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2350,
    comparisonTags: ["NLP API", "Medical Database", "HIPAA Storage"]
  },
  {
    serviceCode: "codegurureviewer",
    name: "CodeGuru Reviewer",
    slug: "amazon-code-guru-reviewer",
    categorySlug: "developer-tools",
    shortDescription: "ML-powered automated source code auditing.",
    fullDescription: "Amazon CodeGuru Reviewer uses machine learning and program analysis to identify difficult-to-find bugs and security vulnerabilities during application development.",
    characteristics: ["Automated pull request code scanner", "Best practices security audits checks", "GitHub/CodeCommit repository links"],
    features: ["Java and Python code scanners", "Concurrency bug detection metrics", "OWASP top 10 vulnerability checks", "Automated refactoring code suggestion blocks"],
    useCases: ["Finding memory leaks in Java code in PRs", "Auditing code for hardcoded secrets before commit", "Enforcing corporate code format rules automatically"],
    pricingModels: ["Repository source lines scanned"],
    relatedServices: [{ name: "Amazon CodeGuru", slug: "amazon-codeguru" }],
    keywords: ["reviewer", "code reviews", "automated audit", "pr scanner"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codeguru/latest/reviewer-ug/what-is-codeguru-reviewer.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2360,
    comparisonTags: ["Code Assistant", "DevOps Infrastructure"]
  },
  {
    serviceCode: "codeguruprofiler",
    name: "CodeGuru Profiler",
    slug: "amazon-code-guru-profiler",
    categorySlug: "developer-tools",
    shortDescription: "Analyze application CPU and memory execution profiles.",
    fullDescription: "Amazon CodeGuru Profiler helps developers find their applications' most expensive lines of code by continuously monitoring runtime CPU and memory usage.",
    characteristics: ["Continuous application host agent loops", "Application hot-spot diagnostic graphs", "Operations latency analysis indicators"],
    features: ["JVM/Python runtime profiler agents", "CPU call-stack flame graphs visualization", "Memory leak detection tracking", "Cost optimization scaling suggestions"],
    useCases: ["Debugging server CPU spikes in production", "Optimizing application memory usage allocations", "Finding CPU expensive loops in runtime code"],
    pricingModels: ["Active Profiler Agent Hours"],
    relatedServices: [{ name: "Amazon CodeGuru", slug: "amazon-codeguru" }],
    keywords: ["profiler", "flame graph", "application profiling", "cpu hot spot"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2370,
    comparisonTags: ["Application Performance Monitoring", "Tracing Tool"]
  },
  {
    serviceCode: "athenafederated",
    name: "Athena Federated Query",
    slug: "amazon-athena-federated-query",
    categorySlug: "analytics",
    shortDescription: "Execute SQL queries across databases stored anywhere.",
    fullDescription: "Amazon Athena Federated Query enables you to run SQL queries across data stored in relational, non-relational, object, and custom data sources.",
    characteristics: ["Serverless query federator routers", "Custom data source query connectors", "Single unified SQL query console"],
    features: ["Lambda source connector executions", "SQL query schema mappings catalog", "Athena query editor compatibility", "Glue Data Catalog mapping interfaces"],
    useCases: ["Querying DynamoDB and S3 tables in one query", "Running SQL queries on local RDS databases", "Accessing external data sources from Athena dashboards"],
    pricingModels: ["Athena scanned data per Query TB", "Lambda connector invocation costs"],
    relatedServices: [{ name: "Amazon Athena", slug: "amazon-athena" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["federated query", "athena federated", "cross database sql", "athena lambda"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/athena/latest/ug/connect-to-a-data-source.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2380,
    comparisonTags: ["SQL Query Engine", "Serverless Analytics"]
  },
  {
    serviceCode: "gluedatastreet",
    name: "AWS Glue Data Catalog",
    slug: "aws-glue-data-catalog",
    categorySlug: "analytics",
    shortDescription: "Central database for cloud schema metadata.",
    fullDescription: "AWS Glue Data Catalog provides a centralized metadata repository to store and share database schemas, tables, and partitions for analytics engines.",
    characteristics: ["Central schema database registry", "Glue Crawler schema crawler syncs", "Compatible with Hive Metastore rules"],
    features: ["Schema version history tracking", "Database table partition registers", "Glue crawler automated updates", "Athena/Redshift query mappings catalog"],
    useCases: ["Maintaining query table schemas for Athena", "Sharing database schemas across Redshift and EMR", "Auditing dataset schema modifications over time"],
    pricingModels: ["Free (First million objects stored)", "Active schema objects store monthly rate"],
    relatedServices: [{ name: "AWS Glue", slug: "aws-glue" }, { name: "Amazon Athena", slug: "amazon-athena" }],
    keywords: ["data catalog", "schema registry", "metadata db", "hive metastore"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/glue/latest/dg/populate-data-catalog.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2390,
    comparisonTags: ["Data Registry", "ETL Tool"]
  },
  {
    serviceCode: "elementalmediaconnect",
    name: "AWS Elemental MediaConnect",
    slug: "aws-elemental-mediaconnect",
    categorySlug: "media",
    shortDescription: "High-quality, reliable live video transport service.",
    fullDescription: "AWS Elemental MediaConnect is a high-quality, reliable, and secure live video transport service, routing video feeds between local systems and cloud services.",
    characteristics: ["Durable live video transit pipelines", "Supports major video transport protocols", "Low latency network routing"],
    features: ["SRT, Zixi, RIST video transport support", "Dynamic video replication splits", "BGP network path optimizations", "KMS-backed video flow encryption"],
    useCases: ["Ingesting live camera feeds into MediaLive", "Routing television feeds to global affiliates", "Secure private live broadcast transits"],
    pricingModels: ["Video Flow connection hour", "Data volume sent per GB Egress"],
    relatedServices: [{ name: "AWS Elemental MediaLive", slug: "aws-elemental-medialive" }],
    keywords: ["mediaconnect", "video transport", "live route", "zixi srt", "video flow"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/mediaconnect/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2400,
    comparisonTags: ["Video Processing", "Networking Gateway"]
  },
  {
    serviceCode: "iotdeviceadvisor",
    name: "AWS IoT Core Device Advisor",
    slug: "aws-iot-device-advisor",
    categorySlug: "iot",
    shortDescription: "Validate IoT device connectivity before deployment.",
    fullDescription: "AWS IoT Core Device Advisor is a cloud-based test capability that helps you validate your IoT devices' connectivity and security settings against AWS IoT best practices.",
    characteristics: ["Automated device test suites", "MQTT connection test validation logs", "Pre-built security check criteria"],
    features: ["TLS connection validation scripts", "MQTT client connect mock tests", "Device test report PDF exports", "Console diagnostic error logs"],
    useCases: ["Testing smart lock firmware before shipping", "Validating device MQTT connection retry code", "Auditing device TLS encryption strength compatibility"],
    pricingModels: ["Free (Core validation utility)"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }],
    keywords: ["device advisor", "iot test", "mqtt validator", "firmware check"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iot/latest/developerguide/device-advisor.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2410,
    comparisonTags: ["IoT Device Management", "Testing Tool"]
  },
  {
    serviceCode: "iotsecuretunneling",
    name: "AWS IoT Secure Tunneling",
    slug: "aws-iot-secure-tunneling",
    categorySlug: "iot",
    shortDescription: "Establish secure SSH/HTTP sessions to remote IoT devices.",
    fullDescription: "AWS IoT Secure Tunneling allows you to establish secure bidirectional SSH or HTTP connections to remote devices behind firewalls and NAT gateways.",
    characteristics: ["Secure SSH/HTTP tunnels to devices", "Bypasses local NAT configuration barriers", "No inbound firewall rules required"],
    features: ["Tunnel token dynamic generations", "Local proxy software agent setups", "IAM secure tunnel access policies", "Console active tunnel logs"],
    useCases: ["SSH login to remote smart gates in fields", "Accessing local HTTP dashboards on IoT gateways", "Remote debugging factory machine computers"],
    pricingModels: ["Active Tunnel duration hour"],
    relatedServices: [{ name: "AWS IoT Device Management", slug: "aws-iot-device-management" }],
    keywords: ["secure tunnel", "iot ssh", "nat bypass", "remote shell"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iot/latest/developerguide/secure-tunneling.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2420,
    comparisonTags: ["Systems Management", "On-Premises Gateway"]
  },
  {
    serviceCode: "workspacescore",
    name: "Amazon WorkSpaces Core",
    slug: "amazon-workspaces-core",
    categorySlug: "end-user-computing",
    shortDescription: "Managed VDI infrastructure APIs for custom clients.",
    fullDescription: "Amazon WorkSpaces Core provides cloud desktop virtualization APIs to build customized VDI applications or integrate with third-party software like VMware Horizon.",
    characteristics: ["API-driven VDI host engines", "Third-party virtualization software support", "Managed cloud desktop scalability"],
    features: ["WorkSpace VM creation APIs", "Active Directory credentials syncs", "VPC routing integration support", "KMS volume encryption bindings"],
    useCases: ["Deploying virtual desktops managed by VMware Horizon", "Building custom client VDI administration consoles", "Automating corporate cloud desktop deployments"],
    pricingModels: ["Workspace VM Hourly deployment rate", "Microsoft RDS User licenses fee"],
    relatedServices: [{ name: "Amazon WorkSpaces", slug: "amazon-workspaces" }],
    keywords: ["workspaces core", "vdi api", "vmware horizon aws", "managed vdi host"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/workspaces-core/",
    isFeatured: false,
    status: "GA",
    displayOrder: 2430,
    comparisonTags: ["Virtual Desktop", "DaaS"]
  },
  {
    serviceCode: "appstreamgraphics",
    name: "AppStream Graphics Workstations",
    slug: "amazon-appstream-graphics-workstations",
    categorySlug: "end-user-computing",
    shortDescription: "Stream GPU-accelerated desktop apps to web browsers.",
    fullDescription: "Amazon AppStream 2.0 Graphics Workstations streams high-performance, GPU-accelerated desktop applications to any HTML5 browser for creative workflows.",
    characteristics: ["NVIDIA GPU computing instances", "Low latency streaming protocols", "Browser-based application access"],
    features: ["NVIDIA Tesla/GRID GPU card mounts", "HTML5 browser client compatibility", "S3 dynamic file synchronization", "VPC private network connections rules"],
    useCases: ["Streaming Blender 3D editing programs", "Running CAD design software on web pages", "Virtual engineering laboratory computer classrooms"],
    pricingModels: ["GPU Instance Hourly execution rate", "Microsoft RDS license charges"],
    relatedServices: [{ name: "Amazon AppStream 2.0", slug: "amazon-appstream-2" }],
    keywords: ["appstream graphics", "gpu stream", "3d browser stream", "cad workstation"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/appstream2/latest/developerguide/graphics-design.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2440,
    comparisonTags: ["Application Delivery", "GPU Computing", "DaaS"]
  },
  {
    serviceCode: "wickrenterprise",
    name: "AWS Wickr Enterprise",
    slug: "aws-wickr-enterprise",
    categorySlug: "business-applications",
    shortDescription: "Deploy dedicated Wickr secure chat server environments.",
    fullDescription: "AWS Wickr Enterprise allows organizations to deploy and manage dedicated, isolated Wickr secure chat environments for complete corporate control.",
    characteristics: ["Dedicated encrypted chat server pools", "Strict zero-trust database control", "Corporate compliance logging dashboards"],
    features: ["Dedicated Wickr server cluster deployments", "Corporate data export log compliance check", "SSO Active Directory configurations", "MFA and device control rules"],
    useCases: ["Operating secure communication networks for banks", "Deploying custom secure message vaults for governments", "Audit-compliant secure chat for medical boards"],
    pricingModels: ["Dedicated Wickr Server Hourly rate", "User monthly subscription plans"],
    relatedServices: [{ name: "AWS Wickr", slug: "aws-wickr" }],
    keywords: ["wickr enterprise", "private secure chat", "encrypted messenger server", "compliance chat"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/wickr/latest/adminguide/what-is-wickr.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2450,
    comparisonTags: ["Corporate Chat", "Data Privacy"]
  },
  {
    serviceCode: "managedblockchainquery",
    name: "Managed Blockchain Query",
    slug: "amazon-managed-blockchain-query",
    categorySlug: "blockchain",
    shortDescription: "Serverless read queries access to public blockchain networks.",
    fullDescription: "Amazon Managed Blockchain Query provides serverless, low-latency API access to retrieve transaction history and token balances from public blockchain networks.",
    characteristics: ["Serverless blockchain query endpoints", "Zero public node syncing required", "Consistent query response speeds"],
    features: ["Bitcoin/Ethereum transaction APIs", "Token balance query operations", "Smart contract event traces trackers", "VPC private network endpoint connections"],
    useCases: ["Displaying user Ethereum wallet token balances in apps", "Checking Bitcoin transaction histories in code", "Auditing public smart contract events logs"],
    pricingModels: ["API Query requests volume (per million)"],
    relatedServices: [{ name: "Amazon Managed Blockchain", slug: "amazon-managed-blockchain" }],
    keywords: ["blockchain query", "eth api", "bitcoin history", "wallet balance query"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/managed-blockchain/latest/amb-query-dg/what-is-amb-query.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2460,
    comparisonTags: ["Blockchain Infrastructure", "Database Service"]
  },
  {
    serviceCode: "eventbridgescheduler",
    name: "Amazon EventBridge Scheduler",
    slug: "amazon-eventbridge-scheduler",
    categorySlug: "integration",
    shortDescription: "Create and execute millions of scheduled events.",
    fullDescription: "Amazon EventBridge Scheduler is a serverless scheduler that allows you to create, run, and manage millions of scheduled events and tasks easily.",
    characteristics: ["Massive-scale cron event scheduler", "Serverless trigger execution scaling", "Supports one-time and recurring events"],
    features: ["Cron and Rate expression schedulers", "Trigger targets (Lambda, SQS, SNS, API Gateway)", "Flexible time-window execution offsets", "IAM execution roles validation"],
    useCases: ["Scheduling automated database backups at night", "Triggering user notification cron scripts", "Executing one-time task cancellations after 3 days"],
    pricingModels: ["Active Schedules per Month (First 14 million Free)"],
    relatedServices: [{ name: "Amazon EventBridge", slug: "amazon-eventbridge" }],
    keywords: ["scheduler", "eventbridge scheduler", "cron trigger", "one time schedule"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/scheduler/latest/UserGuide/what-is-scheduler.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2470,
    comparisonTags: ["Event Router", "Serverless Orchestration"]
  },
  {
    serviceCode: "rdspostgresql",
    name: "Amazon RDS for PostgreSQL",
    slug: "amazon-rds-for-postgresql",
    categorySlug: "database",
    shortDescription: "Managed PostgreSQL database service for enterprise apps.",
    fullDescription: "Amazon RDS for PostgreSQL makes it easy to set up, operate, and scale PostgreSQL deployments in the cloud, managing backups and patching.",
    characteristics: ["Managed PostgreSQL server instances", "Multi-AZ replication availability", "POSIX-compliant database indexing"],
    features: ["PostgreSQL version updates control", "Automated backups and point-in-time recovery", "Read replica scale nodes", "KMS database storage encryption"],
    useCases: ["Enterprise application PostgreSQL database hosting", "SaaS multi-tenant database systems", "Migrating local PostgreSQL databases to cloud"],
    pricingModels: ["DB Instance Hourly rate", "Provisioned storage GB/Month"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["rds postgresql", "postgres db", "postgresql", "managed postgres"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2480,
    comparisonTags: ["Relational Database", "SQL Database", "PaaS Database"]
  },
  {
    serviceCode: "rdsmysql",
    name: "Amazon RDS for MySQL",
    slug: "amazon-rds-for-mysql",
    categorySlug: "database",
    shortDescription: "Managed MySQL database service for web applications.",
    fullDescription: "Amazon RDS for MySQL provides a fully managed, scalable MySQL relational database engine in the cloud, handling backup and replication tasks.",
    characteristics: ["Managed MySQL server instances", "Automated database patching", "Multi-AZ replication availability"],
    features: ["MySQL version updates control", "Automated daily backups", "Read replica scale instances", "KMS disk encrypt integrations"],
    useCases: ["Web app MySQL database hosting", "E-commerce transactional databases", "Migrating on-prem MySQL databases to AWS"],
    pricingModels: ["DB Instance Hourly rate", "Provisioned storage GB/Month"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["rds mysql", "mysql db", "managed mysql", "relational mysql"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2490,
    comparisonTags: ["Relational Database", "SQL Database", "PaaS Database"]
  },
  {
    serviceCode: "rdsoracle",
    name: "Amazon RDS for Oracle",
    slug: "amazon-rds-for-oracle",
    categorySlug: "database",
    shortDescription: "Managed Oracle Database deployment service.",
    fullDescription: "Amazon RDS for Oracle makes it easy to set up, operate, and scale Oracle Database deployments in the cloud, supporting various database versions.",
    characteristics: ["Managed Oracle Database servers", "BYOL (Bring Your Own License) or License Included options", "Multi-AZ backup redundancy"],
    features: ["Oracle version updates control", "Automated backups and restorations", "VPC private database subnets", "KMS disk encryption integration"],
    useCases: ["Enterprise ERP Oracle database hosting", "Legacy Oracle database cloud migration", "Managed database setups for business systems"],
    pricingModels: ["DB Instance Hourly rate (License Included / BYOL)", "Provisioned storage GB/Month"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["rds oracle", "oracle db", "managed oracle", "license included oracle"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Oracle.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2500,
    comparisonTags: ["Relational Database", "SQL Database", "PaaS Database"]
  },
  {
    serviceCode: "rdssqlserver",
    name: "Amazon RDS for SQL Server",
    slug: "amazon-rds-for-sql-server",
    categorySlug: "database",
    shortDescription: "Managed Microsoft SQL Server database service.",
    fullDescription: "Amazon RDS for SQL Server makes it easy to set up, operate, and scale SQL Server database deployments, supporting multiple editions like Express, Web, Standard, and Enterprise.",
    characteristics: ["Managed SQL Server instances", "Microsoft SQL Server license options", "Multi-AZ mirroring availability"],
    features: ["SQL Server version updates control", "Automated backups and restorations", "Always On Availability Groups support", "KMS database storage encryption"],
    useCases: ["Windows-centric enterprise app databases", "Microsoft SQL Server cloud migrations", "Managed database setups for corporate systems"],
    pricingModels: ["DB Instance Hourly rate (License Included / BYOL)", "Provisioned storage GB/Month"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["rds sql server", "sql server db", "microsoft sql", "managed sql server"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 2510,
    comparisonTags: ["Relational Database", "SQL Database", "PaaS Database"]
  }
];
