export interface SeedService {
  serviceCode: string;
  name: string;
  slug: string;
  categorySlug: string;
  shortDescription: string;
  fullDescription: string;
  characteristics: string[];
  features: string[];
  useCases: string[];
  pricingModels: string[];
  relatedServices: { name: string; slug: string }[];
  keywords: string[];
  awsDocumentationUrl: string;
  isFeatured?: boolean;
  status?: string;
  displayOrder: number;
  comparisonTags: string[];
  isActive?: boolean;
}

export const seedServicesPart1: SeedService[] = [
  // COMPUTE
  {
    serviceCode: "ec2",
    name: "Amazon EC2",
    slug: "amazon-ec2",
    categorySlug: "compute",
    shortDescription: "Secure and resizable compute capacity in the cloud.",
    fullDescription: "Amazon Elastic Compute Cloud (Amazon EC2) provides resizable, secure compute capacity in the cloud. It allows users to boot virtual machines, customize settings, and scale instance footprints dynamically.",
    characteristics: ["On-demand provisioning", "Full root OS access", "Highly customizable instance types"],
    features: ["Auto Scaling", "Elastic Block Store (EBS) attachments", "Elastic Load Balancing integration", "Flexible OS support"],
    useCases: ["General web application hosting", "Enterprise corporate backend clusters", "Legacy systems migration"],
    pricingModels: ["On-Demand", "Reserved Instances", "Spot Instances", "Savings Plans"],
    relatedServices: [{ name: "Amazon EBS", slug: "amazon-ebs" }, { name: "AWS Auto Scaling", slug: "aws-auto-scaling" }],
    keywords: ["virtual machine", "server", "instances", "ec2", "compute"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/ec2/",
    isFeatured: true,
    status: "GA",
    displayOrder: 10,
    comparisonTags: ["Virtual Machines", "IaaS", "Compute"]
  },
  {
    serviceCode: "lambda",
    name: "AWS Lambda",
    slug: "aws-lambda",
    categorySlug: "compute",
    shortDescription: "Serverless code execution triggered by events.",
    fullDescription: "AWS Lambda lets you run code without provisioning or managing servers. You pay only for the compute time you consume—there is no charge when your code is not running.",
    characteristics: ["Zero server management", "Automatic micro-scaling", "Sub-second execution billing"],
    features: ["Event-driven triggers", "Multi-language support", "Provisioned concurrency options", "VPC routing integration"],
    useCases: ["Microservices architecture backends", "Real-time file processing (S3 triggers)", "Scheduled cron automation"],
    pricingModels: ["Pay-as-you-go per execution", "Provisioned Concurrency"],
    relatedServices: [{ name: "Amazon API Gateway", slug: "amazon-api-gateway" }, { name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["serverless", "function", "lambda", "microservices", "event-driven"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/lambda/",
    isFeatured: true,
    status: "GA",
    displayOrder: 20,
    comparisonTags: ["Serverless", "FaaS", "Compute"]
  },
  {
    serviceCode: "lightsail",
    name: "Amazon Lightsail",
    slug: "amazon-lightsail",
    categorySlug: "compute",
    shortDescription: "Easy-to-use virtual private servers, databases, and plans.",
    fullDescription: "Amazon Lightsail is an easy-to-use virtual private server (VPS) that offers you everything needed to build an application or website, plus a cost-effective, monthly plan.",
    characteristics: ["Simplified user dashboard", "Pre-configured application stacks", "Flat predictable monthly fees"],
    features: ["WordPress single-click deployment", "Integrated DNS and load balancing", "Static IP allocations", "Automatic snapshots"],
    useCases: ["Personal blogs and portfolio sites", "Simple testing servers", "Small-scale e-commerce storefronts"],
    pricingModels: ["Predictable Monthly Tier Bundles"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Amazon Route 53", slug: "amazon-route-53" }],
    keywords: ["vps", "lightsail", "wordpress", "simple virtual server"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/lightsail/",
    isFeatured: false,
    status: "GA",
    displayOrder: 30,
    comparisonTags: ["Virtual Private Server", "VPS", "Simple Hosting"]
  },
  {
    serviceCode: "apprunner",
    name: "AWS App Runner",
    slug: "aws-app-runner",
    categorySlug: "compute",
    shortDescription: "Deploy containerized web apps easily at scale.",
    fullDescription: "AWS App Runner is a fully managed service that makes it easy for developers to quickly deploy containerized web applications and APIs, at scale and with no prior infrastructure experience.",
    characteristics: ["Source code or container inputs", "No server orchestration needed", "Fully managed operations"],
    features: ["Automatic build pipelines", "Built-in HTTPS endpoints", "Auto Scaling on request count", "IAM connection security"],
    useCases: ["Deploying Node.js or Python APIs", "Microservices frontend hosting", "SaaS web portals"],
    pricingModels: ["Active Provisioned CPU/Memory Hourly", "Request Ingestion Fees"],
    relatedServices: [{ name: "Amazon ECR", slug: "amazon-ecr" }, { name: "Amazon ECS", slug: "amazon-ecs" }],
    keywords: ["app runner", "containers", "deployment", "serverless containers"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/apprunner/",
    isFeatured: false,
    status: "GA",
    displayOrder: 40,
    comparisonTags: ["PaaS", "App Deployment", "Serverless Containers"]
  },
  {
    serviceCode: "batch",
    name: "AWS Batch",
    slug: "aws-batch",
    categorySlug: "compute",
    shortDescription: "Fully managed batch computing at any scale.",
    fullDescription: "AWS Batch enables developers, scientists, and engineers to easily and efficiently run hundreds of thousands of batch computing jobs on AWS, automatically scaling resources.",
    characteristics: ["Dynamic provisioning of instances", "Job queue priorities", "Optimal container placement"],
    features: ["Support for Fargate & EC2 spots", "Multi-node parallel tasks", "Array job support", "Priority queue overrides"],
    useCases: ["Financial risk model calculations", "Genome sequence alignments", "Media encoding rendering runs"],
    pricingModels: ["No extra charge (pay for underlying EC2/Fargate resources)"],
    relatedServices: [{ name: "Amazon ECS", slug: "amazon-ecs" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["batch", "jobs", "hpc", "queue processing", "scheduler"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/batch/",
    isFeatured: false,
    status: "GA",
    displayOrder: 50,
    comparisonTags: ["Batch Processing", "HPC Scheduling"]
  },
  {
    serviceCode: "elasticbeanstalk",
    name: "AWS Elastic Beanstalk",
    slug: "aws-elastic-beanstalk",
    categorySlug: "compute",
    shortDescription: "Easy deployment and scaling of web apps.",
    fullDescription: "AWS Elastic Beanstalk is an easy-to-use service for deploying and scaling web applications and services developed with Java, .NET, PHP, Node.js, Python, Ruby, Go, and Docker on familiar servers.",
    characteristics: ["Developer-centric controls", "Full control over underlying resources", "Automated deployment pipelines"],
    features: ["Load balancing auto-configuration", "Rolling update options", "Monitoring health dashboards", "Multi-container support"],
    useCases: ["Java Spring Boot apps deployment", "Node.js REST servers hosting", "Multi-container Docker applications"],
    pricingModels: ["No extra charge (pay for created EC2/RDS resources)"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Elastic Load Balancing", slug: "elastic-load-balancing" }],
    keywords: ["beanstalk", "paas", "java", "php", "deploy"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/Welcome.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 60,
    comparisonTags: ["PaaS", "Application Management"]
  },
  {
    serviceCode: "outposts",
    name: "AWS Outposts",
    slug: "aws-outposts",
    categorySlug: "compute",
    shortDescription: "Run AWS infrastructure and services on-premises.",
    fullDescription: "AWS Outposts is a fully managed service that offers the same AWS infrastructure, AWS services, APIs, and tools to virtually any datacenter, co-location space, or on-premises facility.",
    characteristics: ["Hybrid cloud expansion", "Low local data latency", "Local data processing storage"],
    features: ["Outposts hardware racks", "Local Gateway (LGW) routing", "Supports S3, EC2, ECS, EKS locally", "Managed firmware upgrades"],
    useCases: ["Low latency factory automation systems", "Local medical data residency", "On-prem legacy database integration"],
    pricingModels: ["Hardware leases upfront or monthly payments"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["hybrid", "on-premises", "outposts", "hardware rack"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/outposts/",
    isFeatured: false,
    status: "GA",
    displayOrder: 70,
    comparisonTags: ["Hybrid Cloud", "On-Premises Infrastructure"]
  },
  {
    serviceCode: "wavelength",
    name: "AWS Wavelength",
    slug: "aws-wavelength",
    categorySlug: "compute",
    shortDescription: "Ultra-low latency mobile edge computing via 5G networks.",
    fullDescription: "AWS Wavelength embeds AWS compute and storage services within 5G networks, providing mobile edge computing infrastructure for developing, deploying, and scaling ultra-low-latency applications.",
    characteristics: ["5G mobile carrier network endpoints", "Edge processing architecture", "Reduced round-trip transit times"],
    features: ["Wavelength Zones deployment", "VPC edge subnet allocations", "Seamless AWS API parity", "Carrier network routing"],
    useCases: ["Real-time smart vehicle routing", "Live game video streaming overlays", "Interactive industrial AR headsets"],
    pricingModels: ["Wavelength zone EC2 hourly rates"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["5g", "edge", "mobile edge", "wavelength", "latency"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/wavelength/",
    isFeatured: false,
    status: "GA",
    displayOrder: 80,
    comparisonTags: ["Edge Computing", "5G Network Compute"]
  },
  {
    serviceCode: "localzones",
    name: "AWS Local Zones",
    slug: "aws-local-zones",
    categorySlug: "compute",
    shortDescription: "Deploy applications close to large population centers.",
    fullDescription: "AWS Local Zones place compute, storage, database, and other select AWS services close to large population, industry, and IT centers, so you can deliver applications with single-digit millisecond latency.",
    characteristics: ["Extended metropolitan subnets", "Single-digit millisecond access locally", "AWS cloud unified integration"],
    features: ["Local zone subnets in VPC", "Select service deployments (EC2, EBS)", "Co-location latency benefits", "IAM uniform controls"],
    useCases: ["Real-time financial transactions processing", "Live multiplayer gaming lobbies", "Local media workstations hosting"],
    pricingModels: ["Local Zone instance billing configurations"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["metropolitan", "local zones", "low latency", "edge subnets"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/local-zones/",
    isFeatured: false,
    status: "GA",
    displayOrder: 90,
    comparisonTags: ["Edge Computing", "Low Latency Subnets"]
  },
  {
    serviceCode: "ec2imagebuilder",
    name: "EC2 Image Builder",
    slug: "ec2-image-builder",
    categorySlug: "compute",
    shortDescription: "Automate creation, testing, and deployment of VMs.",
    fullDescription: "EC2 Image Builder simplifies the creation, maintenance, validation, sharing, and deployment of customized, secure, and up-to-date server images (AMIs) that you can run on AWS or on-premises.",
    characteristics: ["Policy-based server baselines", "Automated pipeline logic", "Infrastructure as Code AMIs"],
    features: ["Image testing assertions", "Component builder worksheets", "Multi-account AMI distribution", "Patch management tracking"],
    useCases: ["Creating secure Golden OS baselines", "Automated custom container image builds", "OS patching automation grids"],
    pricingModels: ["No extra charge (pay for EC2 instances used during testing)"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "AWS Systems Manager", slug: "aws-systems-manager" }],
    keywords: ["ami", "image builder", "golden image", "builder pipeline"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/imagebuilder/",
    isFeatured: false,
    status: "GA",
    displayOrder: 100,
    comparisonTags: ["Image Management", "DevOps Infrastructure"]
  },
  {
    serviceCode: "serverlessrepo",
    name: "AWS Serverless Application Repository",
    slug: "aws-serverless-application-repository",
    categorySlug: "compute",
    shortDescription: "Discover, deploy, and publish serverless applications.",
    fullDescription: "The AWS Serverless Application Repository enables you to quickly find, deploy, and publish serverless applications. Teams can collaborate and share components with public or private partitions.",
    characteristics: ["Shareable pre-built templates", "Direct integration with SAM", "Developer showcase registry"],
    features: ["Nested template compositions", "Permissions sharing metadata", "Click-to-deploy Console bindings", "CloudFormation integrations"],
    useCases: ["Publishing open source serverless utility plugins", "Sharing common backend API setups in teams", "Single-click serverless app boots"],
    pricingModels: ["No extra charge (pay for created compute/database resources)"],
    relatedServices: [{ name: "AWS Lambda", slug: "aws-lambda" }, { name: "AWS CloudFormation", slug: "aws-cloudformation" }],
    keywords: ["repository", "serverless applications", "sam", "share code"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/serverlessrepo/",
    isFeatured: false,
    status: "GA",
    displayOrder: 110,
    comparisonTags: ["Registry", "Serverless Components"]
  },
  {
    serviceCode: "lightsailresearch",
    name: "Amazon Lightsail for Research",
    slug: "amazon-lightsail-for-research",
    categorySlug: "compute",
    shortDescription: "Run analytical virtual computers with pre-installed apps.",
    fullDescription: "Amazon Lightsail for Research allows you to run powerful analytical virtual computers in the cloud with pre-installed research applications like RStudio, Scilab, Jupyter, and Octave in clicks.",
    characteristics: ["Pre-configured analytical frameworks", "Browser-based workspace interface", "Predictable monthly bundle plans"],
    features: ["Jupyter Notebooks launch presets", "File storage sync layers", "Automatic idle-timer shutdowns", "Encrypted analytical volumes"],
    useCases: ["Academic research model running", "Python Jupyter data processing sandbox", "Statistical RStudio visualizations"],
    pricingModels: ["Research Instance Bundle Tiers"],
    relatedServices: [{ name: "Amazon Lightsail", slug: "amazon-lightsail" }],
    keywords: ["research", "jupyter", "rstudio", "analytical server"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/lightsail/latest/userguide/what-is-lightsail-for-research.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 120,
    comparisonTags: ["Data Science Workspace", "Predictable VPS"]
  },
  {
    serviceCode: "firecracker",
    name: "AWS Firecracker",
    slug: "aws-firecracker",
    categorySlug: "compute",
    shortDescription: "Open-source virtualization technology for serverless containers.",
    fullDescription: "AWS Firecracker is an open-source virtualization technology that enables developers to build secure, multi-tenant container and serverless services, spawning microVMs in fractions of a second.",
    characteristics: ["Extremely low memory footprints", "MicroVM execution scaling", "Rust-based architecture platform"],
    features: ["Sub-5ms startup times", "Jailer isolation sandbox", "Host resource overcommit setups", "RESTful API config endpoints"],
    useCases: ["Running multi-tenant FaaS backends", "Secure single-tenant sandbox isolation", "MicroVM cluster compute layers"],
    pricingModels: ["Open-Source Engine (Underlies AWS Lambda / Fargate)"],
    relatedServices: [{ name: "AWS Lambda", slug: "aws-lambda" }, { name: "AWS Fargate", slug: "aws-fargate" }],
    keywords: ["microvm", "virtualization", "hypervisor", "rust", "lambda engine"],
    awsDocumentationUrl: "https://firecracker-microvm.github.io/",
    isFeatured: false,
    status: "GA",
    displayOrder: 130,
    comparisonTags: ["Virtualization", "Hypervisor", "Open Source Engine"]
  },
  {
    serviceCode: "nitrossystem",
    name: "AWS Nitro System",
    slug: "aws-nitro-system",
    categorySlug: "compute",
    shortDescription: "The underlying hardware layer powering next-gen EC2.",
    fullDescription: "The AWS Nitro System is the underlying platform for the modern generation of EC2 instances. It offloads virtualization functions to dedicated hardware cards for high performance and security.",
    characteristics: ["Hardware-based virtualization processing", "Zero-overhead execution virtualization", "Hardware cryptographic trust root"],
    features: ["Nitro Enclaves isolation zones", "Nitro Security Chips architecture", "Direct EBS local SSD controllers", "Nitro Hypervisor efficiency"],
    useCases: ["Running high performance database AMIs", "Confidential compute architectures", "Bare-metal high throughput applications"],
    pricingModels: ["Included in modern EC2 instances pricing"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["nitro", "hypervisor", "hardware offload", "enclaves", "virtualization"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances-nitro.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 140,
    comparisonTags: ["Hardware Infrastructure", "EC2 Core Platform"]
  },
  {
    serviceCode: "ec2autoscaling",
    name: "AWS Auto Scaling (EC2)",
    slug: "aws-auto-scaling-ec2",
    categorySlug: "compute",
    shortDescription: "Scale EC2 instance footprints automatically on policies.",
    fullDescription: "Amazon EC2 Auto Scaling helps you maintain application availability and allows you to automatically add or remove EC2 instances according to conditions you define.",
    characteristics: ["Dynamic traffic tracking response", "Health-check instance recycling", "Proactive scaling configurations"],
    features: ["Target tracking scaling policies", "Predictive scaling ML forecasts", "Multi-AZ instance rebalancing", "Launch template configurations"],
    useCases: ["Scaling web applications to traffic peaks", "Decommissioning idle compute during nights", "Self-healing failed instance clusters"],
    pricingModels: ["No extra charge (pay for running EC2 instances)"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Elastic Load Balancing", slug: "elastic-load-balancing" }],
    keywords: ["auto scaling", "scaling", "ec2 target", "group metrics"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html",
    isFeatured: true,
    status: "GA",
    displayOrder: 150,
    comparisonTags: ["Auto Scaling", "Availability Management"]
  },

  // CONTAINERS
  {
    serviceCode: "ecs",
    name: "Amazon ECS",
    slug: "amazon-ecs",
    categorySlug: "containers",
    shortDescription: "Highly secure, reliable, and scalable container management.",
    fullDescription: "Amazon Elastic Container Service (Amazon ECS) is a highly scalable, high-performance container orchestration service that supports Docker containers and allows you to run applications.",
    characteristics: ["Deep AWS native API integrations", "Simple container orchestration", "Zero orchestration plane billing"],
    features: ["Task Definitions templates", "Service load balancer attachments", "AWS VPC native networking", "ECS Exec direct shell"],
    useCases: ["Microservices architecture clusters", "Containerized API server deployments", "Asynchronous job worker fleets"],
    pricingModels: ["Fargate compute rates", "EC2 instance rates"],
    relatedServices: [{ name: "AWS Fargate", slug: "aws-fargate" }, { name: "Amazon ECR", slug: "amazon-ecr" }],
    keywords: ["containers", "docker", "ecs", "orchestration", "microservices"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/ecs/",
    isFeatured: true,
    status: "GA",
    displayOrder: 160,
    comparisonTags: ["Container Orchestration", "Docker Hosting"]
  },
  {
    serviceCode: "eks",
    name: "Amazon EKS",
    slug: "amazon-eks",
    categorySlug: "containers",
    shortDescription: "Managed Kubernetes service for standard clusters.",
    fullDescription: "Amazon Elastic Kubernetes Service (Amazon EKS) is a managed service that makes it easy for you to run Kubernetes on AWS without needing to stand up or maintain your own control plane.",
    characteristics: ["Upstream Kubernetes compatibility", "Managed control plane redundancy", "Robust community integrations"],
    features: ["Managed Node Groups lifecycle", "AWS IAM roles for service accounts (IRSA)", "VPC CNI container networking", "Cluster endpoints access"],
    useCases: ["Standardizing multi-cloud container ops", "Enterprise cloud-native migrations", "Complex microservices meshes"],
    pricingModels: ["Hourly Cluster Fee ($0.10/hour)", "Pay for compute nodes (EC2/Fargate)"],
    relatedServices: [{ name: "Amazon ECR", slug: "amazon-ecr" }, { name: "AWS Fargate", slug: "aws-fargate" }],
    keywords: ["kubernetes", "eks", "containers", "k8s", "control plane"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/eks/",
    isFeatured: true,
    status: "GA",
    displayOrder: 170,
    comparisonTags: ["Kubernetes", "Container Orchestration"]
  },
  {
    serviceCode: "ecr",
    name: "Amazon ECR",
    slug: "amazon-ecr",
    categorySlug: "containers",
    shortDescription: "Fully managed registry to store and deploy container images.",
    fullDescription: "Amazon Elastic Container Registry (Amazon ECR) is a fully managed container registry that makes it easy for developers to share and deploy container images and artifacts.",
    characteristics: ["Highly available secure registries", "IAM authorization scopes", "Fast local pull times for ECS/EKS"],
    features: ["Vulnerability image scanning", "Lifecycle cleanup policies", "Public gallery distribution", "Cross-region replication layers"],
    useCases: ["Storing private build pipelines Docker images", "Distributing public container application assets", "Hosting Helm charts catalog"],
    pricingModels: ["Data Storage per GB", "Internet Data Egress Transfer"],
    relatedServices: [{ name: "Amazon ECS", slug: "amazon-ecs" }, { name: "Amazon EKS", slug: "amazon-eks" }],
    keywords: ["registry", "images", "docker registry", "ecr", "artifacts"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/ecr/",
    isFeatured: false,
    status: "GA",
    displayOrder: 180,
    comparisonTags: ["Artifact Registry", "Docker Repository"]
  },
  {
    serviceCode: "fargate",
    name: "AWS Fargate",
    slug: "aws-fargate",
    categorySlug: "containers",
    shortDescription: "Serverless compute engine for container architectures.",
    fullDescription: "AWS Fargate is a serverless, pay-as-you-go compute engine that lets you focus on building applications without managing servers. It works directly with ECS and EKS.",
    characteristics: ["No container host OS management", "Elastic task-level isolation", "Sized exactly on CPU/Memory requests"],
    features: ["Task-level IAM credential profiles", "Ephemeral storage mount configurations", "VPC native ENI assignments", "Fargate Spot discounted compute"],
    useCases: ["API microservices without host patching", "Scheduled container batch tasks", "Scalable container application workloads"],
    pricingModels: ["Hourly CPU/Memory Allocation Rates"],
    relatedServices: [{ name: "Amazon ECS", slug: "amazon-ecs" }, { name: "Amazon EKS", slug: "amazon-eks" }],
    keywords: ["serverless", "containers", "fargate", "ecs fargate", "serverless containers"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonECS/latest/userguide/what-is-fargate.html",
    isFeatured: true,
    status: "GA",
    displayOrder: 190,
    comparisonTags: ["Serverless Containers", "CaaS"]
  },
  {
    serviceCode: "eksanywhere",
    name: "Amazon EKS Anywhere",
    slug: "amazon-eks-anywhere",
    categorySlug: "containers",
    shortDescription: "Run Kubernetes clusters on-premises with EKS consistency.",
    fullDescription: "Amazon EKS Anywhere is an deployment option for Amazon EKS that allows you to easily create and operate Kubernetes clusters on-premises, using consistent software configurations.",
    characteristics: ["Local physical datacenter execution", "EKS Console console visibility", "Consistent orchestration software tooling"],
    features: ["Bare metal and vSphere hypervisor support", "GitOps deployment controller sync", "Local control plane deployment tools", "Unified support channel"],
    useCases: ["Hybrid on-prem Kubernetes infrastructure", "Legacy data proximity applications", "Regulated data localization grids"],
    pricingModels: ["Free open source", "EKS Anywhere Subscription Support Package"],
    relatedServices: [{ name: "Amazon EKS", slug: "amazon-eks" }],
    keywords: ["hybrid", "kubernetes on-prem", "eks anywhere", "vsphere"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/eks/latest/userguide/eks-anywhere.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 200,
    comparisonTags: ["Hybrid Kubernetes", "On-Premises Orchestration"]
  },
  {
    serviceCode: "ecsanywhere",
    name: "Amazon ECS Anywhere",
    slug: "amazon-ecs-anywhere",
    categorySlug: "containers",
    shortDescription: "Orchestrate container tasks on customer-managed hardware.",
    fullDescription: "Amazon ECS Anywhere provides a fully managed container orchestration service that allows you to run and manage ECS tasks on your own customer-managed local servers and hardware.",
    characteristics: ["Hybrid hardware control", "Lightweight ECS systems agent", "Unified ECS control plane interface"],
    features: ["Systems Manager registration layer", "Local CPU/Memory execution stats", "IAM credentials dynamic bindings", "ECS console unified dashboards"],
    useCases: ["On-premises hardware data processing", "IoT edge hub microservices orchestration", "Migrating on-prem servers to ECS containerized tasks"],
    pricingModels: ["Per Active ECS Anywhere Registered Instance Hour"],
    relatedServices: [{ name: "Amazon ECS", slug: "amazon-ecs" }],
    keywords: ["ecs anywhere", "hybrid container", "on-prem servers", "agent"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 210,
    comparisonTags: ["Hybrid Containers", "On-Premises Orchestration"]
  },
  {
    serviceCode: "eksdistro",
    name: "Amazon EKS Distro",
    slug: "amazon-eks-distro",
    categorySlug: "containers",
    shortDescription: "Open-source Kubernetes distribution used by Amazon EKS.",
    fullDescription: "Amazon EKS Distro is a secure, open-source distribution of Kubernetes components (etcd, CoreDNS, upstream binaries) used by EKS, allowing manual installation on raw environments.",
    characteristics: ["Verified security patches", "Strict upstream conformance", "Open source packaging modules"],
    features: ["Latest stable Kubernetes version builds", "Automated compatibility test validation", "Hardened system components package", "GitHub source repositories"],
    useCases: ["Building custom K8s setups from source", "Standardizing internal private Kubernetes nodes", "Bare-metal infrastructure conformance"],
    pricingModels: ["Open-Source Free Distribution"],
    relatedServices: [{ name: "Amazon EKS", slug: "amazon-eks" }],
    keywords: ["distro", "open source k8s", "kubernetes distribution", "eks distro"],
    awsDocumentationUrl: "https://distro.eks.amazonaws.com/",
    isFeatured: false,
    status: "GA",
    displayOrder: 220,
    comparisonTags: ["Kubernetes Conformance", "Open Source Engine"]
  },
  {
    serviceCode: "copilot",
    name: "AWS Copilot CLI",
    slug: "aws-copilot-cli",
    categorySlug: "containers",
    shortDescription: "Deploy and manage containerized apps from CLI.",
    fullDescription: "AWS Copilot is an open-source command line interface (CLI) that simplifies deploying and managing production-ready containerized applications on ECS and AWS Fargate.",
    characteristics: ["Declarative application design", "CLI-driven developer productivity", "Automatic CloudFormation orchestration"],
    features: ["Copilot environment creation presets", "Service blueprint templates (load balanced / backend)", "Integrated logs and monitoring commands", "Multi-stage pipeline generation"],
    useCases: ["Fast CLI deployments for Docker projects", "Setting up production ECS clusters instantly", "Standardizing container deployments configurations"],
    pricingModels: ["Open-Source CLI Tool (Pay for deployed resources)"],
    relatedServices: [{ name: "Amazon ECS", slug: "amazon-ecs" }, { name: "AWS Fargate", slug: "aws-fargate" }],
    keywords: ["cli", "copilot", "deploy containers", "ecs builder"],
    awsDocumentationUrl: "https://aws.github.io/copilot-cli/",
    isFeatured: false,
    status: "GA",
    displayOrder: 230,
    comparisonTags: ["CLI Tool", "Application Delivery", "Container Deployment"]
  },

  // STORAGE
  {
    serviceCode: "s3",
    name: "Amazon S3",
    slug: "amazon-s3",
    categorySlug: "storage",
    shortDescription: "Scalable object storage for high availability data archiving.",
    fullDescription: "Amazon Simple Storage Service (Amazon S3) is an object storage service offering industry-leading scalability, data availability, security, and performance for databases, backups, and analytics.",
    characteristics: ["99.999999999% durability design", "Virtually unlimited space capacity", "Flexible storage tiers structure"],
    features: ["Lifecycle replication rules", "Object Versioning control", "S3 Storage Lens analytics", "Bucket access control lists (ACLs)"],
    useCases: ["SaaS assets and media storage", "Disaster recovery data backups", "Data lakes target repositories"],
    pricingModels: ["Data Storage per GB Monthly", "Request Operations (GET/PUT)", "Data Transfer Egress"],
    relatedServices: [{ name: "Amazon CloudFront", slug: "amazon-cloudfront" }, { name: "AWS KMS", slug: "aws-kms" }],
    keywords: ["storage", "s3 bucket", "object storage", "backup data", "cloud files"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/s3/",
    isFeatured: true,
    status: "GA",
    displayOrder: 240,
    comparisonTags: ["Object Storage", "Cloud Storage"]
  },
  {
    serviceCode: "ebs",
    name: "Amazon EBS",
    slug: "amazon-ebs",
    categorySlug: "storage",
    shortDescription: "High-performance block storage volumes for EC2 virtual servers.",
    fullDescription: "Amazon Elastic Block Store (Amazon EBS) provides high-performance, persistent block storage volumes for use with Amazon EC2 instances, supporting critical transaction application performance.",
    characteristics: ["Raw block storage access", "Dynamic capacity scaling", "AZ replication redundancy"],
    features: ["SSD-backed configurations (gp3, io2)", "EBS Snapshot volume backups", "Automatic KMS encryption", "Elastic volume expansion"],
    useCases: ["EC2 host boot volumes", "Relational database storage mount points", "Enterprise transactional server storage"],
    pricingModels: ["Provisioned Capacity per GB/Month", "Provisioned IOPS Monthly Rate"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "AWS Backup", slug: "aws-backup" }],
    keywords: ["hard drive", "block storage", "ebs volume", "ec2 drive", "persistent"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/ebs/",
    isFeatured: true,
    status: "GA",
    displayOrder: 250,
    comparisonTags: ["Block Storage", "VM Virtual Disks"]
  },
  {
    serviceCode: "efs",
    name: "Amazon EFS",
    slug: "amazon-efs",
    categorySlug: "storage",
    shortDescription: "Serverless elastic file storage for simultaneous EC2 mounts.",
    fullDescription: "Amazon Elastic File System (Amazon EFS) provides a simple, serverless, set-and-forget elastic file system for use with AWS Cloud services and on-premises resources, supporting standard NFS protocols.",
    characteristics: ["Elastic self-scaling storage", "Simultaneous multi-instance mounts", "POSIX-compliant directory structures"],
    features: ["NFSv4 network share mounting", "EFS Lifecycle Management rules", "Provisioned throughput overrides", "Multi-AZ mount target subnets"],
    useCases: ["Content management assets shares (WordPress)", "Enterprise shared application data volumes", "Shared developer workspace folders"],
    pricingModels: ["Capacity Storage per GB Monthly", "Data Access Read/Write Operations"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "AWS Fargate", slug: "aws-fargate" }],
    keywords: ["network share", "nfs", "efs", "shared files", "elastic storage"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/efs/",
    isFeatured: false,
    status: "GA",
    displayOrder: 260,
    comparisonTags: ["File Storage", "Network File Share", "NAS"]
  },
  {
    serviceCode: "glacier",
    name: "Amazon S3 Glacier",
    slug: "amazon-s3-glacier",
    categorySlug: "storage",
    shortDescription: "Low-cost archival data vaults with flexible retrieval models.",
    fullDescription: "Amazon S3 Glacier is a secure, durable, and extremely low-cost cloud storage class for data archiving and long-term backup. It provides retrieval options from minutes to hours.",
    characteristics: ["Extreme long-term cost optimization", "99.999999999% data durability", "Configurable retrieval timelines"],
    features: ["S3 Glacier Deep Archive storage", "Glacier Vault Lock audit control", "Data query-in-place (S3 Select)", "Lifecycle transition integration"],
    useCases: ["Regulatory compliance ledger logging archives", "Deep disaster recovery data reserves", "Legacy backup tape replacement"],
    pricingModels: ["Archival Storage GB/Month (Very Low)", "Data Retrieval Fees", "Rapid Access Options"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["glacier", "archive", "cold storage", "tape backup", "long term storage"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/glacier/",
    isFeatured: false,
    status: "GA",
    displayOrder: 270,
    comparisonTags: ["Archival Storage", "Cold Storage"]
  },
  {
    serviceCode: "storagegateway",
    name: "AWS Storage Gateway",
    slug: "aws-storage-gateway",
    categorySlug: "storage",
    shortDescription: "Hybrid storage bridges connecting local setups to S3 cloud files.",
    fullDescription: "AWS Storage Gateway is a hybrid cloud storage service that gives you on-premises access to virtually unlimited cloud storage. It provides file, volume, and virtual tape gateways.",
    characteristics: ["Hybrid network integration", "Local caching endpoints", "Standard file protocol compatibility"],
    features: ["File Gateway (NFS/SMB caching)", "Volume Gateway (iSCSI virtualization)", "Tape Gateway (VTL cloud backup)", "AWS Backup centralized schedule"],
    useCases: ["Local workstation cloud backups", "Low-latency hybrid application shares", "Replacing local tape backups to Glacier"],
    pricingModels: ["Virtual Appliance Active Hours", "Data Storage consumed in S3"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon S3 Glacier", slug: "amazon-s3-glacier" }],
    keywords: ["hybrid storage", "gateway", "nfs local", "iscsi", "cached drive"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/storagegateway/",
    isFeatured: false,
    status: "GA",
    displayOrder: 280,
    comparisonTags: ["Hybrid Cloud Storage", "On-Premises Gateway"]
  },
  {
    serviceCode: "backup",
    name: "AWS Backup",
    slug: "aws-backup",
    categorySlug: "storage",
    shortDescription: "Centralized managed backup automation across AWS services.",
    fullDescription: "AWS Backup is a fully managed backup service that makes it easy to centralize and automate the back up of data across AWS services in the cloud as well as on-premises.",
    characteristics: ["Central policy-based schedules", "Unified multi-service dashboard", "Compliance auditing logs"],
    features: ["Continuous backup points", "Cross-region vault replications", "WORM compliance lock (Backup Lock)", "Restoration test pipelines"],
    useCases: ["Daily EC2/RDS snapshot automations", "Compliance backup preservation audits", "Cross-region disaster recovery replication"],
    pricingModels: ["Backup Data Storage GB/Month", "Data Restoration per GB Transfer"],
    relatedServices: [{ name: "Amazon EBS", slug: "amazon-ebs" }, { name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["backup", "snapshots", "restore", "disaster recovery", "backup plan"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 290,
    comparisonTags: ["Backup Management", "Data Protection"]
  },
  {
    serviceCode: "snowball",
    name: "AWS Snowball",
    slug: "aws-snowball",
    categorySlug: "storage",
    shortDescription: "Ruggedized petabyte-scale data migration edge computing devices.",
    fullDescription: "AWS Snowball is a service that utilizes physical data migration devices to transfer large amounts of data between the local infrastructure and the AWS cloud offline.",
    characteristics: ["Rugged physical shipping boxes", "Offline secure data transit", "Local computing processing"],
    features: ["Snowball Edge Storage Optimized (80TB)", "Snowball Edge Compute Optimized (sizable cores)", "NFC/AES hardware data encryption", "VPC routing and EC2 capability"],
    useCases: ["Offline petabyte-scale cloud data transfers", "Temporary field compute data stations", "Maritime and research ship data storage"],
    pricingModels: ["Device Rental Fee Per Job Duration", "Shipping and Logistics Fees"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["snowball", "data migration", "offline transfer", "import data", "rugged computer"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/snowball/",
    isFeatured: false,
    status: "GA",
    displayOrder: 300,
    comparisonTags: ["Data Migration Hardware", "Edge Compute"]
  },
  {
    serviceCode: "snowcone",
    name: "AWS Snowcone",
    slug: "aws-snowcone",
    categorySlug: "storage",
    shortDescription: "Ultra-portable light data transfer and computing device.",
    fullDescription: "AWS Snowcone is the smallest member of the AWS Snow Family of edge computing, edge storage, and data transfer devices, weighing only 4.5 lbs for portable deployments.",
    characteristics: ["Ultra-portable small form-factor", "Low power requirements", "Rugged shockproof build"],
    features: ["8TB local storage capability", "USB/Ethernet connectivity", "E-Ink shipping label display", "AWS IoT Greengrass compatibility"],
    useCases: ["Tactical military data gathering", "Mobile vehicle sensor collection stations", "Offline field data office backup syncs"],
    pricingModels: ["Snowcone Device Rental Fee", "Shipping Logistics Charges"],
    relatedServices: [{ name: "AWS Snowball", slug: "aws-snowball" }],
    keywords: ["snowcone", "portable storage", "edge collect", "small device"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/snowball/latest/developer-guide/snowcone.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 310,
    comparisonTags: ["Data Migration Hardware", "Edge Compute"]
  },
  {
    serviceCode: "snowmobile",
    name: "AWS Snowmobile",
    slug: "aws-snowmobile",
    categorySlug: "storage",
    shortDescription: "Exabyte-scale shipping container data transport system.",
    fullDescription: "AWS Snowmobile is an exabyte-scale data transfer service used to move massive volumes of data to AWS, deploying a 45-foot ruggedized shipping container pulled by a semi-trailer truck.",
    characteristics: ["Massive semi-trailer container", "Dedicated operations team escort", "High physical network bandwidth"],
    features: ["100 Petabyte storage capacity", "Physical security protection units", "Liquid-cooling climate controls", "Dedicated fiber-optic cable reels"],
    useCases: ["Exabyte-scale enterprise datacenter migrations", "National research archives cloud loading", "Government database partition movements"],
    pricingModels: ["Custom Contract Service Pricing"],
    relatedServices: [{ name: "AWS Snowball", slug: "aws-snowball" }],
    keywords: ["snowmobile", "truck data", "exabyte migration", "shipping container"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/snowball/latest/ug/whatissnowmobile.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 320,
    comparisonTags: ["Data Migration Hardware"]
  },
  {
    serviceCode: "elasticdisasterrecovery",
    name: "AWS Elastic Disaster Recovery",
    slug: "aws-elastic-disaster-recovery",
    categorySlug: "storage",
    shortDescription: "Minimize data loss with reliable cloud-based recovery.",
    fullDescription: "AWS Elastic Disaster Recovery (AWS DRS) minimizes downtime and data loss with fast, reliable recovery of physical, virtual, and cloud-based servers into the AWS Cloud.",
    characteristics: ["Continuous asynchronous data replication", "Automated drill tests", "Highly optimized recovery checkpoints"],
    features: ["Lightweight source server agents", "Continuous replication target subnets", "One-click failover operations", "Automatic KMS encrypt protection"],
    useCases: ["Datacenter failure disaster recovery protection", "Active multi-cloud backup failovers", "Business continuity infrastructure compliance"],
    pricingModels: ["Per Replicating Source Server Hourly Fee"],
    relatedServices: [{ name: "AWS Backup", slug: "aws-backup" }, { name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["disaster recovery", "drs", "failover", "replication", "backup sync"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/drs/latest/userguide/what-is-drs.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 330,
    comparisonTags: ["Disaster Recovery", "Business Continuity"]
  },
  {
    serviceCode: "s3outposts",
    name: "Amazon S3 on Outposts",
    slug: "amazon-s3-on-outposts",
    categorySlug: "storage",
    shortDescription: "Deploy S3 object storage directly on-premises.",
    fullDescription: "Amazon S3 on Outposts delivers object storage capabilities on your physical AWS Outposts rack, meeting local data residency and low latency storage demands.",
    characteristics: ["On-premise object storage caching", "Consistent AWS API protocols", "Secure hardware containment"],
    features: ["Local S3 bucket endpoints", "Outposts management layers integration", "Automatic data encryption", "VPC Local Gateway link access"],
    useCases: ["High-speed local video editing caches", "Regulated localized database backups", "Outposts microservices local storage access"],
    pricingModels: ["Included in AWS Outposts hardware subscription rates"],
    relatedServices: [{ name: "AWS Outposts", slug: "aws-outposts" }, { name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["s3 outposts", "local s3", "hybrid object storage", "outpost rack"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/S3onOutposts.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 340,
    comparisonTags: ["Object Storage", "Hybrid Cloud Storage", "On-Premises Hardware"]
  },
  {
    serviceCode: "filecache",
    name: "Amazon File Cache",
    slug: "amazon-file-cache",
    categorySlug: "storage",
    shortDescription: "High-speed cache for data stored on-prem and on S3.",
    fullDescription: "Amazon File Cache is a fully managed, high-speed cache on AWS for data stored anywhere (including on-premises files or S3 buckets), supporting standard Lustre file APIs.",
    characteristics: ["Sub-millisecond data caching speeds", "Aggregated unified namespace", "Managed Lustre cache engine"],
    features: ["High throughput cache pools", "Automatic background storage syncs", "NFS/SMB source gateways mounts", "Integrated IAM security policies"],
    useCases: ["High performance hybrid analytics pipelines", "Distributed computational jobs inputs caching", "Cloud processing of local datacenter assets"],
    pricingModels: ["Provisioned Cache Capacity per GB/Hour"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["file cache", "caching", "lustre cache", "hybrid cache", "data cache"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/fsx/latest/FileCacheGuide/what-is.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 350,
    comparisonTags: ["High Performance Storage", "Cache Gateway"]
  },
  {
    serviceCode: "backupgateway",
    name: "AWS Backup Gateway",
    slug: "aws-backup-gateway",
    categorySlug: "storage",
    shortDescription: "Connect on-premises hypervisor storage to AWS Backup.",
    fullDescription: "AWS Backup Gateway provides a backup software appliance that installs in your local VMware environment to replicate VMs directly into AWS Backup vaults.",
    characteristics: ["Hybrid backup bridge", "VMware Hypervisor compatibility", "Central AWS dashboard controls"],
    features: ["VMware CBT (Changed Block Tracking) tracking", "Encrypted gateway network transit", "Automatic VM restoration pipelines", "Storage volume scheduling"],
    useCases: ["VMware VM backups storage consolidation", "Corporate hybrid datacenter recovery blueprints", "Off-site backup compliance auditing"],
    pricingModels: ["Gateway Appliance hours", "Pay for Vault storage used"],
    relatedServices: [{ name: "AWS Backup", slug: "aws-backup" }],
    keywords: ["backup gateway", "vmware backup", "hypervisor backup", "vm backup"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/aws-backup/latest/devguide/what-is-backup-gateway.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 360,
    comparisonTags: ["Backup Management", "On-Premises Gateway"]
  },

  // DATABASE
  {
    serviceCode: "rds",
    name: "Amazon RDS",
    slug: "amazon-rds",
    categorySlug: "database",
    shortDescription: "Managed relational database engine for SQL platforms.",
    fullDescription: "Amazon Relational Database Service (Amazon RDS) makes it easy to set up, operate, and scale a relational database in the cloud, supporting PostgreSQL, MySQL, MariaDB, SQL Server, and Oracle.",
    characteristics: ["Automated patching updates", "Multi-AZ high availability mirroring", "Familiar SQL database engines compatibility"],
    features: ["Automated daily DB backups", "Read Replica scaling nodes", "KMS database encryption", "Storage auto-scaling layers"],
    useCases: ["Enterprise ERP/CRM application storage", "Web app transactional SQL databases", "Standard database backup migrations"],
    pricingModels: ["DB Instance Hourly rate", "Provisioned storage GB/Month", "I/O Rates (Engine Dependent)"],
    relatedServices: [{ name: "Amazon Aurora", slug: "amazon-aurora" }, { name: "AWS KMS", slug: "aws-kms" }],
    keywords: ["database", "sql", "postgresql", "mysql", "rds", "relational"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/rds/",
    isFeatured: true,
    status: "GA",
    displayOrder: 370,
    comparisonTags: ["Relational Database", "SQL Database", "PaaS Database"]
  },
  {
    serviceCode: "aurora",
    name: "Amazon Aurora",
    slug: "amazon-aurora",
    categorySlug: "database",
    shortDescription: "High-performance Postgres and MySQL compatible database.",
    fullDescription: "Amazon Aurora is a modern relational database engine built for the cloud. It features compatibility with Postgres and MySQL, offering high throughput and automated storage replication.",
    characteristics: ["Cloud-native storage virtualization", "Up to 5x throughput of standard MySQL", "Global cross-region replication databases"],
    features: ["Aurora Serverless v2 dynamic scaling", "6-way Multi-AZ storage mirroring", "Sub-10ms database replicas", "Fast database recovery engines"],
    useCases: ["High-throughput e-commerce transactional database", "SaaS multi-tenant database clusters", "Global scale application databases"],
    pricingModels: ["Aurora Capacity Unit (ACU) Hour", "Storage consumed GB/Month", "Request I/O Operations count"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["aurora", "mysql", "postgresql", "cloud native database", "serverless database"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html",
    isFeatured: true,
    status: "GA",
    displayOrder: 380,
    comparisonTags: ["Relational Database", "SQL Database", "Cloud-Native Database"]
  },
  {
    serviceCode: "dynamodb",
    name: "Amazon DynamoDB",
    slug: "amazon-dynamodb",
    categorySlug: "database",
    shortDescription: "Serverless NoSQL database with single-digit millisecond performance.",
    fullDescription: "Amazon DynamoDB is a fully managed, serverless NoSQL key-value and document database designed to deliver single-digit millisecond latency at any scale.",
    characteristics: ["Serverless automatic throughput scaling", "Consistent single-digit millisecond responses", "Structured document/key-value storage"],
    features: ["DynamoDB Streams change tracking", "Global Tables active-active cross-region", "On-Demand scale configuration", "Point-in-Time recovery backups"],
    useCases: ["High-traffic shopping cart session stores", "Real-time gaming player leaderboard scoreboards", "IoT high-volume metadata ingestion tables"],
    pricingModels: ["On-Demand Capacity request billing", "Provisioned Read/Write Capacity (RCU/WCU)", "Storage consumed per GB/Month"],
    relatedServices: [{ name: "AWS Lambda", slug: "aws-lambda" }, { name: "Amazon Kinesis", slug: "amazon-kinesis" }],
    keywords: ["nosql", "dynamodb", "key-value", "document database", "serverless db"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/dynamodb/",
    isFeatured: true,
    status: "GA",
    displayOrder: 390,
    comparisonTags: ["NoSQL Database", "Key-Value Database", "Serverless Database"]
  },
  {
    serviceCode: "elasticache",
    name: "Amazon ElastiCache",
    slug: "amazon-elasticache",
    categorySlug: "database",
    shortDescription: "Managed in-memory Redis and Memcached caching clusters.",
    fullDescription: "Amazon ElastiCache is a fully managed in-memory data store and cache service, supporting Redis and Memcached engines to accelerate application database access layers.",
    characteristics: ["Sub-millisecond data retrieval times", "High concurrency load buffer", "Managed cluster replication setups"],
    features: ["Redis cluster mode support", "Multi-AZ replication failovers", "Auto Discovery client endpoints", "Seamless RDS connection caching bindings"],
    useCases: ["SQL Query cache layers", "Real-time session token management", "High-frequency pub/sub data hubs"],
    pricingModels: ["Cache Node Instance Hourly rate"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }, { name: "Amazon DynamoDB", slug: "amazon-dynamodb" }],
    keywords: ["cache", "redis", "memcached", "in-memory database", "speed cache"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/elasticache/",
    isFeatured: false,
    status: "GA",
    displayOrder: 400,
    comparisonTags: ["In-Memory Database", "Caching Engine"]
  },
  {
    serviceCode: "neptune",
    name: "Amazon Neptune",
    slug: "amazon-neptune",
    categorySlug: "database",
    shortDescription: "Fast, reliable graph database engine built for the cloud.",
    fullDescription: "Amazon Neptune is a fast, reliable, fully managed graph database service that makes it easy to build and run applications that work with highly connected datasets.",
    characteristics: ["Optimized graph traversal query engines", "Supports Gremlin and SPARQL frameworks", "Multi-AZ database high availability"],
    features: ["Neptune Serverless dynamic scaling", "Graph visualization integrations", "Read replica scale nodes", "KMS-backed cluster encryption"],
    useCases: ["Social media network relationship graph mappings", "Identity fraud detection dependency traces", "Recommendation engine connected logic paths"],
    pricingModels: ["Neptune Instance Hourly rate", "Storage consumed GB/Month", "I/O request cycles count"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["graph", "neptune", "connected data", "gremlin", "sparql"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/neptune/",
    isFeatured: false,
    status: "GA",
    displayOrder: 410,
    comparisonTags: ["Graph Database", "NoSQL Database"]
  },
  {
    serviceCode: "documentdb",
    name: "Amazon DocumentDB",
    slug: "amazon-documentdb",
    categorySlug: "database",
    shortDescription: "MongoDB-compatible managed JSON document database.",
    fullDescription: "Amazon DocumentDB (with MongoDB compatibility) is a fast, scalable, highly available, and fully managed enterprise document database service for scale JSON workloads.",
    characteristics: ["MongoDB API compatibility", "Decoupled storage and compute layers", "Automatic storage auto-scaling pools"],
    features: ["JSON query expression parser support", "Automated cluster failovers", "Encrypted document data vaults", "Read replicas scaling instances"],
    useCases: ["JSON profile data archives", "E-commerce catalogs document storage", "Content management systems database structures"],
    pricingModels: ["Compute Instance Hourly rate", "Storage consumed GB/Month", "I/O request billing blocks"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["mongodb", "json", "document db", "nosql json", "documentdb"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/documentdb/",
    isFeatured: false,
    status: "GA",
    displayOrder: 420,
    comparisonTags: ["NoSQL Database", "Document Database"]
  },
  {
    serviceCode: "keyspaces",
    name: "Amazon Keyspaces",
    slug: "amazon-keyspaces",
    categorySlug: "database",
    shortDescription: "Apache Cassandra compatible serverless database.",
    fullDescription: "Amazon Keyspaces (for Apache Cassandra) is a scalable, highly available, and managed Apache Cassandra-compatible database service that is fully serverless.",
    characteristics: ["Cassandra CQL syntax compatibility", "Fully serverless capacity autoscaling", "Consistent single-digit millisecond writes"],
    features: ["On-demand scaling configurations", "Point-in-time recovery checkpoints", "Automatic encryption by default", "AWS CLI table creation tools"],
    useCases: ["Migrating local Cassandra databases to cloud", "High-frequency telemetry logging pipelines", "Scalable application state tables"],
    pricingModels: ["On-Demand Capacity request blocks", "Provisioned capacity rates", "Storage consumed per GB/Month"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["cassandra", "cql", "keyspaces", "columnar database", "nosql cassandra"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/keyspaces/",
    isFeatured: false,
    status: "GA",
    displayOrder: 430,
    comparisonTags: ["NoSQL Database", "Columnar Database", "Serverless Database"]
  },
  {
    serviceCode: "timestream",
    name: "Amazon Timestream",
    slug: "amazon-timestream",
    categorySlug: "database",
    shortDescription: "Managed time-series database for IoT and telemetry.",
    fullDescription: "Amazon Timestream is a fast, scalable, and serverless time-series database service for IoT and operational applications that makes it easy to store and analyze trillions of events daily.",
    characteristics: ["Optimized time-series database indexing", "Fully serverless resource provisioning", "Decoupled storage lifecycle tiers"],
    features: ["Built-in time-series SQL functions", "Automated data lifecycle cleanups", "Integrated analytics dashboards sync", "High write performance ingestion scales"],
    useCases: ["IoT sensor telemetry logging databases", "Application performance metric trackers", "E-commerce user-activity clicks archives"],
    pricingModels: ["Data Ingestion per GB", "Query Execution Scanned Bytes", "Storage consumed per Tier (Memory/Magnetic)"],
    relatedServices: [{ name: "AWS IoT Core", slug: "aws-iot-core" }, { name: "Amazon QuickSight", slug: "amazon-quicksight" }],
    keywords: ["time series", "timestream", "iot db", "metrics logging", "sensor data"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/timestream/",
    isFeatured: false,
    status: "GA",
    displayOrder: 440,
    comparisonTags: ["Time-Series Database", "NoSQL Database", "Serverless Database"]
  },
  {
    serviceCode: "memorydb",
    name: "MemoryDB for Redis",
    slug: "amazon-memorydb-for-redis",
    categorySlug: "database",
    shortDescription: "Redis-compatible database with transactional log durability.",
    fullDescription: "Amazon MemoryDB for Redis is a Redis-compatible, durable, in-memory database service that delivers ultra-fast performance and microsecond read latencies.",
    characteristics: ["Microsecond database read responses", "Multi-AZ transactional log durability", "Fully Redis API compatibility"],
    features: ["Multi-AZ cluster clustering options", "Durable write-ahead journal log", "Redis client libraries support", "IAM database role permissions"],
    useCases: ["Primary database requiring fast latency", "High-frequency financial transactional ledgers", "Real-time gaming persistent inventories"],
    pricingModels: ["MemoryDB Instance Hourly rate", "Data Written per GB to durability logs"],
    relatedServices: [{ name: "Amazon ElastiCache", slug: "amazon-elasticache" }],
    keywords: ["memorydb", "redis durable", "in-memory db", "fast database", "redis transaction"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/memorydb/",
    isFeatured: false,
    status: "GA",
    displayOrder: 450,
    comparisonTags: ["In-Memory Database", "NoSQL Database", "Durable Cache"]
  },
  {
    serviceCode: "rdscustom",
    name: "Amazon RDS Custom",
    slug: "amazon-rds-custom",
    categorySlug: "database",
    shortDescription: "Managed database with underlying host OS customization rights.",
    fullDescription: "Amazon RDS Custom is a managed database service that automates database setup and patching, while granting users access to the underlying OS and database configuration.",
    characteristics: ["Managed database administration automation", "OS root access permissions", "Custom database application support"],
    features: ["Automated backups and updates control", "Support for custom Oracle/SQL Server setups", "Host OS virtualization access", "KMS disk encrypt integration"],
    useCases: ["Legacy enterprise applications requiring OS plugins", "Databases requiring custom third-party SQL scripts", "Highly customized corporate databases installations"],
    pricingModels: ["RDS Custom Instance Hourly rate", "Provisioned storage parameters"],
    relatedServices: [{ name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["rds custom", "root access", "oracle custom", "sql server custom"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-custom.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 460,
    comparisonTags: ["Relational Database", "PaaS Database", "Hybrid Management"]
  },
  {
    serviceCode: "simpledb",
    name: "Amazon SimpleDB",
    slug: "amazon-simpledb",
    categorySlug: "database",
    shortDescription: "Simple, highly available NoSQL data lookup store.",
    fullDescription: "Amazon SimpleDB is a highly available and flexible NoSQL database store that offloads database administration. It is a legacy service for small, simple lookup datasets.",
    characteristics: ["Highly available metadata stores", "Simple data lookup logic", "Legacy lightweight footprint"],
    features: ["Automatic index compilation", "Simple API requests (PutAttributes/GetAttributes)", "No-schema item attributes", "IAM connection policies"],
    useCases: ["Legacy system simple lookup tables", "Lightweight metadata indexing registers", "Configuration parameter databases"],
    pricingModels: ["SimpleDB Machine Hours", "Storage consumed GB/Month"],
    relatedServices: [{ name: "Amazon DynamoDB", slug: "amazon-dynamodb" }],
    keywords: ["simpledb", "nosql simple", "legacy db", "attribute lookup"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/simpledb/",
    isFeatured: false,
    status: "GA",
    displayOrder: 470,
    comparisonTags: ["NoSQL Database", "Key-Value Database", "Legacy Database"]
  },
  {
    serviceCode: "dax",
    name: "Amazon DynamoDB Accelerator (DAX)",
    slug: "amazon-dynamodb-accelerator-dax",
    categorySlug: "database",
    shortDescription: "In-memory caching cache layer for Amazon DynamoDB.",
    fullDescription: "Amazon DynamoDB Accelerator (DAX) is a fully managed, highly available, in-memory cache for Amazon DynamoDB that delivers up to a 10x performance improvement.",
    characteristics: ["Microsecond DynamoDB read latencies", "Transparent cache operations", "Managed caching cluster logic"],
    features: ["DynamoDB API client compatibility", "Automatic write-through cache logic", "Multi-AZ clustering protection", "KMS cluster encryption"],
    useCases: ["High-speed caching for gaming scoreboards", "High-volume read query session buffers", "Reducing DynamoDB read cost under spikes"],
    pricingModels: ["DAX Node Instance Hourly rate"],
    relatedServices: [{ name: "Amazon DynamoDB", slug: "amazon-dynamodb" }],
    keywords: ["dax", "dynamodb cache", "caching", "in-memory cache", "accelerator"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 480,
    comparisonTags: ["Caching Engine", "Database Accelerator"]
  },

  // NETWORKING
  {
    serviceCode: "vpc",
    name: "Amazon VPC",
    slug: "amazon-vpc",
    categorySlug: "networking",
    shortDescription: "Isolated cloud resources virtual networks manager.",
    fullDescription: "Amazon Virtual Private Cloud (Amazon VPC) lets you provision a logically isolated section of the AWS Cloud where you can launch AWS resources in a virtual network you define.",
    characteristics: ["Private network isolation control", "Configurable network subnets IP routing", "Secure VPC network gateways config"],
    features: ["Subnet IP allocations (Private/Public)", "Network Access Control Lists (NACLs)", "Security Groups stateful firewall rules", "VPC Flow Logs traffic auditing"],
    useCases: ["Isolating application backend servers", "Connecting corporate office networks to cloud", "Structuring multi-tier database subnets"],
    pricingModels: ["Free (pay for Nat Gateways / IP assignments / Flow Logs)"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "AWS Transit Gateway", slug: "aws-transit-gateway" }],
    keywords: ["network", "vpc", "subnets", "routing", "private cloud", "isolated"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpc/",
    isFeatured: true,
    status: "GA",
    displayOrder: 490,
    comparisonTags: ["Virtual Private Network", "Cloud Routing"]
  },
  {
    serviceCode: "cloudfront",
    name: "Amazon CloudFront",
    slug: "amazon-cloudfront",
    categorySlug: "networking",
    shortDescription: "Global content delivery network (CDN) for low-latency assets.",
    fullDescription: "Amazon CloudFront is a web service that speeds up distribution of your static and dynamic web content, such as .html, .css, .js, and image files, to users via edge locations.",
    characteristics: ["Global low latency file caching", "Integrated edge security protections", "High-speed network endpoints"],
    features: ["Edge cache control headers", "CloudFront Functions serverless edge code", "Geo-restriction user blockers", "Origin Shield centralized cache"],
    useCases: ["Fast static website assets delivery", "Global streaming video files caching", "Edge API gateway routing speedups"],
    pricingModels: ["Data Transfer Out Egress", "HTTP Request Operations count", "Origin Shield fees"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "AWS WAF", slug: "aws-waf" }],
    keywords: ["cdn", "cloudfront", "cache", "edge locations", "website delivery"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cloudfront/",
    isFeatured: true,
    status: "GA",
    displayOrder: 500,
    comparisonTags: ["Content Delivery Network", "Edge Cache"]
  },
  {
    serviceCode: "route53",
    name: "Amazon Route 53",
    slug: "amazon-route-53",
    categorySlug: "networking",
    shortDescription: "Scalable Domain Name System (DNS) and domain registry.",
    fullDescription: "Amazon Route 53 is a highly available and scalable cloud Domain Name System (DNS) web service. It is designed to give developers a reliable way to route end users.",
    characteristics: ["Global DNS resolution speeds", "Dynamic routing failovers", "Domain name registration registers"],
    features: ["DNS Health Checks monitors", "Weighted/Latency/Geo routing rules", "Route 53 Resolver local VPC links", "Private DNS Hosted Zones"],
    useCases: ["Mapping public domain names to load balancers", "Cross-region application failover automation", "Configuring internal database private domains"],
    pricingModels: ["Hosted Zone Monthly Charge", "DNS Queries volume (per million)"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["dns", "route53", "domain name", "routing policy", "nameserver"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/route53/",
    isFeatured: true,
    status: "GA",
    displayOrder: 510,
    comparisonTags: ["DNS Service", "Domain Management"]
  },
  {
    serviceCode: "directconnect",
    name: "AWS Direct Connect",
    slug: "aws-direct-connect",
    categorySlug: "networking",
    shortDescription: "Dedicated private fiber network link connecting on-prem to AWS.",
    fullDescription: "AWS Direct Connect bypasses the internet to deliver a private, dedicated physical fiber network connection from your datacenter or office directly to AWS infrastructure.",
    characteristics: ["Dedicated physical fiber cabling link", "Consistent bandwidth pipeline volumes", "Internet routing bypass security"],
    features: ["1Gbps / 10Gbps / 100Gbps connections configurations", "Direct Connect Gateway multi-VPC hubs", "Transit Virtual Interfaces (VIFs) support", "Link Aggregation Group (LAG) backups"],
    useCases: ["Massive database replication file transfers", "Consistent low-latency hybrid cloud connections", "Secure private banking transaction routing"],
    pricingModels: ["Port Hour Connection Fee", "Data Transfer Out (Direct Connect Reduced Egress Rate)"],
    relatedServices: [{ name: "AWS Transit Gateway", slug: "aws-transit-gateway" }],
    keywords: ["direct connect", "private link", "dedicated line", "fiber link", "hybrid network"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/directconnect/",
    isFeatured: false,
    status: "GA",
    displayOrder: 520,
    comparisonTags: ["Dedicated Connection", "Hybrid Network Connectivity"]
  },
  {
    serviceCode: "transitgateway",
    name: "AWS Transit Gateway",
    slug: "aws-transit-gateway",
    categorySlug: "networking",
    shortDescription: "Central cloud router connecting VPCs and local networks.",
    fullDescription: "AWS Transit Gateway acts as a cloud router, connecting virtual private clouds (VPCs) and on-premises networks through a single central gateway attachment hub.",
    characteristics: ["Hub-and-spoke routing architecture", "Eliminates complex mesh peering grids", "Central network policy administration"],
    features: ["Transit Gateway Route Tables controls", "Cross-account share attachments (RAM)", "Direct Connect integration support", "Inter-region gateway peering links"],
    useCases: ["Centralizing routing for hundreds of VPC accounts", "Directing corporate office traffic to cloud VPCs", "Setting up centralized security inspect subnets"],
    pricingModels: ["Per Transit Gateway Attachment Hourly", "Data processed per GB Volume"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }, { name: "AWS Resource Access Manager", slug: "aws-resource-access-manager" }],
    keywords: ["transit gateway", "router", "vpc peering", "hub and spoke", "network hub"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 530,
    comparisonTags: ["Cloud Router", "Network Hub"]
  },
  {
    serviceCode: "privatelink",
    name: "AWS PrivateLink",
    slug: "aws-private-link",
    categorySlug: "networking",
    shortDescription: "Securely access hosted services inside private VPC networks.",
    fullDescription: "AWS PrivateLink provides secure connectivity between VPCs, AWS services, and on-premises applications, keeping network traffic strictly inside the private AWS fiber network.",
    characteristics: ["Internal private network IP endpoints", "No internet route requirements", "Protection against data exfiltration"],
    features: ["VPC Endpoint Services creation", "Elastic Network Interface (ENI) endpoints mapping", "Private DNS name integrations", "IAM endpoint policies validations"],
    useCases: ["Accessing S3 privately without Internet Gateways", "Sharing internal microservices safely across accounts", "Securely connecting partner SaaS solutions"],
    pricingModels: ["VPC Endpoint Hourly connection rate", "Data processed per GB Volume"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["privatelink", "endpoint", "vpc endpoint", "private connection", "safe link"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpc/latest/privatelink/",
    isFeatured: false,
    status: "GA",
    displayOrder: 540,
    comparisonTags: ["Private Connection", "Endpoint Access"]
  },
  {
    serviceCode: "vpn",
    name: "AWS Site-to-Site VPN",
    slug: "aws-site-to-site-vpn",
    categorySlug: "networking",
    shortDescription: "Encrypted IPsec tunnels connecting local offices to VPCs.",
    fullDescription: "AWS Site-to-Site VPN creates secure, encrypted IPsec network tunnels connecting your on-premises datacenter or office networks directly to your AWS Virtual Private Cloud.",
    characteristics: ["IPsec encrypted tunnels", "Fast software-defined configuration", "Public internet transport layers"],
    features: ["Dual-tunnel redundancy configurations", "Customer Gateway (CGW) device mappings", "Virtual Private Gateway (VGW) endpoints", "BGP dynamic routing support"],
    useCases: ["Connecting office servers to cloud subnets", "Backup connection tunnel for Direct Connect links", "Low-cost hybrid network setups for testing"],
    pricingModels: ["Hourly VPN Connection rate", "Standard Internet Egress rates"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["vpn", "ipsec", "encrypted tunnel", "site to site", "office connection"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpn/latest/s2svpn/",
    isFeatured: false,
    status: "GA",
    displayOrder: 550,
    comparisonTags: ["Virtual Private Network", "Hybrid Connection"]
  },
  {
    serviceCode: "clientvpn",
    name: "AWS Client VPN",
    slug: "aws-client-vpn",
    categorySlug: "networking",
    shortDescription: "Managed OpenVPN client service for remote workers.",
    fullDescription: "AWS Client VPN is a fully managed, software-based VPN service that allows remote users to securely access AWS resources and on-premises networks using OpenVPN clients.",
    characteristics: ["User-level network tunnel connections", "Supports standard OpenVPN client profiles", "Elastic autoscaling user concurrency"],
    features: ["Active Directory/IAM SSO authorization", "VPC routing tables integrations", "Client connection logging logs", "Custom network access policies"],
    useCases: ["Providing developers secure access to private database subnets", "Remote work connections to cloud development environments", "Managing user-level hybrid network authorization keys"],
    pricingModels: ["Active Client VPN Endpoint Hourly", "Active User Connection hour"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["client vpn", "openvpn", "remote access", "developer vpn"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/",
    isFeatured: false,
    status: "GA",
    displayOrder: 560,
    comparisonTags: ["Virtual Private Network", "Remote Access"]
  },
  {
    serviceCode: "globalaccelerator",
    name: "AWS Global Accelerator",
    slug: "aws-global-accelerator",
    categorySlug: "networking",
    shortDescription: "Optimize application speed using AWS edge network routing.",
    fullDescription: "AWS Global Accelerator is a networking service that improves your users' speed and availability by routing traffic through the global AWS high-performance network infrastructure.",
    characteristics: ["Static Anycast IP addresses allocations", "Dynamic network path optimization", "Global endpoint failover configurations"],
    features: ["Dual static IP address attachments", "Instant endpoint health failovers", "TCP/UDP traffic weight configurations", "DDoS protection shields integration"],
    useCases: ["Accelerating global API server load times", "Optimizing real-time voice VoIP connections", "Global multiplayer gaming traffic routing"],
    pricingModels: ["Fixed Accelerator Hourly fee", "Data Transfer Premium Egress (per GB)"],
    relatedServices: [{ name: "Elastic Load Balancing", slug: "elastic-load-balancing" }, { name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["accelerator", "anycast ip", "global routing", "latency optimizer"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/global-accelerator/",
    isFeatured: false,
    status: "GA",
    displayOrder: 570,
    comparisonTags: ["Traffic Optimizer", "Anycast Routing"]
  },
  {
    serviceCode: "cloudmap",
    name: "AWS Cloud Map",
    slug: "aws-cloud-map",
    categorySlug: "networking",
    shortDescription: "Cloud resource discovery service registry for microservices.",
    fullDescription: "AWS Cloud Map is a cloud resource discovery service. With Cloud Map, you can define custom names for your application resources, and it maintains up-to-date registry paths.",
    characteristics: ["Dynamic microservices directory lookup", "Supports HTTP and DNS query patterns", "Real-time resource health checkers"],
    features: ["Service discovery registries configuration", "Resource attribute labels tracking", "VPC DNS auto-integration", "REST discovery API routes"],
    useCases: ["Microservices API endpoint tracking registers", "ECS task discovery and connection pathways", "Kubernetes service mapping syncs"],
    pricingModels: ["Registered resource count", "DNS/API discovery queries volume"],
    relatedServices: [{ name: "Amazon ECS", slug: "amazon-ecs" }, { name: "Amazon EKS", slug: "amazon-eks" }],
    keywords: ["cloud map", "service discovery", "microservices registry", "dns registry"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cloud-map/",
    isFeatured: false,
    status: "GA",
    displayOrder: 580,
    comparisonTags: ["Service Registry", "Application Discovery"]
  },
  {
    serviceCode: "appmesh",
    name: "AWS App Mesh",
    slug: "aws-app-mesh",
    categorySlug: "networking",
    shortDescription: "Application-level networking service mesh for microservices.",
    fullDescription: "AWS App Mesh provides application-level networking, making it easy for your services to communicate with each other across multiple types of compute infrastructure.",
    characteristics: ["Envoy sidecar proxy configuration", "Logical service mesh isolation control", "Microservices trace/metric aggregators"],
    features: ["Virtual Routers path rules", "Virtual Services endpoints configuration", "Envoy proxy sidecar injectors", "X-Ray tracing integration support"],
    useCases: ["Standardizing microservices mutual TLS security", "Canary deployment traffic splitting rules", "Detailed service-to-service communication traces"],
    pricingModels: ["No extra charge (pay for underlying compute resources running Envoy)"],
    relatedServices: [{ name: "Amazon ECS", slug: "amazon-ecs" }, { name: "Amazon EKS", slug: "amazon-eks" }],
    keywords: ["service mesh", "app mesh", "envoy", "canary", "microservice network"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/app-mesh/",
    isFeatured: false,
    status: "GA",
    displayOrder: 590,
    comparisonTags: ["Service Mesh", "Microservices Networking"]
  },
  {
    serviceCode: "networkfirewall",
    name: "AWS Network Firewall",
    slug: "aws-network-firewall",
    categorySlug: "networking",
    shortDescription: "Stateful network protection firewall for virtual networks.",
    fullDescription: "AWS Network Firewall is a managed service that makes it easy to deploy essential network protections for all of your Virtual Private Clouds (VPCs) instantly.",
    characteristics: ["Stateful traffic inspection filters", "Highly available managed endpoints", "Central security policy integrations"],
    features: ["Layer 3-7 deep packet inspection", "Suricata rule syntax support", "VPC route table redirect attachments", "Firewall Manager centralized setup"],
    useCases: ["Filtering VPC outbound internet traffic", "Blocking malicious domain requests dynamically", "Inspecting inter-VPC network traffic flows"],
    pricingModels: ["Active Firewall Endpoint Hour", "Data inspected per GB Volume"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }, { name: "AWS Firewall Manager", slug: "aws-firewall-manager" }],
    keywords: ["network firewall", "firewall", "vpc firewall", "stateful packet", "suricata"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/network-firewall/",
    isFeatured: false,
    status: "GA",
    displayOrder: 600,
    comparisonTags: ["Network Firewall", "VPC Security"]
  },
  {
    serviceCode: "cloudwan",
    name: "AWS Cloud WAN",
    slug: "aws-cloud-wan",
    categorySlug: "networking",
    shortDescription: "Managed global wide area network manager.",
    fullDescription: "AWS Cloud WAN is a managed wide area network (WAN) service that connects your on-premises datacenters, branch offices, and AWS VPCs over the global AWS network.",
    characteristics: ["Global enterprise backbone routing", "Policy-driven network layouts", "Unified multi-region network management"],
    features: ["Core Network Policy (CNP) configurations", "Automated transit gateway peering links", "Global segment separations", "Network Manager visualization graphs"],
    useCases: ["Interconnecting branch offices globally over AWS", "Structuring corporate global multi-account VPC networks", "Centralizing global corporate security policies"],
    pricingModels: ["Core Network Connection Hours", "Data processed per GB Volume"],
    relatedServices: [{ name: "AWS Transit Gateway", slug: "aws-transit-gateway" }],
    keywords: ["wan", "cloud wan", "backbone", "branch network", "global routing"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/network-manager/latest/cloudwan/what-is-cloudwan.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 610,
    comparisonTags: ["Wide Area Network", "Global Router"]
  },
  {
    serviceCode: "private5g",
    name: "AWS Private 5G",
    slug: "aws-private-5g",
    categorySlug: "networking",
    shortDescription: "Design, deploy, and scale private 5G mobile networks.",
    fullDescription: "AWS Private 5G is a managed service that makes it easy to design, deploy, and scale your own private mobile network, providing hardware SIM cards and radio units.",
    characteristics: ["Managed cellular hardware deployments", "Local private cellular endpoints", "Simplicity compared to standard carrier setups"],
    features: ["AWS-managed radio hardware units", "SIM card provisioning kits", "VPC local subnet connections", "Central Console device registers"],
    useCases: ["Low latency warehouse smart sensor networks", "Secure mobile coverage for corporate campus grids", "IoT manufacturing robotic telemetry channels"],
    pricingModels: ["Hourly Radio Unit Connection Rate"],
    relatedServices: [{ name: "AWS Outposts", slug: "aws-outposts" }],
    keywords: ["private 5g", "5g radio", "cellular network", "sim cards"],
    awsDocumentationUrl: "https://aws.amazon.com/private5g/",
    isFeatured: false,
    status: "GA",
    displayOrder: 620,
    comparisonTags: ["Private Cellular Network", "On-Premises Infrastructure"]
  },
  {
    serviceCode: "vpclattice",
    name: "Amazon VPC Lattice",
    slug: "amazon-vpc-lattice",
    categorySlug: "networking",
    shortDescription: "Consistent service-to-service communication framework.",
    fullDescription: "Amazon VPC Lattice is a fully managed application-layer networking service that simplifies service-to-service communication, load balancing, and access control across VPC subnets.",
    characteristics: ["Application-layer network virtualization", "Simplified cross-VPC connections", "Integrated access control policies"],
    features: ["VPC Lattice Service Directories configuration", "Layer 7 routing rules (HTTP/HTTPS/gRPC)", "IAM service authorization policies", "Automated HTTPS certificate generations"],
    useCases: ["Connecting microservices across separate VPC accounts", "Load balancing container workloads easily", "Enforcing uniform zero-trust inter-service authorization"],
    pricingModels: ["Active VPC Lattice Service Hour", "Data processed per GB Volume"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }, { name: "Elastic Load Balancing", slug: "elastic-load-balancing" }],
    keywords: ["vpc lattice", "lattice", "service network", "cross vpc link"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/vpc-lattice/",
    isFeatured: false,
    status: "GA",
    displayOrder: 630,
    comparisonTags: ["Application Networking", "Service Mesh Router"]
  }
];
