import { SeedService } from "./seed-services-part1.js";

export const seedServicesPart3: SeedService[] = [
  // DEVELOPER TOOLS
  {
    serviceCode: "codecommit",
    name: "AWS CodeCommit",
    slug: "aws-code-commit",
    categorySlug: "developer-tools",
    shortDescription: "Securely host private Git repositories in the cloud.",
    fullDescription: "AWS CodeCommit is a fully managed source control service that hosts secure Git-based repositories. It makes it easy for teams to collaborate on code in a highly scalable and secure ecosystem.",
    characteristics: ["Fully managed Git servers", "IAM credential access permissions", "S3 backed repository storage"],
    features: ["Standard Git command support", "Branch pull request workflows Console", "Repository notifications triggers (SNS)", "KMS encryption by default"],
    useCases: ["Private company codebase version control", "Triggering build pipelines on code commit", "Multi-developer repository collaborations"],
    pricingModels: ["First 5 Active Users Free", "Per Active User per Month ($1.00)"],
    relatedServices: [{ name: "AWS CodeBuild", slug: "aws-code-build" }, { name: "AWS CodePipeline", slug: "aws-code-pipeline" }],
    keywords: ["git", "codecommit", "repository", "source control", "code host", "version control"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codecommit/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1330,
    comparisonTags: ["Git Repository", "Source Control"]
  },
  {
    serviceCode: "codebuild",
    name: "AWS CodeBuild",
    slug: "aws-code-build",
    categorySlug: "developer-tools",
    shortDescription: "Build code and run automated tests in container sandboxes.",
    fullDescription: "AWS CodeBuild is a fully managed build service that compiles source code, runs tests, and produces software packages that are ready to deploy.",
    characteristics: ["On-demand scaling build container nodes", "Continuous test execution sandboxes", "Pre-configured build OS runtimes"],
    features: ["Buildspec.yml configuration support", "Docker image compiling pipelines", "Artifact caching configurations (S3)", "VPC network build subnets link"],
    useCases: ["Compiling Java/Go source code binaries", "Running JavaScript test suites in pipelines", "Building and pushing Docker images to ECR"],
    pricingModels: ["Build instance compute minute tiers"],
    relatedServices: [{ name: "Amazon ECR", slug: "amazon-ecr" }, { name: "AWS CodePipeline", slug: "aws-code-pipeline" }],
    keywords: ["build", "compiler", "ci cd", "tests run", "codebuild", "continuous integration"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codebuild/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1340,
    comparisonTags: ["CI Tool", "Build Pipeline"]
  },
  {
    serviceCode: "codedeploy",
    name: "AWS CodeDeploy",
    slug: "aws-code-deploy",
    categorySlug: "developer-tools",
    shortDescription: "Automate code deployments to EC2, ECS, and Lambda.",
    fullDescription: "AWS CodeDeploy is a fully managed deployment service that automates software deployments to a variety of compute services such as Amazon EC2, Fargate, ECS, AWS Lambda, and on-premises servers.",
    characteristics: ["Automated rolling deployment scripts", "Multi-environment deploy routing policies", "Centralized deployment state logs"],
    features: ["Appspec.yml configuration support", "Blue/Green deployment traffic routing", "EC2 Systems Agent linkages", "Automated deployment rollback on alarms"],
    useCases: ["Rolling updates to EC2 server clusters", "Deploying new Lambda functions with traffic Canary rules", "Updating ECS container tasks configurations"],
    pricingModels: ["Free (deploying to AWS compute)", "Per On-Premises Server deployment ($0.02)"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "AWS CodePipeline", slug: "aws-code-pipeline" }],
    keywords: ["deploy", "rollback", "blue green", "codedeploy", "deployment automation"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codedeploy/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1350,
    comparisonTags: ["CD Tool", "Deployment Automation"]
  },
  {
    serviceCode: "codepipeline",
    name: "AWS CodePipeline",
    slug: "aws-code-pipeline",
    categorySlug: "developer-tools",
    shortDescription: "Orchestrate multi-stage build, test, and deploy pipelines.",
    fullDescription: "AWS CodePipeline is a fully managed continuous delivery service that helps you automate your release pipelines for fast and reliable application and infrastructure updates.",
    characteristics: ["Multi-stage delivery orchestration workflows", "Visual pipeline state graphs Console", "Multi-service event trigger links"],
    features: ["Custom Action type bindings", "Manual approval gate checkpoints", "S3 source/artifact tracking", "VPC network pipeline integrations"],
    useCases: ["Orchestrating Git-commit to production-deploy paths", "Automating compliance check gates in pipelines", "Structuring multi-account environment rollout sequences"],
    pricingModels: ["Active Pipeline per Month Rate ($1.00)"],
    relatedServices: [{ name: "AWS CodeCommit", slug: "aws-code-commit" }, { name: "AWS CodeBuild", slug: "aws-code-build" }, { name: "AWS CodeDeploy", slug: "aws-code-deploy" }],
    keywords: ["pipeline", "ci/cd", "continuous delivery", "release workflow", "codepipeline"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codepipeline/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1360,
    comparisonTags: ["CI/CD Pipeline", "Release Orchestration"]
  },
  {
    serviceCode: "codeartifact",
    name: "AWS CodeArtifact",
    slug: "aws-code-artifact",
    categorySlug: "developer-tools",
    shortDescription: "Secure private repository registry for npm, PyPI, and Maven packages.",
    fullDescription: "AWS CodeArtifact is a fully managed artifact repository service that makes it easy for organizations of any size to securely store, publish, and share software packages.",
    characteristics: ["Multi-format registry engines support", "IAM package access permission policies", "Automated upstream repository proxy syncs"],
    features: ["Npm/Pip/Maven package formats support", "Upstream package firewall rules (blocking bad links)", "Cross-account package sharing setups", "KMS package volume encryption"],
    useCases: ["Hosting private corporate npm packages", "Caching public PyPI modules internally for builds", "Sharing compiled Java libraries across dev teams"],
    pricingModels: ["Package Storage consumed per GB", "Package API request volume"],
    relatedServices: [{ name: "AWS CodeBuild", slug: "aws-code-build" }],
    keywords: ["artifact", "pypi private", "npm registry", "maven server", "codeartifact"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codeartifact/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1370,
    comparisonTags: ["Artifact Registry", "Package Repository"]
  },
  {
    serviceCode: "codestar",
    name: "AWS CodeStar",
    slug: "aws-code-star",
    categorySlug: "developer-tools",
    shortDescription: "Unified developer dashboard to quickly create project setups.",
    fullDescription: "AWS CodeStar enables you to quickly develop, build, and deploy applications on AWS. It provides a unified user interface, letting you easily manage your activities.",
    characteristics: ["Click-to-project setup templates", "Unified team management dashboards", "Integrated project issue logs Console"],
    features: ["Project template setups (Node/Python/Java)", "Integrated Git/Build/Deploy pipeline setups", "Jira issue tracker links dashboards", "IAM permissions team configuration"],
    useCases: ["Creating complete web app project templates instantly", "Managing developer task permissions in teams", "Tracking release pipeline statuses visually"],
    pricingModels: ["Free (pay for underlying pipeline/compute resources)"],
    relatedServices: [{ name: "AWS CodePipeline", slug: "aws-code-pipeline" }],
    keywords: ["project setup", "codestar", "developer dashboard", "project template"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codestar/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1380,
    comparisonTags: ["DevOps Dashboard", "Project Scaffolding"]
  },
  {
    serviceCode: "cloud9",
    name: "AWS Cloud9",
    slug: "aws-cloud9",
    categorySlug: "developer-tools",
    shortDescription: "Browser-based cloud IDE write, run, and debug code.",
    fullDescription: "AWS Cloud9 is a cloud-based integrated development environment (IDE) that lets you write, run, and debug your code with just a browser. It includes a code editor and terminal.",
    characteristics: ["Browser-based code editor interfaces", "Integrated EC2 console terminal access", "Collaborative pair programming environments"],
    features: ["Real-time multi-user editing", "Built-in SDKs and CLI configurations", "Dynamic EC2 auto-stop rules", "Debugger break points Console"],
    useCases: ["Coding projects on lightweight Chromebook devices", "Pair programming code debugging exercises", "Managing private servers files via CLI terminal"],
    pricingModels: ["No extra charge (pay for underlying EC2/EBS resources)"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["ide", "cloud9", "code editor", "browser terminal", "pair coding"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cloud9/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1390,
    comparisonTags: ["Cloud IDE", "Developer Workspace"]
  },
  {
    serviceCode: "cli",
    name: "AWS CLI",
    slug: "aws-cli",
    categorySlug: "developer-tools",
    shortDescription: "Command Line Interface managing AWS resources via scripts.",
    fullDescription: "The AWS Command Line Interface (CLI) is a unified tool to manage your AWS services. With just one tool to download and configure, you can control multiple services.",
    characteristics: ["Terminal command script inputs", "Cross-platform executable utilities", "Unified API wrapper formats"],
    features: ["Access credentials profiles configuration", "JSON API request/response format overrides", "Server shell piping compatibilities", "Auto-completion bash scripts support"],
    useCases: ["Automating S3 file backups using scripts", "Querying list of active EC2 instances", "Creating dynamic infrastructure scaling terminal tools"],
    pricingModels: ["Open-Source Command Line Client"],
    relatedServices: [{ name: "AWS IAM", slug: "aws-iam" }],
    keywords: ["cli", "terminal cmd", "scripts command", "aws command", "bash link"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cli/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1400,
    comparisonTags: ["Command Line Interface", "CLI Tool"]
  },
  {
    serviceCode: "sdks",
    name: "AWS SDKs",
    slug: "aws-sdks",
    categorySlug: "developer-tools",
    shortDescription: "Software Development Kits for major programming languages.",
    fullDescription: "AWS Software Development Kits (SDKs) allow you to build, deploy, and manage applications that connect directly to AWS APIs using native code packages.",
    characteristics: ["Language specific wrappers packages", "Automatic HTTP call retry models", "Standard client class constructs"],
    features: ["Supports JavaScript/Python/Java/Go/C#/PHP/Ruby/Rust/C++", "IAM credentials local profile discovery", "Detailed error code structures", "API request signature V4 compilers"],
    useCases: ["Writing application code to write to DynamoDB tables", "Uploading user profile photos to S3 from code", "Sending alerts to SNS from backend APIs"],
    pricingModels: ["Open-Source Client Library Collections"],
    relatedServices: [{ name: "AWS IAM", slug: "aws-iam" }],
    keywords: ["sdk", "boto3", "node sdk", "java sdk", "pypi aws", "code package"],
    awsDocumentationUrl: "https://aws.amazon.com/developer/tools/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1410,
    comparisonTags: ["Software Development Kit", "Developer Library"]
  },
  {
    serviceCode: "cdk",
    name: "AWS CDK",
    slug: "aws-cdk",
    categorySlug: "developer-tools",
    shortDescription: "Define cloud infrastructure using standard programming code.",
    fullDescription: "The AWS Cloud Development Kit (CDK) is an open-source software development framework to define your cloud application resources using familiar programming languages.",
    characteristics: ["Infrastructure as Code (IaC) programmatic frameworks", "Object-oriented resource construct libraries", "Synthesizes to CloudFormation templates"],
    features: ["Supports TS/JS/Python/Java/Go/C#", "Construct reusable module configurations", "Diff checks before deploy operations", "Integrated deployment terminal actions"],
    useCases: ["Writing TypeScript code to build VPC networks", "Configuring EC2 groups with construct parameters", "Distributing standard infrastructure blueprints in teams"],
    pricingModels: ["Open-Source Synthesizer Framework"],
    relatedServices: [{ name: "AWS CloudFormation", slug: "aws-cloudformation" }],
    keywords: ["cdk", "infrastructure as code", "typescript cloud", "synthesizer", "constructs"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cdk/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1420,
    comparisonTags: ["Infrastructure as Code", "CDK Framework"]
  },
  {
    serviceCode: "sam",
    name: "AWS SAM",
    slug: "aws-sam",
    categorySlug: "developer-tools",
    shortDescription: "Serverless Application Model CLI template compiler.",
    fullDescription: "AWS Serverless Application Model (SAM) is an open-source framework for building serverless applications on AWS. It provides a CLI and shorthand template syntax.",
    characteristics: ["Serverless specific shorthand templates", "Local Lambda function testing runtimes", "Synthesizes to CloudFormation stacks"],
    features: ["Local API Gateway mock servers CLI", "Docker-based Lambda emulation environments", "SAM template validation rules check", "Serverless deployment packaging scripts"],
    useCases: ["Developing and testing Lambda APIs locally", "Defining API Gateway plus Lambda in few YAML lines", "Deploying serverless web app backends"],
    pricingModels: ["Open-Source CLI Tool Framework"],
    relatedServices: [{ name: "AWS Lambda", slug: "aws-lambda" }, { name: "AWS CloudFormation", slug: "aws-cloudformation" }],
    keywords: ["sam", "serverless template", "local lambda", "sam cli", "yaml compile"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/serverless-application-model/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1430,
    comparisonTags: ["Infrastructure as Code", "Serverless Tool"]
  },
  {
    serviceCode: "xray",
    name: "AWS X-Ray",
    slug: "aws-x-ray",
    categorySlug: "developer-tools",
    shortDescription: "Analyze and debug distributed microservices applications.",
    fullDescription: "AWS X-Ray helps developers analyze and debug distributed applications, such as those built using a microservices architecture, mapping request paths.",
    characteristics: ["End-to-end trace request maps", "Service latency profiles charts", "Cross-account client trace tracking"],
    features: ["X-Ray daemon background agents", "Service Map graph visualizations Console", "Trace filtering expressions dashboards", "SDK inter-service route decorators"],
    useCases: ["Finding latency hot-spots in microservice APIs", "Tracking database queries execution speeds from code", "Tracing failed requests pathways across lambdas"],
    pricingModels: ["Traces segments ingested volume", "Traces queries retrieved volume"],
    relatedServices: [{ name: "Amazon CloudWatch", slug: "amazon-cloudwatch" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["xray", "tracing", "debugging", "latency map", "microservices trace", "apm"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/xray/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1440,
    comparisonTags: ["Application Performance Monitoring", "Tracing Tool"]
  },
  {
    serviceCode: "codecatalyst",
    name: "Amazon CodeCatalyst",
    slug: "amazon-codecatalyst",
    categorySlug: "developer-tools",
    shortDescription: "Unified software development service hosting workspaces.",
    fullDescription: "Amazon CodeCatalyst is a unified software development service that hosts source code, runs pipelines, manages issues, and provides cloud development workspaces.",
    characteristics: ["All-in-one DevOps web portal", "SaaS team collab spaces", "Cloud Dev Environment hosting"],
    features: ["Dev Workspace cloud containers", "Issue tracking board panels", "Github connection integrations", "Workflow action catalog pipelines"],
    useCases: ["Onboarding developers with pre-made cloud workspaces", "Managing team dev tasks on kanban boards", "Running build pipelines with Github triggers"],
    pricingModels: ["Free Tier (Up to 5 Users)", "Professional Tier Monthly per User"],
    relatedServices: [{ name: "AWS Cloud9", slug: "aws-cloud9" }],
    keywords: ["codecatalyst", "devops platform", "cloud workspaces", "issue tracker"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codecatalyst/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1450,
    comparisonTags: ["DevOps Platform", "Developer Workspace"]
  },
  {
    serviceCode: "cloudshell",
    name: "AWS CloudShell",
    slug: "aws-cloudshell",
    categorySlug: "developer-tools",
    shortDescription: "Browser-based console terminal preloaded with CLI tools.",
    fullDescription: "AWS CloudShell is a browser-based shell that makes it easy to securely manage, explore, and interact with your AWS resources. CloudShell is pre-authenticated.",
    characteristics: ["Browser CLI access terminal", "Pre-installed popular admin packages", "Automatic temporary storage allocation"],
    features: ["Built-in CLI, CDK, and SAM executables", "1GB persistent home folder space", "Multiple tab window layouts", "Direct file upload/download links Console"],
    useCases: ["Quick CLI commands execution from browser", "Prototyping CDK files scripts", "Uploading configuration scripts to test AMIs"],
    pricingModels: ["Free (Included with AWS Console)"],
    relatedServices: [{ name: "AWS CLI", slug: "aws-cli" }],
    keywords: ["cloudshell", "terminal browser", "bash console", "cli tool preinstalled"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cloudshell/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1460,
    comparisonTags: ["Developer Workspace", "CLI Tool"]
  },
  {
    serviceCode: "appcomposer",
    name: "AWS Application Composer",
    slug: "aws-application-composer",
    categorySlug: "developer-tools",
    shortDescription: "Visually design and build serverless apps in templates.",
    fullDescription: "AWS Application Composer helps you visually design, configure, and build serverless applications from AWS services, generating CloudFormation templates automatically.",
    characteristics: ["Visual drag-and-drop designer canvas", "Real-time model design validation", "Direct local file synchronizer"],
    features: ["Interactive canvas design panels", "Shorthand SAM/CloudFormation code compiler", "Drag-and-drop Lambda/DynamoDB connections", "VPC routing visual connections layout"],
    useCases: ["Designing serverless architecture diagrams visually", "Generating correct YAML configurations for Lambdas", "Fast prototyping of microservices configurations in teams"],
    pricingModels: ["Free Visual Designer Tool"],
    relatedServices: [{ name: "AWS SAM", slug: "aws-sam" }],
    keywords: ["composer", "visual design", "serverless drag drop", "designer canvas"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/application-composer/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1470,
    comparisonTags: ["Visual Editor", "Infrastructure as Code"]
  },
  {
    serviceCode: "fis",
    name: "AWS FIS",
    slug: "aws-fault-injection-service",
    categorySlug: "developer-tools",
    shortDescription: "Managed chaos engineering service injection faults.",
    fullDescription: "AWS Fault Injection Service (FIS) is a fully managed service for running chaos engineering experiments on AWS to test application resilience and fault tolerance.",
    characteristics: ["Structured system chaos experiments", "Safe experiment abort control triggers", "AWS multi-service failure integrations"],
    features: ["CPU load inject operations", "Network latency delay simulations", "EC2 termination simulation templates", "CloudWatch alarm integration safety checks"],
    useCases: ["Testing web server failovers under load", "Simulating database network latency spikes", "Auditing application recovery response plans"],
    pricingModels: ["Per Action Minute execution rate"],
    relatedServices: [{ name: "Amazon CloudWatch", slug: "amazon-cloudwatch" }, { name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["fis", "chaos engineering", "fault injection", "resilience test", "chaos monkey"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/fis/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1480,
    comparisonTags: ["Chaos Engineering", "Testing Tool"]
  },

  // MANAGEMENT & GOVERNANCE
  {
    serviceCode: "cloudformation",
    name: "AWS CloudFormation",
    slug: "aws-cloudformation",
    categorySlug: "management",
    shortDescription: "Model and provision AWS resources with JSON/YAML code templates.",
    fullDescription: "AWS CloudFormation allows you to model and set up your AWS resources so that you can spend less time managing those resources and more time focusing on your apps.",
    characteristics: ["Declarative configuration JSON/YAML templates", "Centralized stack lifecycle management", "Automated dependency resolve trees"],
    features: ["Stack creation/update policies control", "Change Set previews before execute", "Drift detection resource tracking", "Custom resource integrations (Lambda extensions)"],
    useCases: ["Replicating production environments for testing", "Deploying database infrastructure dynamically via pipelines", "Standardizing server architectures company-wide"],
    pricingModels: ["Free (pay for created AWS resources)", "Custom Namespace registers fee"],
    relatedServices: [{ name: "AWS CDK", slug: "aws-cdk" }, { name: "AWS Config", slug: "aws-config" }],
    keywords: ["cloudformation", "iac", "yaml template", "stacks", "json deploy", "infrastructure as code"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cloudformation/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1490,
    comparisonTags: ["Infrastructure as Code", "Cloud Orchestration"]
  },
  {
    serviceCode: "ssm",
    name: "AWS Systems Manager",
    slug: "aws-systems-manager",
    categorySlug: "management",
    shortDescription: "Configure and manage AWS and on-premises server fleets.",
    fullDescription: "AWS Systems Manager (SSM) provides a centralized dashboard interface that allows you to configure, manage, patch, and execute commands on large pools of server instances.",
    characteristics: ["Cross-platform node agent links", "No inbound SSH port requirements", "Fleet-level automation workflows"],
    features: ["Session Manager secure command shells", "Run Command batch script distributions", "Parameter Store central config secrets", "Patch Manager automation schedules"],
    useCases: ["Secure shell login to private EC2 instances", "Running security patches on 100+ servers", "Storing app configuration properties safely"],
    pricingModels: ["Free (Core instance management features)", "Advanced Parameter Store fees", "Automation execution steps volume"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "AWS KMS", slug: "aws-kms" }],
    keywords: ["systems manager", "ssm", "session manager", "patching", "run command", "parameter store"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/systems-manager/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1500,
    comparisonTags: ["Systems Management", "Operations Center"]
  },
  {
    serviceCode: "config",
    name: "AWS Config",
    slug: "aws-config",
    categorySlug: "management",
    shortDescription: "Audit and record resource configuration changes over time.",
    fullDescription: "AWS Config continuously monitors and records your AWS resource configurations, allowing you to audit compliance, check histories, and automate remediation.",
    characteristics: ["Continuous configuration change logging", "Compliance state rule checkers", "Relationship dependency maps mapping"],
    features: ["AWS Config Rules (custom/managed)", "Configuration history timelines visualization", "Auto remediation Lambda triggers", "Organizations centralized rules setups"],
    useCases: ["Auditing S3 bucket public access changes history", "Enforcing encrypt volumes rule checks automatically", "Tracking server Security Group ports modifications over time"],
    pricingModels: ["Configuration Item recorded volume", "Active Config Rule evaluation runs"],
    relatedServices: [{ name: "AWS CloudTrail", slug: "aws-cloudtrail" }, { name: "AWS Security Hub", slug: "aws-security-hub" }],
    keywords: ["config", "audit resource", "compliance rules", "change timeline", "configuration history"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/config/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1510,
    comparisonTags: ["Compliance Audit", "Postural Security"]
  },
  {
    serviceCode: "cloudwatch",
    name: "Amazon CloudWatch",
    slug: "amazon-cloudwatch",
    categorySlug: "management",
    shortDescription: "Monitor resources, collect metrics, and configure alerts.",
    fullDescription: "Amazon CloudWatch is a monitoring and observability service built for DevOps engineers, developers, site reliability engineers (SREs), and IT managers.",
    characteristics: ["High-resolution metric graphs dashboard", "Centralized log ingestion buckets", "Automated alert action loops"],
    features: ["Alarms threshold actions configurations", "Container Insights metric agents", "Synthetics website canary checkers", "Logs Insights SQL queries support"],
    useCases: ["Tracking EC2 server CPU metrics graphs", "Collecting application errors log files", "Alerting DevOps on database connection spikes"],
    pricingModels: ["Metric queries volume", "Log storage data volume ingested per GB", "Active Alarm count per Month"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Amazon SNS", slug: "amazon-sns" }],
    keywords: ["logs", "alarms", "cloudwatch", "metrics", "monitoring", "observability"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cloudwatch/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1520,
    comparisonTags: ["DevOps Monitoring", "Operational AI", "Logging Platform"]
  },
  {
    serviceCode: "controltower",
    name: "AWS Control Tower",
    slug: "aws-control-tower",
    categorySlug: "management",
    shortDescription: "Set up and govern secure, compliant multi-account setups.",
    fullDescription: "AWS Control Tower provides the easiest way to set up and govern a secure, multi-account AWS environment based on AWS best practices and landing zones.",
    characteristics: ["Multi-account structure orchestrator", "Automated compliance guardrail rules", "Standard landing zone blueprints"],
    features: ["Account Factory automated account creation", "CIS benchmark landing configurations", "Config rules guardrails compliance dashboards", "IAM SSO control bindings"],
    useCases: ["Setting up isolated environments for new projects", "Enforcing company corporate security policies in accounts", "Creating audited log-archive landing accounts"],
    pricingModels: ["Free (pay for created Service Catalog/Config/S3 resources)"],
    relatedServices: [{ name: "AWS Organizations", slug: "aws-organizations" }, { name: "AWS Service Catalog", slug: "aws-service-catalog" }],
    keywords: ["landing zone", "control tower", "multi account setup", "guardrails compliance"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/controltower/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1530,
    comparisonTags: ["Multi-Account Governance", "Cloud Orchestration"]
  },
  {
    serviceCode: "organizations",
    name: "AWS Organizations",
    slug: "aws-organizations",
    categorySlug: "management",
    shortDescription: "Centralized management and billing for multiple AWS accounts.",
    fullDescription: "AWS Organizations helps you centrally manage and govern your environment as you grow and scale your AWS resources, managing unified billing structures.",
    characteristics: ["Hierarchical account groups (OUs)", "Consolidated billing invoices center", "Organization-wide permission blocks"],
    features: ["Service Control Policies (SCPs) control", "Cross-account payment aggregates", "Automated member account creation APIs", "AWS RAM resources sharing integration"],
    useCases: ["Blocking member accounts from deleting CloudTrail", "Consolidating company monthly AWS spend invoices", "Managing database access groups across account boundaries"],
    pricingModels: ["Free (Core governance billing feature)"],
    relatedServices: [{ name: "AWS IAM", slug: "aws-iam" }, { name: "AWS Resource Access Manager", slug: "aws-resource-access-manager" }],
    keywords: ["organizations", "scp", "consolidated billing", "ou", "multi account billing", "governance"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/organizations/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1540,
    comparisonTags: ["Multi-Account Governance", "Billing Service"]
  },
  {
    serviceCode: "servicecatalog",
    name: "AWS Service Catalog",
    slug: "aws-service-catalog",
    categorySlug: "management",
    shortDescription: "Create and manage portfolios of approved AWS services.",
    fullDescription: "AWS Service Catalog allows organizations to create and manage portfolios of IT services that are approved for use on AWS, ensuring uniform compliance.",
    characteristics: ["Self-service application portals", "CloudFormation based blueprints", "Permissions validation wrappers"],
    features: ["Product templates portfolios creation", "IAM launch role mappings", "Version constraint controls", "User launch parameter restrictions"],
    useCases: ["Allowing developers to launch pre-approved databases", "Enforcing standard VPC setups in sandbox accounts", "Managing infrastructure version updates centrally"],
    pricingModels: ["Active portfolio API query volumes"],
    relatedServices: [{ name: "AWS CloudFormation", slug: "aws-cloudformation" }],
    keywords: ["catalog", "portfolios", "approved templates", "self service", "service catalog"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/servicecatalog/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1550,
    comparisonTags: ["Service Catalog", "Cloud Orchestration"]
  },
  {
    serviceCode: "wellarchitected",
    name: "Well-Architected Tool",
    slug: "aws-well-architected-tool",
    categorySlug: "management",
    shortDescription: "Review and improve workloads using AWS best practices.",
    fullDescription: "The AWS Well-Architected Tool helps you define, review, and track the state of your workloads against the 6 pillars of AWS best practices architecture.",
    characteristics: ["Self-service assessment workflows", "Best practices structural checklists", "Milestone progress dashboards dashboard"],
    features: ["6 pillars evaluation worksheets", "Improvement plan PDF reports", "Custom Lens assessment templates", "Console workload definitions registers"],
    useCases: ["Reviewing application designs for security flaws", "Preparing infrastructure reviews for executives", "Auditing systems cost optimization checklists"],
    pricingModels: ["Free (Architecture assessment platform)"],
    relatedServices: [{ name: "AWS Trusted Advisor", slug: "aws-trusted-advisor" }],
    keywords: ["well architected", "pillars assessment", "architecture review", "best practices checklist"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/wellarchitected/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1560,
    comparisonTags: ["Architecture Review", "Compliance Audit"]
  },
  {
    serviceCode: "trustedadvisor",
    name: "AWS Trusted Advisor",
    slug: "aws-trusted-advisor",
    categorySlug: "management",
    shortDescription: "Automated recommendations for cost, security, and performance.",
    fullDescription: "AWS Trusted Advisor is an online tool that provides real-time guidance to help you provision your resources following AWS best practices, scanning configurations.",
    characteristics: ["Automated configuration scanner runs", "Check categories dashboards", "Actionable improvement recommendations"],
    features: ["Cost optimization checks (idle resources)", "Security best-practices checks (open ports)", "Fault tolerance checks (missing backups)", "VPC network limit alarms warnings"],
    useCases: ["Finding active unattached EBS storage volumes", "Auditing public exposed ports in Security Groups", "Reviewing IAM permissions best practices compliance"],
    pricingModels: ["Free (Core checks)", "Business/Enterprise Support Plan check additions"],
    relatedServices: [{ name: "AWS Support", slug: "aws-support" }],
    keywords: ["trusted advisor", "optimization checks", "cost saver", "security check advisor"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/trustedadvisor/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1570,
    comparisonTags: ["Optimization Scanner", "Security Audit"]
  },
  {
    serviceCode: "computeoptimizer",
    name: "AWS Compute Optimizer",
    slug: "aws-compute-optimizer",
    categorySlug: "management",
    shortDescription: "ML-based sizing recommendations for EC2 and Lambda.",
    fullDescription: "AWS Compute Optimizer recommends optimal AWS resources for your workloads to reduce costs and improve performance by analyzing historical utilization metrics.",
    characteristics: ["Machine Learning sizing engines", "Performance metrics analytical graphs", "Sizing risk evaluation metrics"],
    features: ["EC2 instance sizing recommendations", "EBS volume sizing checks", "Lambda memory size adjustments", "ASG group size optimizations"],
    useCases: ["Finding over-provisioned EC2 server instances", "Adjusting Lambda function memory configurations", "Downsizing underutilized database storage disks"],
    pricingModels: ["Free (Standard metrics analysis)", "Enhanced Infrastructure Metrics fee"],
    relatedServices: [{ name: "Amazon EC2", slug: "amazon-ec2" }, { name: "Amazon CloudWatch", slug: "amazon-cloudwatch" }],
    keywords: ["compute optimizer", "instance sizing", "cost metrics", "overprovisioned EC2"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/compute-optimizer/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1580,
    comparisonTags: ["Optimization Scanner", "DevOps Monitoring"]
  },
  {
    serviceCode: "licensemanager",
    name: "AWS License Manager",
    slug: "aws-license-manager",
    categorySlug: "management",
    shortDescription: "Manage software licenses from vendors like Microsoft and Oracle.",
    fullDescription: "AWS License Manager makes it easy to manage your software licenses from software vendors (such as Microsoft, SAP, Oracle, and IBM) across AWS and on-premises.",
    characteristics: ["Dynamic license usage limits", "Auto enforcement rule sets", "Licensing audit log reports"],
    features: ["Active directory license allocations", "VCPU count tracking mechanisms", "Automated instance launch blockers", "Systems Manager inventory integration"],
    useCases: ["Enforcing Windows Server CAL limits on EC2", "Tracking Oracle DB processor license compliance", "Reporting license usage statistics to vendors"],
    pricingModels: ["Free (Core license tracking feature)"],
    relatedServices: [{ name: "AWS Systems Manager", slug: "aws-systems-manager" }],
    keywords: ["license manager", "licensing", "cal compliance", "oracle license", "microsoft license"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/license-manager/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1590,
    comparisonTags: ["License Management", "Compliance Audit"]
  },
  {
    serviceCode: "healthdashboard",
    name: "AWS Health Dashboard",
    slug: "aws-health-dashboard",
    categorySlug: "management",
    shortDescription: "Alerts and remediation guidance for AWS resource health.",
    fullDescription: "The AWS Health Dashboard provides alerts and remediation guidance when AWS is experiencing events that may affect you, displaying personalized service status reports.",
    characteristics: ["Personalized system status dashboards", "Event timeline logs visualization", "Automated webhook alert paths"],
    features: ["Account resource specific alerts", "Scheduled maintenance calendar events", "AWS health API endpoints access", "EventBridge automation integration hooks"],
    useCases: ["Checking if local region outages affect EC2 nodes", "Reviewing upcoming database hardware maintenance schedules", "Configuring Slack alerts on AWS outages"],
    pricingModels: ["Free (Standard dashboard)", "AWS Health API requires Business/Enterprise Support"],
    relatedServices: [{ name: "Amazon EventBridge", slug: "amazon-eventbridge" }],
    keywords: ["health dashboard", "outage reports", "personalized health", "service maintenance"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/health/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1600,
    comparisonTags: ["Service Status", "Alert Management"]
  },
  {
    serviceCode: "proton",
    name: "AWS Proton",
    slug: "aws-proton",
    categorySlug: "management",
    shortDescription: "Fully managed deployment service for container and serverless apps.",
    fullDescription: "AWS Proton is a fully managed delivery service for container and serverless applications. Platform teams can use it to build and manage standard template sets.",
    characteristics: ["Platform engineering template engines", "Declarative stack layout models", "Consistent serverless environment deployments"],
    features: ["Environment schema files template config", "Service pipelines creation pipelines", "CloudFormation backend deployments", "Console version control logs"],
    useCases: ["Standardizing serverless REST API setups", "Providing developers pre-made ECS template pipelines", "Managing microservices version rollouts globally"],
    pricingModels: ["Free (pay for created compute/pipeline resources)"],
    relatedServices: [{ name: "AWS CloudFormation", slug: "aws-cloudformation" }],
    keywords: ["proton", "platform engineering", "infrastructure templates", "service delivery"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/proton/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1610,
    comparisonTags: ["Infrastructure as Code", "Platform Management"]
  },
  {
    serviceCode: "ram",
    name: "AWS RAM",
    slug: "aws-resource-access-manager",
    categorySlug: "management",
    shortDescription: "Share AWS resources securely across separate accounts.",
    fullDescription: "AWS Resource Access Manager (RAM) helps you securely share your resources across AWS accounts, within your Organization or Organizational Units (OUs).",
    characteristics: ["Organizations-wide resource mappings", "Private network share configurations", "Eliminates duplicate resource setups"],
    features: ["Subnet private network sharing", "Transit Gateway sharing attachments", "Route 53 resolver rule sharing", "IAM resource share policies validation"],
    useCases: ["Sharing a single Transit Gateway with 50 accounts", "Allowing member accounts access to central VPC subnets", "Sharing internal private DNS hosted zones"],
    pricingModels: ["Free (Core cross-account resource sharing feature)"],
    relatedServices: [{ name: "AWS Organizations", slug: "aws-organizations" }, { name: "Amazon VPC", slug: "amazon-vpc" }],
    keywords: ["ram", "resource sharing", "cross account share", "share subnets"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/ram/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1620,
    comparisonTags: ["Resource Governance", "Access Control"]
  },
  {
    serviceCode: "budgets",
    name: "AWS Budgets",
    slug: "aws-budgets",
    categorySlug: "management",
    shortDescription: "Track AWS costs and usage with customizable alarms.",
    fullDescription: "AWS Budgets gives you the ability to set custom budgets that alert you when your costs or usage exceed (or are forecasted to exceed) your budgeted amount.",
    characteristics: ["Proactive budget limit alarms", "Flexible cost filters configurations", "Automated instance action scripts"],
    features: ["Cost/Usage/Savings Plans budget types", "Email and SNS alarm setups", "AWS Budgets Action execution scripts", "Daily cost forecasting graphs"],
    useCases: ["Alerting developers when monthly spend hits $500", "Sending billing reports to managers via email", "Stopping dev servers automatically if budget runs out"],
    pricingModels: ["First 2 Budgets Free", "Active Budget per Day Rate ($0.02)"],
    relatedServices: [{ name: "AWS Cost Explorer", slug: "aws-cost-explorer" }, { name: "Amazon SNS", slug: "amazon-sns" }],
    keywords: ["budgets", "billing alerts", "cost limits", "spend threshold", "billing control"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-managing-costs.html",
    isFeatured: true,
    status: "GA",
    displayOrder: 1630,
    comparisonTags: ["Billing Service", "Cost Governance"]
  },
  {
    serviceCode: "costexplorer",
    name: "AWS Cost Explorer",
    slug: "aws-cost-explorer",
    categorySlug: "management",
    shortDescription: "Visualize, understand, and manage your AWS spend.",
    fullDescription: "AWS Cost Explorer has an easy-to-use interface that lets you visualize, understand, and manage your AWS costs and usage over time, generating reports.",
    characteristics: ["Interactive cost visualization charts", "Historical cost data graphs", "Predictive spend forecast projections"],
    features: ["Dimension filters (Region/Account/Service)", "Resource cost tag filters", "Savings Plans coverage recommendations", "Daily/Monthly aggregation options"],
    useCases: ["Analyzing service cost changes over last 6 months", "Identifying which account spends most on EC2", "Reviewing Savings Plans purchase recommendations"],
    pricingModels: ["Free Console Access", "API Query request charges ($0.01/request)"],
    relatedServices: [{ name: "AWS Budgets", slug: "aws-budgets" }],
    keywords: ["cost explorer", "billing charts", "spending analysis", "historical cost"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html",
    isFeatured: true,
    status: "GA",
    displayOrder: 1640,
    comparisonTags: ["Billing Service", "Cost Governance"]
  },

  // APPLICATION INTEGRATION
  {
    serviceCode: "sns",
    name: "Amazon SNS",
    slug: "amazon-sns",
    categorySlug: "integration",
    shortDescription: "Pub/Sub message delivery service for app-to-app communication.",
    fullDescription: "Amazon Simple Notification Service (Amazon SNS) is a fully managed pub/sub messaging service for both application-to-application (A2A) and application-to-person (A2P) communication.",
    characteristics: ["Push-based message distribution logic", "High transactional throughput scaling", "Multi-endpoint delivery protocols"],
    features: ["SNS Topic subscriptions creation", "Message filtering policies support", "Delivery protocols (HTTP, SQS, Email, SMS)", "FIFO (First-In-First-Out) topic options"],
    useCases: ["Publishing user signup events to multiple microservices", "Sending transactional SMS text alerts to users", "Routing application error events to email channels"],
    pricingModels: ["Publish Operations volume (per million)", "SMS Message delivery rates"],
    relatedServices: [{ name: "Amazon SQS", slug: "amazon-sqs" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["pub/sub", "sns topic", "push notifications", "email delivery", "sms alert", "message broker"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/sns/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1650,
    comparisonTags: ["Message Broker", "Application Integration"]
  },
  {
    serviceCode: "sqs",
    name: "Amazon SQS",
    slug: "amazon-sqs",
    categorySlug: "integration",
    shortDescription: "Durable and scalable virtual message queues.",
    fullDescription: "Amazon Simple Queue Service (Amazon SQS) is a fully managed message queuing service that enables you to decouple and scale microservices, distributed systems, and serverless applications.",
    characteristics: ["Pull-based message buffers", "Decouples application component timing", "Message durability locking parameters"],
    features: ["Standard Queues (high scale, best-effort)", "FIFO Queues (exact ordering, once delivery)", "Dead-Letter Queue (DLQ) failed routing", "Visibility Timeout parameter locks"],
    useCases: ["Buffering user checkouts before payment processing", "Decoupling photo upload tasks to background containers", "Handling heavy spike events ingestion safely"],
    pricingModels: ["API request volume (GET/SEND) (per million)"],
    relatedServices: [{ name: "Amazon SNS", slug: "amazon-sns" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["queue", "sqs message", "decouple systems", "fifo queue", "dlq message", "message queue"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/sqs/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1660,
    comparisonTags: ["Message Queue", "Application Integration"]
  },
  {
    serviceCode: "stepfunctions",
    name: "AWS Step Functions",
    slug: "aws-step-functions",
    categorySlug: "integration",
    shortDescription: "Orchestrate serverless workflows using visual state machines.",
    fullDescription: "AWS Step Functions is a serverless orchestration service that lets you combine AWS Lambda functions and other AWS services to build business-critical applications.",
    characteristics: ["Visual state machine workflows Console", "Serverless workflow state preservation", "Long-running execution capabilities"],
    features: ["ASL (Amazon States Language) YAML configuration", "Parallel/Choice task routing logic", "Express and Standard workflow profiles", "Error catch and retry loops configuration"],
    useCases: ["Orchestrating multi-step credit application checks", "Configuring complex media transcode pipelines sequence", "Managing automated server cleanup sequences"],
    pricingModels: ["Standard Workflow State Transitions volume", "Express Workflow CPU/Memory Hour"],
    relatedServices: [{ name: "AWS Lambda", slug: "aws-lambda" }, { name: "Amazon EventBridge", slug: "amazon-eventbridge" }],
    keywords: ["workflows", "state machine", "step functions", "orchestration", "lambda flows"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/step-functions/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1670,
    comparisonTags: ["Workflow Orchestration", "Serverless Orchestration"]
  },
  {
    serviceCode: "eventbridge",
    name: "Amazon EventBridge",
    slug: "amazon-eventbridge",
    categorySlug: "integration",
    shortDescription: "Serverless event bus linking applications with event routing.",
    fullDescription: "Amazon EventBridge is a serverless event bus that makes it easy to connect applications together using data from your own applications, SaaS applications, and AWS services.",
    characteristics: ["Serverless event router structures", "Zero-infrastructure scale configuration", "SaaS vendor event integration hooks"],
    features: ["Custom Event Buses creation", "JSON event routing rule patterns", "Target linkages (Lambda, Step Functions, Kinesis)", "Event Schema Registry databases mapping"],
    useCases: ["Routing CRM vendor events directly to Lambdas", "Triggering error handlers on specific S3 upload events", "Orchestrating microservices based on event queues"],
    pricingModels: ["Events Ingested volume (per million) (AWS events are Free)"],
    relatedServices: [{ name: "AWS Step Functions", slug: "aws-step-functions" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["event bus", "eventbridge", "router event", "rule pattern", "saas event"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/eventbridge/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1680,
    comparisonTags: ["Event Router", "Serverless Orchestration", "Application Integration"]
  },
  {
    serviceCode: "appsync",
    name: "AWS AppSync",
    slug: "aws-appsync",
    categorySlug: "integration",
    shortDescription: "Managed GraphQL and Pub/Sub APIs with real-time sync.",
    fullDescription: "AWS AppSync is a fully managed service that makes it easy to develop GraphQL APIs by handling the secure connection to data sources like DynamoDB, Lambda, and more.",
    characteristics: ["GraphQL API endpoint compiler", "Real-time socket data subscriptions", "Unified resolver interface mappings"],
    features: ["GraphQL schema creation Console", "AppSync VTL/JS Resolver scripts", "Cognito/IAM API authorization scopes", "Caching query parameters layers"],
    useCases: ["Creating mobile app GraphQL backends", "Real-time collaborative chat applications sockets", "Aggregating multiple database queries into one query"],
    pricingModels: ["Query/Mutation operations volume", "Active Real-time socket connections minutes"],
    relatedServices: [{ name: "Amazon DynamoDB", slug: "amazon-dynamodb" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["graphql", "appsync", "real time sync", "resolvers", "query api"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/appsync/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1690,
    comparisonTags: ["GraphQL API", "Application Integration"]
  },
  {
    serviceCode: "mq",
    name: "Amazon MQ",
    slug: "amazon-mq",
    categorySlug: "integration",
    shortDescription: "Managed message broker service for ActiveMQ and RabbitMQ.",
    fullDescription: "Amazon MQ is a managed message broker service for Apache ActiveMQ and RabbitMQ that makes it easy to set up and operate message brokers in the cloud.",
    characteristics: ["Managed open-source brokers instances", "JMS/AMQP protocol compatibilities", "Multi-AZ broker replication availability"],
    features: ["ActiveMQ and RabbitMQ engine support", "VPC network broker isolation", "CloudWatch metric queue monitoring", "Custom broker configuration properties"],
    useCases: ["Migrating legacy ActiveMQ brokers to cloud", "Connecting microservices using AMQP routing patterns", "Decoupling Java enterprise server components"],
    pricingModels: ["Broker Node Instance Hourly rate", "Provisioned storage GB/Month"],
    relatedServices: [{ name: "Amazon SQS", slug: "amazon-sqs" }],
    keywords: ["activemq", "rabbitmq", "mq", "message broker instance", "amqp"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/amazon-mq/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1700,
    comparisonTags: ["Message Broker", "Application Integration"]
  },
  {
    serviceCode: "appfabric",
    name: "AWS AppFabric",
    slug: "aws-appfabric",
    categorySlug: "integration",
    shortDescription: "Connect SaaS applications and consolidate security logs.",
    fullDescription: "AWS AppFabric quickly connects multiple Software as a Service (SaaS) applications (like Slack, Salesforce, Zoom) to consolidate logs and optimize security alerts.",
    characteristics: ["SaaS security log consolidator", "OCSF standard data formatting", "No-code SaaS connection bridge"],
    features: ["SaaS vendor OAuth configuration wizard", "Unified security audit dashboard Console", "Security log export to S3/Security Lake", "SaaS usage optimization reports"],
    useCases: ["Aggregating Slack and Salesforce audit logs", "Monitoring unauthorized SaaS document sharing alerts", "Auditing multi-SaaS app security policies"],
    pricingModels: ["Active User connection per Month per SaaS App"],
    relatedServices: [{ name: "Amazon Security Lake", slug: "amazon-security-lake" }],
    keywords: ["appfabric", "saas logs", "slack salesforce connect", "security audit saas"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/appfabric/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1710,
    comparisonTags: ["SaaS Integration", "Security Management"]
  },
  {
    serviceCode: "mwaa",
    name: "Amazon MWAA",
    slug: "amazon-mwaa",
    categorySlug: "integration",
    shortDescription: "Managed Apache Airflow service for data pipelines.",
    fullDescription: "Amazon Managed Workflows for Apache Airflow (MWAA) is a managed orchestration service for Apache Airflow that makes it easy to setup and operate data pipelines.",
    characteristics: ["Apache Airflow DAG compatibility", "Serverless worker node autoscaling", "Integrated IAM role security bindings"],
    features: ["Airflow Web Server URL access", "Worker node scaling min/max pools", "S3 dynamic DAG parser sync", "CloudWatch database logging integrations"],
    useCases: ["Orchestrating nightly data analytics EMR pipelines", "Managing complex database extraction DAG files schedules", "Triggering pipeline operations based on S3 event logs"],
    pricingModels: ["Airflow Environment Profile Hourly", "Worker Node CPU/Memory Hour"],
    relatedServices: [{ name: "Amazon EMR", slug: "amazon-emr" }, { name: "AWS Glue", slug: "aws-glue" }],
    keywords: ["airflow", "mwaa", "dag pipeline", "data workflow scheduler"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/mwaa/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1720,
    comparisonTags: ["Workflow Orchestration", "Big Data Platform"]
  }
];
