import { SeedService } from "./seed-services-part1.js";

export const seedServicesPart2: SeedService[] = [
  // SECURITY, IDENTITY, & COMPLIANCE
  {
    serviceCode: "iam",
    name: "AWS IAM",
    slug: "aws-iam",
    categorySlug: "security",
    shortDescription: "Securely control user and service access to AWS resources.",
    fullDescription: "AWS Identity and Access Management (IAM) enables you to securely control access to AWS services and resources for your users, groups, and service profiles.",
    characteristics: ["Fine-grained access control policies", "Multi-factor authentication (MFA)", "Identity federation mappings"],
    features: ["IAM User accounts management", "Access control policies (JSON formats)", "AssumeRole security profiles", "Access Analyzer auditing"],
    useCases: ["Restricting developer server write access", "Assigning EC2 runtime instance roles", "Enforcing company corporate MFA mandates"],
    pricingModels: ["Free (Core security feature)"],
    relatedServices: [{ name: "AWS IAM Identity Center", slug: "aws-iam-identity-center" }, { name: "AWS CloudTrail", slug: "aws-cloudtrail" }],
    keywords: ["security", "iam", "permissions", "roles", "users", "access control"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/iam/",
    isFeatured: true,
    status: "GA",
    displayOrder: 640,
    comparisonTags: ["Identity Management", "Access Control"]
  },
  {
    serviceCode: "secretsmanager",
    name: "AWS Secrets Manager",
    slug: "aws-secrets-manager",
    categorySlug: "security",
    shortDescription: "Rotate, manage, and retrieve database credentials and API keys.",
    fullDescription: "AWS Secrets Manager helps you protect secrets needed to access your applications, services, and IT resources. The service enables you to easily rotate, manage, and retrieve database credentials.",
    characteristics: ["Automated secret rotations", "API-driven secure access", "KMS-backed database credential vaults"],
    features: ["RDS database auto-rotation scripts", "Random secret string generation", "IAM policy access blocks", "Cross-account secret sharing"],
    useCases: ["Storing app PostgreSQL database passwords", "Rotating third-party vendor API keys", "Securing microservices authentication tokens"],
    pricingModels: ["Secret per Month Rate", "API Operations (per 10,000 requests)"],
    relatedServices: [{ name: "AWS KMS", slug: "aws-kms" }, { name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["credentials", "secrets", "database password", "rotation", "kms secrets"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/secretsmanager/",
    isFeatured: true,
    status: "GA",
    displayOrder: 650,
    comparisonTags: ["Secrets Management", "Credential Vault"]
  },
  {
    serviceCode: "kms",
    name: "AWS KMS",
    slug: "aws-kms",
    categorySlug: "security",
    shortDescription: "Create and control cryptographic keys to encrypt data.",
    fullDescription: "AWS Key Management Service (KMS) makes it easy for you to create and manage cryptographic keys and control their use across a wide range of AWS services and in your applications.",
    characteristics: ["Hardware Security Module (HSM) backups", "FIPS 140-2 Level 3 compliance", "Seamless multi-service storage encryption integrations"],
    features: ["Customer Managed Keys (CMK) creation", "Automatic key rotation schedules", "Asymmetric and symmetric key systems", "Cryptographic decrypt operations APIs"],
    useCases: ["Encrypting S3 bucket file storage", "Signing application JWT verification keys", "Securing EBS operating system volume disks"],
    pricingModels: ["Active Key per Month Rate", "Cryptographic API Request volume"],
    relatedServices: [{ name: "AWS CloudTrail", slug: "aws-cloudtrail" }],
    keywords: ["kms", "encryption", "keys", "cryptography", "key rotation", "certificates"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/kms/",
    isFeatured: true,
    status: "GA",
    displayOrder: 660,
    comparisonTags: ["Key Management", "Data Encryption"]
  },
  {
    serviceCode: "shield",
    name: "AWS Shield",
    slug: "aws-shield",
    categorySlug: "security",
    shortDescription: "Managed DDoS protection for Route 53, CloudFront, and ELB.",
    fullDescription: "AWS Shield is a managed Distributed Denial of Service (DDoS) protection service that safeguards applications running on AWS. It provides Shield Standard and Shield Advanced tiers.",
    characteristics: ["Real-time packet inspection filters", "Automatic volumetric attack mitigation", "DDoS Response Team (DRT) access (Advanced)"],
    features: ["Shield Standard (included baseline coverage)", "Shield Advanced (financial layer protection)", "Global traffic pattern monitors", "WAF rate-limit auto-integration"],
    useCases: ["Protecting public facing CDN domains", "Securing global DNS servers queries routing", "Mitigating application layer server attacks"],
    pricingModels: ["Standard (Free)", "Advanced ($3,000/Month Fixed subscription + data charges)"],
    relatedServices: [{ name: "AWS WAF", slug: "aws-waf" }, { name: "Amazon CloudFront", slug: "amazon-cloudfront" }],
    keywords: ["ddos", "shield", "protection", "firewall ddos", "ddos prevention"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/shield/",
    isFeatured: false,
    status: "GA",
    displayOrder: 670,
    comparisonTags: ["DDoS Mitigation", "Web Protection"]
  },
  {
    serviceCode: "waf",
    name: "AWS WAF",
    slug: "aws-waf",
    categorySlug: "security",
    shortDescription: "Web Application Firewall protecting sites from exploit traffic.",
    fullDescription: "AWS WAF is a web application firewall that helps protect your web applications or APIs against common web exploits and bots that may affect availability, compromise security.",
    characteristics: ["Flexible custom firewall rules", "Real-time traffic inspect rules", "Managed ruleset community packages"],
    features: ["IP address blacklist/whitelist matching", "SQL injection detection parameters", "Cross-Site Scripting (XSS) blockers", "Bot Control managed rule filters"],
    useCases: ["Blocking malicious crawler bots from sites", "Preventing SQL injection on API endpoints", "Rate-limiting login brute force attempts"],
    pricingModels: ["Web ACL Monthly fee", "Firewall Rule configuration Monthly rate", "Web request volume inspected"],
    relatedServices: [{ name: "Amazon CloudFront", slug: "amazon-cloudfront" }, { name: "Amazon API Gateway", slug: "amazon-api-gateway" }],
    keywords: ["firewall", "waf", "web application firewall", "security rules", "exploit blocking"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/waf/",
    isFeatured: true,
    status: "GA",
    displayOrder: 680,
    comparisonTags: ["Web Application Firewall", "Web Protection"]
  },
  {
    serviceCode: "guardduty",
    name: "Amazon GuardDuty",
    slug: "amazon-guardduty",
    categorySlug: "security",
    shortDescription: "Intelligent threat detection monitoring account activity.",
    fullDescription: "Amazon GuardDuty is a threat detection service that continuously monitors for malicious activity and unauthorized behavior to protect your AWS accounts, workloads, and data stored in Amazon S3.",
    characteristics: ["Machine Learning anomaly detectors", "Zero agent software requirements", "Continuous background analysis logs"],
    features: ["VPC Flow Logs analytics scans", "DNS query threat detections", "CloudTrail API audit trackers", "Malware scan triggers on volume mounts"],
    useCases: ["Detecting compromised host Bitcoin miners", "Monitoring backend account API key theft", "Identifying unusual data access from S3"],
    pricingModels: ["Logs volume analyzed per Month (CloudTrail/DNS/Flow Logs)"],
    relatedServices: [{ name: "AWS Security Hub", slug: "aws-security-hub" }, { name: "AWS CloudTrail", slug: "aws-cloudtrail" }],
    keywords: ["threat detection", "guardduty", "anomaly detection", "security scanner"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/guardduty/",
    isFeatured: false,
    status: "GA",
    displayOrder: 690,
    comparisonTags: ["Threat Detection", "Security Audit"]
  },
  {
    serviceCode: "inspector",
    name: "Amazon Inspector",
    slug: "amazon-inspector",
    categorySlug: "security",
    shortDescription: "Automated vulnerability scanner for EC2 and ECR.",
    fullDescription: "Amazon Inspector is an automated vulnerability management service that continually scans AWS workloads for software vulnerabilities and unintended network exposure.",
    characteristics: ["Continuous automated package scanning", "CVSS score threat evaluations", "Container and VM layer scanning"],
    features: ["EC2 software package scans", "ECR docker container registry scans", "Lambda function code vulnerability scans", "Systems Manager connection agent support"],
    useCases: ["Finding outdated OpenSSL software on VMs", "Scanning container images in build pipelines", "Auditing EC2 public port exposures"],
    pricingModels: ["Per EC2 Instance scanned", "Per Container Image scanned", "Per Lambda Function scanned"],
    relatedServices: [{ name: "AWS Systems Manager", slug: "aws-systems-manager" }, { name: "Amazon ECR", slug: "amazon-ecr" }],
    keywords: ["vulnerability", "scanner", "security audit", "inspector", "cve scan"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/inspector/",
    isFeatured: false,
    status: "GA",
    displayOrder: 700,
    comparisonTags: ["Vulnerability Scanner", "Security Audit"]
  },
  {
    serviceCode: "macie",
    name: "Amazon Macie",
    slug: "amazon-macie",
    categorySlug: "security",
    shortDescription: "Discover and secure sensitive data like PII in S3 buckets.",
    fullDescription: "Amazon Macie is a fully managed data security and data privacy service that uses machine learning and pattern matching to discover and protect sensitive data in AWS.",
    characteristics: ["Pattern matching text classifiers", "PII/Credit Card sensitive detection rules", "Continuous automated bucket audits"],
    features: ["Regex custom criteria matching", "S3 bucket access policy reports", "Interactive sensitive finding alerts", "CloudWatch Events notifications outputs"],
    useCases: ["Auditing S3 databases for exposed user PII", "Checking compliance files for unencrypted credit cards", "Reporting S3 public file exposures"],
    pricingModels: ["Per S3 Bucket evaluated", "Gigabytes of S3 text scanned"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["pii", "macie", "data privacy", "credit card finder", "sensitive scanner"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/macie/",
    isFeatured: false,
    status: "GA",
    displayOrder: 710,
    comparisonTags: ["Data Privacy", "Vulnerability Scanner"]
  },
  {
    serviceCode: "securityhub",
    name: "AWS Security Hub",
    slug: "aws-security-hub",
    categorySlug: "security",
    shortDescription: "Unified posture center compiling security checks.",
    fullDescription: "AWS Security Hub is a cloud security posture management service that performs security best practice checks, aggregates alerts, and enables automated remediation.",
    characteristics: ["Unified cross-account single pane", "Pre-built compliance standards dashboards", "Finding aggregation endpoints"],
    features: ["CIS benchmarks security checks", "PCI-DSS database checks alignment", "GuardDuty/Inspector finding consolidator", "AWS Config rule compliance engine"],
    useCases: ["Aggregating corporate cloud security audits", "Enforcing uniform developer CIS policy rules", "Creating automated security finding reports"],
    pricingModels: ["Checks executed volume", "Security findings ingested volume"],
    relatedServices: [{ name: "AWS Config", slug: "aws-config" }],
    keywords: ["security hub", "compliance", "posture management", "best practices", "cis benchmark"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/securityhub/",
    isFeatured: false,
    status: "GA",
    displayOrder: 720,
    comparisonTags: ["Security Posture Management", "Compliance Audit"]
  },
  {
    serviceCode: "identitycenter",
    name: "AWS IAM Identity Center",
    slug: "aws-iam-identity-center",
    categorySlug: "security",
    shortDescription: "Single sign-on access to AWS accounts and cloud apps.",
    fullDescription: "AWS IAM Identity Center (successor to AWS Single Sign-On) helps you securely build, configure, and assign single sign-on access to all of your AWS accounts and cloud apps.",
    characteristics: ["Central employee credentials portal", "SAML 2.0 app integration support", "Identity source directory syncs"],
    features: ["Active Directory connector linkages", "Permission Sets account assignments", "Multi-account access console lists", "Okta/Azure AD user synchronizer"],
    useCases: ["Providing employees single-portal login access", "Configuring developer console session lengths", "Linking Okta login directories to AWS accounts"],
    pricingModels: ["Free (Core account management feature)"],
    relatedServices: [{ name: "AWS IAM", slug: "aws-iam" }],
    keywords: ["sso", "single sign on", "identity center", "directory sync", "saml login"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/singlesignon/",
    isFeatured: false,
    status: "GA",
    displayOrder: 730,
    comparisonTags: ["Identity Management", "Access Control"]
  },
  {
    serviceCode: "directoryservice",
    name: "AWS Directory Service",
    slug: "aws-directory-service",
    categorySlug: "security",
    shortDescription: "Managed Active Directory in the AWS Cloud.",
    fullDescription: "AWS Directory Service enables your directory-aware workloads and resources to use managed Active Directory in the AWS Cloud, integrating corporate directories.",
    characteristics: ["Native Windows Active Directory engine", "Managed AD controller instances", "Trust relationship integrations"],
    features: ["Microsoft AD domain controller operations", "AD connector bridge setups", "Group Policy Object (GPO) support", "Single sign-on credentials link"],
    useCases: ["Running Microsoft AD dependent ERP databases", "Joining Windows EC2 instances to AD domains", "Federating corporate client logins into AWS console"],
    pricingModels: ["Active AD Controller Instance Hour"],
    relatedServices: [{ name: "AWS IAM Identity Center", slug: "aws-iam-identity-center" }],
    keywords: ["active directory", "ad connector", "microsoft ad", "domain controller"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/directoryservice/",
    isFeatured: false,
    status: "GA",
    displayOrder: 740,
    comparisonTags: ["Directory Service", "Identity Management"]
  },
  {
    serviceCode: "acm",
    name: "AWS Certificate Manager",
    slug: "aws-certificate-manager",
    categorySlug: "security",
    shortDescription: "Provision, manage, and deploy public/private SSL certificates.",
    fullDescription: "AWS Certificate Manager (ACM) handles the complexity of creating, storing, and renewing public/private Secure Socket Layer (SSL/TLS) certificates for AWS deployments.",
    characteristics: ["Automated certificate renewals", "Immediate deployment to CloudFront/ELB", "Validated domain registry links"],
    features: ["DNS and Email domain validation", "Free public SSL certificates", "ACM Private CA certificate links", "Auto-renewal triggers before expiry"],
    useCases: ["Enabling HTTPS on application Load Balancers", "Securing API Gateway custom domains", "Managing corporate domain SSL rotation logs"],
    pricingModels: ["Public Certificates (Free)", "Private CA Certificates (Per CA per Month + Certificate Fee)"],
    relatedServices: [{ name: "Amazon CloudFront", slug: "amazon-cloudfront" }, { name: "Elastic Load Balancing", slug: "elastic-load-balancing" }],
    keywords: ["ssl", "tls", "certificate", "https", "ssl renewal", "acm"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/acm/",
    isFeatured: true,
    status: "GA",
    displayOrder: 750,
    comparisonTags: ["Certificate Authority", "Web Protection"]
  },
  {
    serviceCode: "firewallmanager",
    name: "AWS Firewall Manager",
    slug: "aws-firewall-manager",
    categorySlug: "security",
    shortDescription: "Central security policy configuration across AWS accounts.",
    fullDescription: "AWS Firewall Manager simplifies your WAF, Shield, Network Firewall, and Security Group rules configuration and management tasks across accounts in AWS Organizations.",
    characteristics: ["Organizations-wide policy enforcement", "Automated compliance auditing", "Centralized security setups"],
    features: ["WAF rule policy propagation", "Shield Advanced dynamic attachments", "Security Group rule auditing scopes", "Network Firewall rule replication"],
    useCases: ["Enforcing uniform WAF rules on all web servers", "Ensuring Shield Advanced protects new public routes", "Detecting unauthorized Security Group port openings"],
    pricingModels: ["Active Security Policy per Month per Region", "Pay for underlying WAF/Shield resources"],
    relatedServices: [{ name: "AWS Organizations", slug: "aws-organizations" }, { name: "AWS WAF", slug: "aws-waf" }],
    keywords: ["firewall manager", "central security", "firewall rules policy", "security audit"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/firewall-manager/",
    isFeatured: false,
    status: "GA",
    displayOrder: 760,
    comparisonTags: ["Security Management", "Compliance Audit"]
  },
  {
    serviceCode: "cloudtrail",
    name: "AWS CloudTrail",
    slug: "aws-cloudtrail",
    categorySlug: "security",
    shortDescription: "Log and audit all AWS API activities and console actions.",
    fullDescription: "AWS CloudTrail records, continuously monitors, and retains account activity related to actions across your AWS infrastructure, providing a complete API audit log trail.",
    characteristics: ["Continuous account API audit logging", "WORM immutable data archive options", "Multi-account single aggregate logs"],
    features: ["API caller identification tracks", "S3 data event detailed logs", "CloudTrail Lake database queries", "Log integrity cryptographic validations"],
    useCases: ["Investigating root cause resource deletions", "Auditing database access compliance reports", "Tracking console logins activity logs"],
    pricingModels: ["First Trail (Free)", "Management Event logging (per 100,000 events)", "Data Event logging per GB"],
    relatedServices: [{ name: "Amazon CloudWatch", slug: "amazon-cloudwatch" }, { name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["audit", "logs", "cloudtrail", "api history", "security log", "compliance tracking"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cloudtrail/",
    isFeatured: true,
    status: "GA",
    displayOrder: 770,
    comparisonTags: ["Security Audit", "API Logging"]
  },
  {
    serviceCode: "artifact",
    name: "AWS Artifact",
    slug: "aws-artifact",
    categorySlug: "security",
    shortDescription: "On-demand portal for AWS compliance reports.",
    fullDescription: "AWS Artifact is your go-to central resource for compliance-related information. It provides on-demand access to AWS's compliance reports and select online agreements.",
    characteristics: ["Self-service audit report downloader", "Official certification records access", "AWS agreements digital signatures console"],
    features: ["ISO/SOC compliance report downloads", "HIPAA Business Associate Addendum (BAA) signing", "Nondisclosure Agreements (NDA) management", "PCI compliance package downloads"],
    useCases: ["Downloading SOC2 reports for corporate auditors", "Signing legal HIPAA compliance agreements with AWS", "Reviewing AWS ISO certification certificates"],
    pricingModels: ["Free (Compliance utility platform)"],
    relatedServices: [{ name: "AWS IAM", slug: "aws-iam" }],
    keywords: ["compliance reports", "soc2 download", "iso certification", "legal agreements", "artifact"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/artifact/",
    isFeatured: false,
    status: "GA",
    displayOrder: 780,
    comparisonTags: ["Compliance Registry", "Legal Agreements"]
  },
  {
    serviceCode: "auditmanager",
    name: "AWS Audit Manager",
    slug: "aws-audit-manager",
    categorySlug: "security",
    shortDescription: "Continuously audit your AWS usage to simplify compliance assessment.",
    fullDescription: "AWS Audit Manager helps you continuously audit your AWS usage to simplify how you assess risk and compliance with regulations and industry standards.",
    characteristics: ["Automated evidence gathering pipelines", "Pre-built regulation compliance frameworks", "Audit document compiler"],
    features: ["Config compliance evidence logs aggregation", "System configuration snapshot logs", "User activity audit recordings", "Audit report PDF exports"],
    useCases: ["Preparing for standard HIPAA compliance audits", "Aggregating configuration compliance evidence sheets", "Tracking user IAM permissions compliance logs"],
    pricingModels: ["Evidence collected volume per Month"],
    relatedServices: [{ name: "AWS Config", slug: "aws-config" }, { name: "AWS CloudTrail", slug: "aws-cloudtrail" }],
    keywords: ["audit manager", "compliance evidence", "compliance reports", "framework audit"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/audit-manager/",
    isFeatured: false,
    status: "GA",
    displayOrder: 790,
    comparisonTags: ["Compliance Audit", "Postural Security"]
  },
  {
    serviceCode: "cognito",
    name: "Amazon Cognito",
    slug: "amazon-cognito",
    categorySlug: "security",
    shortDescription: "Customer identity sign-in and user pool directory manager.",
    fullDescription: "Amazon Cognito lets you add user sign-up, sign-in, and access control to your web and mobile apps quickly and easily, scaling to millions of active users.",
    characteristics: ["Self-service user login portals", "SAML/OIDC identity providers linkage", "OAuth 2.0 endpoint generations"],
    features: ["User Pools (user directory databases)", "Identity Pools (temporary IAM token dispensers)", "Social logins (Google/Facebook/Apple)", "Multi-Factor Authentication (MFA) SMS scripts"],
    useCases: ["Managing SaaS application user accounts", "Enabling user login via Google/Apple credentials", "Granting authenticated users secure write access to S3"],
    pricingModels: ["Monthly Active Users (MAU) volume tiers (First 50,000 MAU Free)"],
    relatedServices: [{ name: "AWS IAM", slug: "aws-iam" }, { name: "Amazon SES", slug: "amazon-ses" }],
    keywords: ["identity pool", "user directory", "social login", "oauth", "cognito", "authentication"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/cognito/",
    isFeatured: true,
    status: "GA",
    displayOrder: 800,
    comparisonTags: ["Identity Directory", "Access Control"]
  },
  {
    serviceCode: "privateca",
    name: "AWS Private CA",
    slug: "aws-private-ca",
    categorySlug: "security",
    shortDescription: "Deploy private root and subordinate certificate authorities.",
    fullDescription: "AWS Private Certificate Authority (AWS Private CA) is a secure, managed private CA service that helps you securely manage certificates for your internal resources, connected devices, and users.",
    characteristics: ["Managed hardware private CAs", "Strict isolation policies", "Custom enterprise domain naming"],
    features: ["Root CA and Subordinate CA creation", "Online certificate signing operations APIs", "CRL (Certificate Revocation List) registries", "IAM authorization scopes"],
    useCases: ["Deploying SSL keys to factory IoT sensors", "Securing internal server-to-server networks", "Managing internal company VPN identity keys"],
    pricingModels: ["Active Private CA Monthly fee", "Certificates issued volume"],
    relatedServices: [{ name: "AWS Certificate Manager", slug: "aws-certificate-manager" }],
    keywords: ["private ca", "ca vault", "subordinate ca", "private ssl"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/privateca/",
    isFeatured: false,
    status: "GA",
    displayOrder: 810,
    comparisonTags: ["Certificate Authority", "Security Management"]
  },
  {
    serviceCode: "securitylake",
    name: "Amazon Security Lake",
    slug: "amazon-security-lake",
    categorySlug: "security",
    shortDescription: "Automatically centralize security data into a data lake.",
    fullDescription: "Amazon Security Lake automatically centralizes security data from cloud, on-premises, and custom sources into a purpose-built data lake stored in your AWS account.",
    characteristics: ["OCSF open standard format parsing", "Automated log pipelines", "Centralized security database access"],
    features: ["CloudTrail/VPC Flow logs ingestion auto-links", "Data consolidation query endpoints", "Storage lifecycle optimization tools", "S3 data lake configuration layers"],
    useCases: ["Consolidating multi-account security logs", "Creating SIEM analytics pipelines", "Querying security events with Amazon Athena"],
    pricingModels: ["Data volume ingested per GB", "Prisma/Athena query costs"],
    relatedServices: [{ name: "Amazon Athena", slug: "amazon-athena" }, { name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["security lake", "log lake", "ocsf log", "siem lake"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/security-lake/",
    isFeatured: false,
    status: "GA",
    displayOrder: 820,
    comparisonTags: ["Data Lake", "Security Management"]
  },
  {
    serviceCode: "detective",
    name: "Amazon Detective",
    slug: "amazon-detective",
    categorySlug: "security",
    shortDescription: "Investigate and analyze the root cause of security findings.",
    fullDescription: "Amazon Detective makes it easy to analyze, investigate, and quickly identify the root cause of potential security issues or suspicious activities using graph data models.",
    characteristics: ["Automated graph dependency maps", "Logs correlation dashboards", "Visual attack sequence paths"],
    features: ["VPC Flow logs visual correlates", "GuardDuty alert linkages", "IAM relationship threat profiles", "CloudTrail API call sequences visualization"],
    useCases: ["Investigating root cause of a server malware alert", "Tracking API key misuse timelines", "Mapping network connections of compromised hosts"],
    pricingModels: ["Data volume ingested from GuardDuty/CloudTrail per GB"],
    relatedServices: [{ name: "Amazon GuardDuty", slug: "amazon-guardduty" }, { name: "AWS Security Hub", slug: "aws-security-hub" }],
    keywords: ["detective", "investigation", "root cause security", "attack graph"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/detective/",
    isFeatured: false,
    status: "GA",
    displayOrder: 830,
    comparisonTags: ["Threat Investigation", "Security Audit"]
  },
  {
    serviceCode: "accessanalyzer",
    name: "IAM Access Analyzer",
    slug: "iam-access-analyzer",
    categorySlug: "security",
    shortDescription: "Identify public or cross-account resource exposures.",
    fullDescription: "IAM Access Analyzer helps you identify resources in your organization and accounts that are shared with an external entity, verifying secure policies.",
    characteristics: ["Mathematical logic policy verification", "Automated scan updates", "Access pattern validations"],
    features: ["Policy validation warnings", "S3 bucket exposure checks", "KMS/IAM policy audits", "Access simulation parameters"],
    useCases: ["Checking if an S3 bucket is publicly writable", "Validating custom IAM policies for syntax errors", "Auditing cross-account KMS key access rights"],
    pricingModels: ["Free (Included in AWS IAM Console)"],
    relatedServices: [{ name: "AWS IAM", slug: "aws-iam" }],
    keywords: ["access analyzer", "policy check", "public bucket", "exposure check"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 840,
    comparisonTags: ["Policy Validator", "Security Audit"]
  },
  {
    serviceCode: "rolesanywhere",
    name: "IAM Roles Anywhere",
    slug: "iam-roles-anywhere",
    categorySlug: "security",
    shortDescription: "Obtain temporary AWS IAM roles for on-premises servers.",
    fullDescription: "IAM Roles Anywhere allows workloads running outside of AWS (like on-premises servers or containers) to obtain temporary IAM role credentials using local X.509 certificates.",
    characteristics: ["On-prem credentials token dispenser", "Cryptographic trust anchors links", "Eliminates hardcoded access keys"],
    features: ["X.509 certificate validation anchor", "STS (Security Token Service) integration", "Profile permission scoping policies", "Console audit logs tracking"],
    useCases: ["Granting on-prem backup servers rights to write S3", "Securing local database migration pipeline connections", "Eliminates static IAM access keys in corporate scripts"],
    pricingModels: ["Free (Core IAM access utility)"],
    relatedServices: [{ name: "AWS IAM", slug: "aws-iam" }],
    keywords: ["roles anywhere", "on-prem credentials", "sts keys", "certificates access"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/rolesanywhere/",
    isFeatured: false,
    status: "GA",
    displayOrder: 850,
    comparisonTags: ["Access Control", "Identity Management"]
  },
  {
    serviceCode: "signer",
    name: "AWS Signer",
    slug: "aws-signer",
    categorySlug: "security",
    shortDescription: "Fully managed code-signing service ensuring authenticity.",
    fullDescription: "AWS Signer is a fully managed code-signing service to sign code packages, ensuring their authenticity and integrity against unauthorized changes.",
    characteristics: ["Digital signature generations", "Central certificate authority integrations", "Automated validation pipelines"],
    features: ["Lambda code sign validations", "Container image signature profiles", "Signature expiration rules", "IAM role execution controls"],
    useCases: ["Signing serverless application deployment code", "Enforcing container signature checks on EKS", "Verifying deploy integrity parameters in CI/CD"],
    pricingModels: ["Free (Pay for generated KMS keys used)"],
    relatedServices: [{ name: "AWS KMS", slug: "aws-kms" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["signer", "code signing", "deploy signature", "integrity check"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/signer/",
    isFeatured: false,
    status: "GA",
    displayOrder: 860,
    comparisonTags: ["Code Signing", "Data Protection"]
  },
  {
    serviceCode: "paymentcryptography",
    name: "AWS Payment Cryptography",
    slug: "aws-payment-cryptography",
    categorySlug: "security",
    shortDescription: "Elastic cloud-based cryptography service for retail payments.",
    fullDescription: "AWS Payment Cryptography simplifies key management and cryptographic operations for retail payment processing, replacing specialized on-premises payment HSMs.",
    characteristics: ["Payment card industry compliance", "Hardware payment security modules", "High transactional throughput limits"],
    features: ["PIN generation and validation APIs", "EMV transaction cryptogram checks", "FIPS 140-2 payment keys storage", "PCI-PIN/PCI-3DS standards audit logs"],
    useCases: ["Validating point-of-sale retail credit cards", "Decrypting PIN blocks on cloud servers", "Securing digital card credentials generation"],
    pricingModels: ["Active Payment Key per Month", "Payment Cryptographic API operations count"],
    relatedServices: [{ name: "AWS KMS", slug: "aws-kms" }],
    keywords: ["payment crypto", "hsm payment", "credit card pin", "pci pin compliance"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/payment-cryptography/",
    isFeatured: false,
    status: "GA",
    displayOrder: 870,
    comparisonTags: ["Key Management", "Payment Cryptography"]
  },

  // ANALYTICS
  {
    serviceCode: "athena",
    name: "Amazon Athena",
    slug: "amazon-athena",
    categorySlug: "analytics",
    shortDescription: "Serverless SQL query engine analyzing S3 files.",
    fullDescription: "Amazon Athena is an interactive query service that makes it easy to analyze data in Amazon S3 using standard SQL. Athena is serverless, so there is no infrastructure to manage.",
    characteristics: ["Fully serverless ad-hoc query engine", "Queries data directly in S3", "Pay-as-you-go scanned data billing"],
    features: ["Standard ANSI SQL query engine", "AWS Glue Data Catalog schemas integration", "Multiple file format parser (CSV/JSON/Parquet)", "Federated database query connectors"],
    useCases: ["Querying CloudTrail security log archives", "Ad-hoc SQL analytics on CSV files in S3", "Analyzing data lake files without databases"],
    pricingModels: ["Data Scanned per Query ($5.00/TB scanned)"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "AWS Glue", slug: "aws-glue" }],
    keywords: ["query", "sql S3", "serverless sql", "analytics", "athena"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/athena/",
    isFeatured: true,
    status: "GA",
    displayOrder: 880,
    comparisonTags: ["SQL Query Engine", "Analytics Engine", "Serverless Analytics"]
  },
  {
    serviceCode: "emr",
    name: "Amazon EMR",
    slug: "amazon-emr",
    categorySlug: "analytics",
    shortDescription: "Hadoop, Spark, and big data processing cluster manager.",
    fullDescription: "Amazon EMR (Elastic MapReduce) is a industry-leading cloud big data platform for processing vast amounts of data using open-source tools such as Apache Spark, Hadoop, and Presto.",
    characteristics: ["Scalable big data clusters orchestration", "Supports open source analytics frameworks", "Flexible instance configuration pools"],
    features: ["Managed Spark/Hadoop installs", "Auto Scaling node groups", "EMR notebooks workspace dashboards", "S3 filesystem integration (EMRFS)"],
    useCases: ["Large-scale data transformation (ETL) processing", "Scientific computations big data models runs", "Hadoop application cloud migration"],
    pricingModels: ["EMR software fee per Node Hour", "Pay for EC2/Fargate compute nodes"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon EC2", slug: "amazon-ec2" }],
    keywords: ["hadoop", "spark", "big data", "etl", "mapreduce", "emr"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/emr/",
    isFeatured: true,
    status: "GA",
    displayOrder: 890,
    comparisonTags: ["Big Data Platform", "HPC Processing"]
  },
  {
    serviceCode: "redshift",
    name: "Amazon Redshift",
    slug: "amazon-redshift",
    categorySlug: "analytics",
    shortDescription: "Fast, simple, cost-effective enterprise cloud data warehouse.",
    fullDescription: "Amazon Redshift is a fully managed, petabyte-scale data warehouse service in the cloud. It allows you to analyze your data using your existing business intelligence tools.",
    characteristics: ["Columnar storage database engine", "Massively Parallel Processing (MPP) architecture", "High scale enterprise query executions"],
    features: ["Redshift Serverless dynamic queries scaling", "Redshift Spectrum query-in-place on S3", "Materialized views optimization", "Concurrency scaling query queues"],
    useCases: ["Enterprise BI dashboard data warehousing", "Aggregated company sales analytics dashboards", "Long term historical database storage analytical centers"],
    pricingModels: ["Redshift Compute Node Hourly", "Redshift Managed Storage GB/Month", "Serverless Redshift Processing Units (RPU)"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "AWS Glue", slug: "aws-glue" }],
    keywords: ["data warehouse", "redshift", "bi analytics", "olap db", "spectrum"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/redshift/",
    isFeatured: true,
    status: "GA",
    displayOrder: 900,
    comparisonTags: ["Data Warehouse", "Analytics Engine"]
  },
  {
    serviceCode: "kinesisstreams",
    name: "Amazon Kinesis Data Streams",
    slug: "amazon-kinesis-data-streams",
    categorySlug: "analytics",
    shortDescription: "Real-time high-throughput streaming data ingestion service.",
    fullDescription: "Amazon Kinesis Data Streams is a mass-scalable and durable real-time data streaming service that can continuously capture gigabytes of data per second from sources.",
    characteristics: ["Micro-second streaming record delivery", "Partition shard scaling capabilities", "Continuous durable buffer logs"],
    features: ["On-demand shard autoscale scaling", "Kinesis Client Library (KCL) integrations", "KMS server-side record encryption", "Data retention setting configs"],
    useCases: ["Real-time application metrics log streams", "E-commerce user clickstream analytics pipelines", "High-frequency financial ticker ingestion grids"],
    pricingModels: ["Shard Hour deployment cost", "PUT Payload Units volume (per million)"],
    relatedServices: [{ name: "Amazon Kinesis Data Firehose", slug: "amazon-kinesis-data-firehose" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["kinesis", "streaming data", "ingest log", "clickstream", "real time streams"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/streams/",
    isFeatured: true,
    status: "GA",
    displayOrder: 910,
    comparisonTags: ["Data Streaming", "Ingestion Ingest"]
  },
  {
    serviceCode: "kinesisfirehose",
    name: "Amazon Kinesis Data Firehose",
    slug: "amazon-kinesis-data-firehose",
    categorySlug: "analytics",
    shortDescription: "Load real-time streaming data directly into storage targets.",
    fullDescription: "Amazon Kinesis Data Firehose is the easiest way to reliably load streaming data into data stores and analytics tools, supporting direct S3, Redshift, and OpenSearch delivery.",
    characteristics: ["Automated target delivery pipelines", "Zero administration scaling structures", "Inline stream formatting converters"],
    features: ["Dynamic record decompression (Parquet/ORC)", "Delivery targets (S3, Redshift, Splunk, Datadog)", "Lambda inline transformation triggers", "Buffer settings configurations (Timeline/Size)"],
    useCases: ["Dumping server metric logs directly to S3 data lakes", "Ingesting IoT data streams into Redshift warehouses", "Streaming system logs directly to OpenSearch search servers"],
    pricingModels: ["Data Volume processed per GB Ingested"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon Redshift", slug: "amazon-redshift" }],
    keywords: ["firehose", "kinesis delivery", "load database", "s3 delivery", "stream dump"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/firehose/",
    isFeatured: false,
    status: "GA",
    displayOrder: 920,
    comparisonTags: ["Data Streaming", "ETL Tool"]
  },
  {
    serviceCode: "kinesisanalytics",
    name: "Amazon Kinesis Data Analytics",
    slug: "amazon-kinesis-data-analytics",
    categorySlug: "analytics",
    shortDescription: "Process and analyze streaming data with SQL or Flink.",
    fullDescription: "Amazon Kinesis Data Analytics enables you to process and analyze streaming data in real-time using SQL or Apache Flink without managing servers.",
    characteristics: ["Real-time event processing engine", "Supports standard SQL and Flink APIs", "Fully serverless streaming analytics"],
    features: ["Apache Flink application integrations", "SQL window query syntax support", "Schema auto discovery tools", "CloudWatch metrics alerts generation"],
    useCases: ["Computing rolling-average sensor metrics", "Generating anomaly alerts on active log streams", "Real-time scoreboard generation"],
    pricingModels: ["Kinesis Processing Unit (KPU) Hour"],
    relatedServices: [{ name: "Amazon Kinesis Data Streams", slug: "amazon-kinesis-data-streams" }],
    keywords: ["flink", "kinesis analytics", "stream sql", "real time analytics"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/kinesisanalytics/",
    isFeatured: false,
    status: "GA",
    displayOrder: 930,
    comparisonTags: ["Data Streaming", "Analytics Engine"]
  },
  {
    serviceCode: "opensearch",
    name: "Amazon OpenSearch Service",
    slug: "amazon-opensearch-service",
    categorySlug: "analytics",
    shortDescription: "Managed search, audit, and log analytics engines platform.",
    fullDescription: "Amazon OpenSearch Service (successor to Amazon Elasticsearch Service) makes it easy to deploy, secure, operate, and scale OpenSearch and Elasticsearch clusters in the cloud.",
    characteristics: ["High-speed full text indexing database", "Managed indexing search controllers", "Open Kibana/OpenSearch dashboards integrated"],
    features: ["VPC network cluster isolation", "UltraWarm storage tier allocations", "Cognito SSO dashboard authorization", "KMS indexing disk encrypt"],
    useCases: ["Application full-text keyword search index", "Log analytics monitoring dashboards (ELK)", "Security information event audits logging (SIEM)"],
    pricingModels: ["OpenSearch Instance Hourly rate", "Storage consumed GB/Month"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon Kinesis Data Firehose", slug: "amazon-kinesis-data-firehose" }],
    keywords: ["elasticsearch", "opensearch", "kibana", "elk log", "search engine", "indexing"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/opensearch-service/",
    isFeatured: true,
    status: "GA",
    displayOrder: 940,
    comparisonTags: ["Search Engine", "Log Analytics", "NoSQL Database"]
  },
  {
    serviceCode: "quicksight",
    name: "Amazon QuickSight",
    slug: "amazon-quicksight",
    categorySlug: "analytics",
    shortDescription: "Fast, cloud-powered business intelligence (BI) service.",
    fullDescription: "Amazon QuickSight is a fast, cloud-powered business intelligence service that makes it easy to deliver insights to everyone in your organization, featuring rich dashboard interfaces.",
    characteristics: ["Super-fast Parallel In-memory Calculation Engine (SPICE)", "Natural language questions (QuickSight Q)", "Easy sharing and dashboard embedding"],
    features: ["Interactive chart widgets creation", "Direct database connections (RDS, Redshift, Athena)", "Row-level data authorization rules", "Automated email report schedules"],
    useCases: ["Corporate sales metric business dashboards", "Embedding BI charts into custom client portals", "Analyzing Athena query database outputs visually"],
    pricingModels: ["Active Dashboard Author User Monthly Fee", "Active Reader Session blocks"],
    relatedServices: [{ name: "Amazon Athena", slug: "amazon-athena" }, { name: "Amazon Redshift", slug: "amazon-redshift" }],
    keywords: ["bi", "quicksight", "dashboards", "visualization", "business intelligence", "reports"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/quicksight/",
    isFeatured: true,
    status: "GA",
    displayOrder: 950,
    comparisonTags: ["Business Intelligence", "Visualization"]
  },
  {
    serviceCode: "glue",
    name: "AWS Glue",
    slug: "aws-glue",
    categorySlug: "analytics",
    shortDescription: "Simple, serverless data integration and ETL service.",
    fullDescription: "AWS Glue is a serverless data integration service that makes it easy to discover, prepare, and combine data for analytics, machine learning, and application development.",
    characteristics: ["Fully serverless ETL job pipelines", "Automated database schema metadata discovery", "Unified data integration console"],
    features: ["Glue Schema Crawlers database cataloging", "Spark code generator scripts (Python/Scala)", "Glue Studio visual job interface", "Glue Data Catalog central metadata database"],
    useCases: ["Running nightly DB database migration scripts", "Discovering S3 CSV file schemas automatically", "Maintaining a central data catalog for Athena queries"],
    pricingModels: ["Data Processing Unit (DPU) Hourly execution rate", "Data Catalog metadata storage"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon Athena", slug: "amazon-athena" }],
    keywords: ["etl", "glue", "crawler", "data catalog", "schema", "transform data"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/glue/",
    isFeatured: true,
    status: "GA",
    displayOrder: 960,
    comparisonTags: ["ETL Tool", "Data Registry"]
  },
  {
    serviceCode: "lakeformation",
    name: "AWS Lake Formation",
    slug: "aws-lake-formation",
    categorySlug: "analytics",
    shortDescription: "Build, secure, and manage data lakes easily.",
    fullDescription: "AWS Lake Formation is a service that makes it easy to set up a secure data lake in days. A data lake is a centralized, curated, and secured repository that stores all your data.",
    characteristics: ["Centralized data lake security policies", "Cell-level data permission controls", "Accelerated data lake setup utilities"],
    features: ["AWS Glue Data Catalog permissions linkage", "Row and column-level access controls", "Data ingestion blueprint templates", "Centralized security audit dashboards"],
    useCases: ["Restricting BI user query fields in Athena", "Setting up a secure enterprise S3 data lake", "Enforcing uniform data lake access controls policies"],
    pricingModels: ["No extra charge (pay for underlying Glue / Athena / S3 resources)"],
    relatedServices: [{ name: "AWS Glue", slug: "aws-glue" }, { name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["data lake", "lake formation", "permissions", "curated lake"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/lake-formation/",
    isFeatured: false,
    status: "GA",
    displayOrder: 970,
    comparisonTags: ["Data Lake Management", "Access Control"]
  },
  {
    serviceCode: "msk",
    name: "Amazon MSK",
    slug: "amazon-msk",
    categorySlug: "analytics",
    shortDescription: "Managed Apache Kafka streaming service clusters.",
    fullDescription: "Amazon Managed Streaming for Apache Kafka (Amazon MSK) is a fully managed service that makes it easy for you to build and run applications that use Apache Kafka to process streaming data.",
    characteristics: ["Upstream Apache Kafka compatibility", "Managed ZooKeeper/Kraft control infrastructure", "Highly available multi-AZ broker nodes"],
    features: ["MSK Serverless auto-scaling configuration", "Broker node instance class options", "IAM client authentication rules", "KMS-backed broker network encryption"],
    useCases: ["Running Apache Kafka pipelines without infrastructure setups", "Migrating local Kafka clusters to AWS", "High throughput event-driven system backbone integration"],
    pricingModels: ["Broker Node Instance Hourly rate", "Storage consumed per GB/Month", "Serverless MSK partition unit hour"],
    relatedServices: [{ name: "Amazon VPC", slug: "amazon-vpc" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["kafka", "msk", "managed kafka", "event streams", "message broker"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/msk/",
    isFeatured: false,
    status: "GA",
    displayOrder: 980,
    comparisonTags: ["Data Streaming", "Message Broker"]
  },
  {
    serviceCode: "dataexchange",
    name: "AWS Data Exchange",
    slug: "aws-data-exchange",
    categorySlug: "analytics",
    shortDescription: "Find, subscribe to, and use third-party data in the cloud.",
    fullDescription: "AWS Data Exchange makes it easy to find, subscribe to, and use third-party data in the cloud. It features thousands of data products from certified data providers.",
    characteristics: ["Unified data market portal", "Automated data revision deliveries", "AWS native API formats integrations"],
    features: ["S3 direct data copy subscriptions", "Redshift data sharing connections integration", "API Gateway data product endpoints", "Centralized subscription invoice billing"],
    useCases: ["Subscribing to global weather history databases", "Ingesting third-party financial market data feeds", "Publishing proprietary corporate data products"],
    pricingModels: ["Subscription pricing set by Data Provider", "AWS marketplace transactional fees"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["data exchange", "market", "third party data", "data feed"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/data-exchange/",
    isFeatured: false,
    status: "GA",
    displayOrder: 990,
    comparisonTags: ["Data Registry", "Marketplace"]
  },
  {
    serviceCode: "cleanrooms",
    name: "AWS Clean Rooms",
    slug: "aws-clean-rooms",
    categorySlug: "analytics",
    shortDescription: "Collaborate on datasets without sharing raw records.",
    fullDescription: "AWS Clean Rooms helps companies collaborate with their partners to analyze their collective datasets without sharing or exposing raw, underlying user information.",
    characteristics: ["Privacy-protecting SQL query environments", "Cryptographic database matching filters", "Decoupled participant database storage"],
    features: ["Cryptographic computing matches", "Differential privacy query checks", "SQL query rule analysis templates", "AWS Glue schema integrations"],
    useCases: ["Co-marketing analysis on user lists", "Cross-company medical research databases analysis", "Secure banking account transaction matches"],
    pricingModels: ["Clean Room Collaboration Hour execution rate"],
    relatedServices: [{ name: "AWS Glue", slug: "aws-glue" }],
    keywords: ["clean rooms", "privacy query", "collaboration", "secure database sql"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/clean-rooms/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1000,
    comparisonTags: ["Privacy Analytics", "SQL Query Engine"]
  },
  {
    serviceCode: "datapipeline",
    name: "AWS Data Pipeline",
    slug: "aws-data-pipeline",
    categorySlug: "analytics",
    shortDescription: "Orchestrate data movement and transformation schedules.",
    fullDescription: "AWS Data Pipeline is a web service that helps you reliably process and move data between different AWS compute and storage services, as well as on-premises data sources.",
    characteristics: ["Visual pipeline construction dashboards", "Fault-tolerant schedule orchestration", "Multi-service workflow integrations"],
    features: ["Data nodes endpoints configuration", "Pre-built transformation templates (EC2/EMR)", "Pipeline failure automatic retries", "VPC routing integration support"],
    useCases: ["Running daily S3 backup logs to Redshift", "Triggering daily EMR data transformation scripts", "Automated historical database archive copies"],
    pricingModels: ["Active cloud/on-premise Pipelines per Month"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon RDS", slug: "amazon-rds" }],
    keywords: ["data pipeline", "pipeline", "etl schedule", "data transfer workflow"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/datapipeline/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1010,
    comparisonTags: ["Workflow Orchestration", "ETL Tool"]
  },
  {
    serviceCode: "gluedatabrew",
    name: "AWS Glue DataBrew",
    slug: "aws-glue-databrew",
    categorySlug: "analytics",
    shortDescription: "Visual data preparation tool with pre-built transformations.",
    fullDescription: "AWS Glue DataBrew is a visual data preparation tool that makes it easy for data analysts and data scientists to clean and normalize data without writing code.",
    characteristics: ["No-code visual dataset dashboards", "Interactive data profile graphs", "Pre-built clean transformation modules"],
    features: ["250+ data clean operations (filter/pivot/format)", "Data lineage visualization tracking", "Glue Data Catalog schemas sync", "Automated data profiling pipelines"],
    useCases: ["Cleaning dirty customer list CSV databases", "Formatting raw datetime strings visually", "Profiling data distributions for machine learning"],
    pricingModels: ["Glue DataBrew active Analyst Session hour", "DataBrew Job execution run"],
    relatedServices: [{ name: "AWS Glue", slug: "aws-glue" }],
    keywords: ["databrew", "data prep", "no code etl", "clean data", "visual etl"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/databrew/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1020,
    comparisonTags: ["No-Code Tool", "ETL Tool"]
  },
  {
    serviceCode: "managedgrafana",
    name: "Amazon Managed Grafana",
    slug: "amazon-managed-grafana",
    categorySlug: "analytics",
    shortDescription: "Fully managed Grafana service for visualization.",
    fullDescription: "Amazon Managed Grafana is a fully managed service that handles the deployment, operations, and scaling of Grafana, a popular open-source dashboard tool.",
    characteristics: ["Managed Grafana deployment workspaces", "IAM SSO user authorization dashboard", "Direct connection to Prometheus/CloudWatch"],
    features: ["Interactive graph widget panels", "Multi-datasource analytics consolidator", "Secure workspace URLs", "IAM role-based visualization access"],
    useCases: ["Creating application health metric dashboard portals", "Visualizing system logs from CloudWatch", "Building centralized DevOps analytics centers"],
    pricingModels: ["Active Dashboard Editor User Monthly Fee", "Active Viewer User Fee"],
    relatedServices: [{ name: "Amazon Managed Service for Prometheus", slug: "amazon-managed-service-for-prometheus" }],
    keywords: ["grafana", "visualization", "managed metrics", "devops dashboard"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/grafana/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1030,
    comparisonTags: ["DevOps Dashboard", "Visualization"]
  },
  {
    serviceCode: "managedprometheus",
    name: "Amazon Managed Prometheus",
    slug: "amazon-managed-service-for-prometheus",
    categorySlug: "analytics",
    shortDescription: "Managed Prometheus compatible monitoring service.",
    fullDescription: "Amazon Managed Service for Prometheus (AMP) is a serverless, Prometheus-compatible monitoring service for container metrics that makes it easy to scale monitoring.",
    characteristics: ["Serverless Prometheus metric query engine", "PromQL query syntax compatibility", "Massive container scale support"],
    features: ["Auto-scaling ingestion metrics pools", "Secure workspace API endpoints", "AlertManager policy configurations", "EKS cluster native integration"],
    useCases: ["Ingesting EKS container CPU/memory telemetry", "Querying metrics using standard PromQL scripts", "Routing system alerts to SNS notification channels"],
    pricingModels: ["Metrics Ingested volume per GB", "Metrics Storage consumed GB/Month", "Query Execution Unit time"],
    relatedServices: [{ name: "Amazon EKS", slug: "amazon-eks" }],
    keywords: ["prometheus", "prometheus metrics", "promql", "container monitor"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/prometheus/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1040,
    comparisonTags: ["DevOps Monitoring", "Time-Series Database", "Serverless Database"]
  },
  {
    serviceCode: "mskconnect",
    name: "Amazon MSK Connect",
    slug: "amazon-msk-connect",
    categorySlug: "analytics",
    shortDescription: "Deploy Kafka Connect connectors easily on MSK.",
    fullDescription: "Amazon MSK Connect is a feature of MSK that allows you to easily deploy and run fully managed Kafka Connect connectors to copy data in/out of Kafka clusters.",
    characteristics: ["Fully managed Kafka connectors deployments", "Supports standard Kafka Connect plug-in packages", "Auto scaling worker compute nodes"],
    features: ["S3 direct connector integrations", "Database change capture (Debezium) setups", "VPC network connection routing", "CloudWatch connector logging integration"],
    useCases: ["Streaming Postgres DB changes to Kafka brokers", "Dumping Kafka topic records to S3 directories", "Connecting third-party SaaS stream inputs to MSK"],
    pricingModels: ["MSK Connect Worker Unit hour"],
    relatedServices: [{ name: "Amazon MSK", slug: "amazon-msk" }],
    keywords: ["msk connect", "kafka connect", "connector database", "stream sync"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/msk/latest/developerguide/msk-connect.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 1050,
    comparisonTags: ["Data Streaming", "ETL Tool"]
  },
  {
    serviceCode: "emrserverless",
    name: "Amazon EMR Serverless",
    slug: "amazon-emr-serverless",
    categorySlug: "analytics",
    shortDescription: "Run Spark and Hive applications without cluster management.",
    fullDescription: "Amazon EMR Serverless is a serverless deployment option in Amazon EMR that makes it easy for developers to run big data analytics applications without configuring EC2 clusters.",
    characteristics: ["Zero cluster infrastructure management", "Automatic scaling task executors", "Pay-as-you-go execution cpu/memory rates"],
    features: ["Apache Spark framework runtimes", "Apache Hive engine support", "IAM execution roles validation", "VPC private subnet attachments"],
    useCases: ["Ad-hoc Spark big data analytics processing", "Asynchronous ETL data transformations", "Data science predictive models running"],
    pricingModels: ["Provisioned CPU/Memory hours per job execution duration"],
    relatedServices: [{ name: "Amazon EMR", slug: "amazon-emr" }],
    keywords: ["emr serverless", "serverless spark", "spark run", "hive analytics"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/emr/latest/EMR-Serverless-User-Guide/emr-serverless.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 1060,
    comparisonTags: ["Big Data Platform", "Serverless Analytics"]
  },
  {
    serviceCode: "redshiftserverless",
    name: "Amazon Redshift Serverless",
    slug: "amazon-redshift-serverless",
    categorySlug: "analytics",
    shortDescription: "Run analytics without configuring data warehouse instances.",
    fullDescription: "Amazon Redshift Serverless makes it easy to run and scale analytics without having to set up and manage physical database warehouse clusters.",
    characteristics: ["Fully serverless data warehouse querying", "Auto scaling compute capacity", "No idle instance fees"],
    features: ["SQL query editor compatibility", "Redshift Spectrum query-on-S3 support", "VPC private database endpoints", "Point-in-time database restorations"],
    useCases: ["Ad-hoc enterprise data warehouse queries", "Intermittent BI dashboard queries handling", "Low cost development and testing warehouses"],
    pricingModels: ["Redshift Processing Unit (RPU) Hour", "Storage consumed per GB/Month"],
    relatedServices: [{ name: "Amazon Redshift", slug: "amazon-redshift" }],
    keywords: ["redshift serverless", "serverless warehouse", "sql warehouse serverless", "bi sql"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-what-is.html",
    isFeatured: false,
    status: "GA",
    displayOrder: 1070,
    comparisonTags: ["Data Warehouse", "Serverless Analytics", "SQL Query Engine"]
  },

  // MACHINE LEARNING
  {
    serviceCode: "sagemaker",
    name: "Amazon SageMaker",
    slug: "amazon-sagemaker",
    categorySlug: "machine-learning",
    shortDescription: "Build, train, and deploy machine learning models at scale.",
    fullDescription: "Amazon SageMaker is a fully managed service that provides every developer and data scientist with the ability to build, train, and deploy machine learning (ML) models quickly.",
    characteristics: ["Unified ML lifecycle workspace", "Managed distributed training clusters", "High-performance model hosting endpoints"],
    features: ["SageMaker Studio IDE interface", "SageMaker Autopilot AutoML search", "Model registry dashboards", "Edge manager device deployments"],
    useCases: ["Training custom image classification neural nets", "Hosting high throughput real-time prediction APIs", "Automating data labelling workflows"],
    pricingModels: ["SageMaker Notebook Instance hour", "ML Training node hour", "Model Endpoint hosting hour"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }, { name: "Amazon ECR", slug: "amazon-ecr" }],
    keywords: ["ml", "ai", "sagemaker", "model training", "predictive analytics", "jupyter ml"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/sagemaker/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1080,
    comparisonTags: ["ML Platform", "AI Development"]
  },
  {
    serviceCode: "bedrock",
    name: "Amazon Bedrock",
    slug: "amazon-bedrock",
    categorySlug: "machine-learning",
    shortDescription: "Build generative AI apps with foundation models.",
    fullDescription: "Amazon Bedrock is a fully managed service that offers choice of high-performing foundation models (FMs) from leading AI startups and Amazon via a single API.",
    characteristics: ["Serverless Foundation Model access", "Serverless fine-tuning parameters", "Enterprise grade security data protection"],
    features: ["Claude/Llama/Titan models selection APIs", "Retrieval-Augmented Generation (RAG) agents configuration", "Custom model fine-tuning support", "Data encryption standard integrations"],
    useCases: ["Building smart AI conversational chatbots", "Automated text summarizing applications", "Generating images from text queries"],
    pricingModels: ["Pay-as-you-go per token", "Provisioned throughput contract capacity"],
    relatedServices: [{ name: "Amazon SageMaker", slug: "amazon-sagemaker" }],
    keywords: ["generative ai", "bedrock", "claude", "llama", "foundation models", "ai chatbot"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/bedrock/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1090,
    comparisonTags: ["Generative AI Platform", "API AI Service"]
  },
  {
    serviceCode: "lex",
    name: "Amazon Lex",
    slug: "amazon-lex",
    categorySlug: "machine-learning",
    shortDescription: "Build conversational bots for voice and text apps.",
    fullDescription: "Amazon Lex is a fully managed service for building conversational interfaces into any application using voice and text, powering the backend of Amazon Alexa.",
    characteristics: ["Natural Language Understanding (NLU) parsing", "Automatic Speech Recognition (ASR) mapping", "Zero infrastructure chatbot runtime scaling"],
    features: ["Intent and Slot builders console", "Multi-turn dialog layouts", "Direct Amazon Connect contact center integrations", "Lambda webhook fulfillment hooks"],
    useCases: ["Customer service text chatbots", "Voice-driven phone support call queues", "Smart system voice command controllers"],
    pricingModels: ["Text Requests volume (per 1,000 requests)", "Speech Requests volume"],
    relatedServices: [{ name: "Amazon Connect", slug: "amazon-connect" }, { name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["chatbot", "lex", "voice bot", "alexa engine", "nlu text"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/lex/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1100,
    comparisonTags: ["NLP API", "Conversational AI"]
  },
  {
    serviceCode: "polly",
    name: "Amazon Polly",
    slug: "amazon-polly",
    categorySlug: "machine-learning",
    shortDescription: "Turn text into lifelike speech using deep learning.",
    fullDescription: "Amazon Polly is a service that turns text into lifelike speech, allowing you to create applications that talk, and build entirely new categories of speech-enabled products.",
    characteristics: ["Neural Text-to-Speech (NTTS) voice engine", "Multi-language dialect support", "Microsecond streaming audio responses"],
    features: ["SSML (Speech Synthesis Markup Language) tags parser", "Pronunciation lexicon uploads support", "Audio output format selections (MP3/OGG)", "Dynamic speaking rate controllers"],
    useCases: ["Generating voice audiobooks from news articles", "Live customer support automated IVR voice lines", "Adding accessibility voiceovers to apps"],
    pricingModels: ["Characters synthesized volume"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["text to speech", "tts", "polly", "audio generator", "lifelike voice"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/polly/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1110,
    comparisonTags: ["Speech Synthesis API", "API AI Service"]
  },
  {
    serviceCode: "rekognition",
    name: "Amazon Rekognition",
    slug: "amazon-rekognition",
    categorySlug: "machine-learning",
    shortDescription: "Automate image and video analysis with computer vision.",
    fullDescription: "Amazon Rekognition makes it easy to add image and video analysis to your applications using proven, highly scalable, deep learning technology that requires no machine learning expertise.",
    characteristics: ["Highly available computer vision APIs", "Real-time stream evaluation capabilities", "No computer vision model training needed"],
    features: ["Facial detection and attributes check", "Object and scene detection classification", "Text in image recognition (OCR)", "Content moderation graphic blockers"],
    useCases: ["Automated user profile photo identity checks", "Checking user-uploaded photos for explicit contents", "Scanning local video feeds for specific security objects"],
    pricingModels: ["Images analyzed volume", "Video duration processed minutes", "Custom Labels model hosting hours"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["image analysis", "computer vision", "rekognition", "facial recognition", "nsfw blocker"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/rekognition/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1120,
    comparisonTags: ["Computer Vision API", "API AI Service"]
  },
  {
    serviceCode: "transcribe",
    name: "Amazon Transcribe",
    slug: "amazon-transcribe",
    categorySlug: "machine-learning",
    shortDescription: "Convert speech to text with automatic voice recognition.",
    fullDescription: "Amazon Transcribe uses advanced deep learning models to convert speech to text quickly and accurately, supporting transcription of audio files and real-time streams.",
    characteristics: ["Speech-to-text audio recognition", "Real-time streaming audio transcriptions", "Multi-speaker identification parsing"],
    features: ["Custom vocabulary configurations", "Automated punctuation and formatting layers", "PII redaction transcript rules", "Call analytics sentiment reports"],
    useCases: ["Generating subtitles for video uploads", "Transcribing customer support call audio logs", "Live dictation speech-to-text applications"],
    pricingModels: ["Audio duration transcribed seconds"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["speech to text", "audio scribe", "transcribe", "subtitles", "stt"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/transcribe/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1130,
    comparisonTags: ["Speech Recognition API", "API AI Service"]
  },
  {
    serviceCode: "translate",
    name: "Amazon Translate",
    slug: "amazon-translate",
    categorySlug: "machine-learning",
    shortDescription: "Fast, high-quality, and customizable neural machine translation.",
    fullDescription: "Amazon Translate is a neural machine translation service that delivers fast, high-quality, affordable, and customizable language translation across dozens of languages.",
    characteristics: ["Neural network translation accuracy", "Real-time API translation responses", "Terminology customization imports"],
    features: ["Active Custom Terminology mappings support", "Automatic source language identifier checks", "Batch database translation routes", "JSON API request payloads support"],
    useCases: ["Translating support ticket logs instantly", "Providing multi-language app interfaces dynamically", "Translating database user reviews files"],
    pricingModels: ["Text characters translated volume"],
    relatedServices: [{ name: "AWS Lambda", slug: "aws-lambda" }],
    keywords: ["translate", "language translation", "translation API", "localize text"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/translate/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1140,
    comparisonTags: ["Translation API", "API AI Service"]
  },
  {
    serviceCode: "comprehend",
    name: "Amazon Comprehend",
    slug: "amazon-comprehend",
    categorySlug: "machine-learning",
    shortDescription: "Find insights and relationships in text with NLP.",
    fullDescription: "Amazon Comprehend is a natural-language processing (NLP) service that uses machine learning to find insights and relationships in unstructured text documents.",
    characteristics: ["Pre-trained language classifiers", "Unstructured text analytics parsing", "No NLP model training required"],
    features: ["Sentiment analysis checks (Positive/Negative)", "Keyphrase and entity extraction check", "Syntax analysis parsing", "Comprehend Medical HIPAA-compliant classification"],
    useCases: ["Analyzing customer support ticket sentiment", "Extracting patient drug names from medical text", "Categorizing customer review text files automatically"],
    pricingModels: ["Text characters evaluated volume (in blocks of 10,000)"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["nlp", "text analytics", "sentiment check", "comprehend", "entity extract"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/comprehend/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1150,
    comparisonTags: ["NLP API", "API AI Service"]
  },
  {
    serviceCode: "kendra",
    name: "Amazon Kendra",
    slug: "amazon-kendra",
    categorySlug: "machine-learning",
    shortDescription: "Intelligent search service powered by machine learning.",
    fullDescription: "Amazon Kendra is an intelligent enterprise search service powered by machine learning, providing natural language query search over unstructured data portals.",
    characteristics: ["Semantic search understanding query intents", "Multi-datasource indexing connectors", "Ready-to-use search dashboards"],
    features: ["Connector linkages (S3, SharePoint, Salesforce)", "Natural language questions answers extracts", "Relevance tuning parameters weights", "User access control search filters"],
    useCases: ["Building company internal intranet wiki searches", "Configuring customer support documentation portal searches", "Aggregating product manuals into searchable indices"],
    pricingModels: ["Kendra Index Hour (Developer/Enterprise Tiers)", "Extra Storage/Query capacity blocks"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["kendra", "search engine", "enterprise search", "semantic search", "wiki search"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/kendra/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1160,
    comparisonTags: ["Search Engine", "Cognitive Search"]
  },
  {
    serviceCode: "personalize",
    name: "Amazon Personalize",
    slug: "amazon-personalize",
    categorySlug: "machine-learning",
    shortDescription: "Create real-time personalized recommendations.",
    fullDescription: "Amazon Personalize enables developers to build applications with the same machine learning technology used by Amazon.com for real-time personalized recommendations.",
    characteristics: ["Dynamic recommendation models", "Custom user data ingestion hooks", "Serverless prediction endpoints scaling"],
    features: ["User-item interaction dataset uploads", "Pre-built ML recipe templates (User-Personalization/SIMS)", "Real-time event trackers ingestions", "Promotional metadata filters"],
    useCases: ["Generating recommended products on checkout pages", "Personalizing news feed articles matching interests", "Recommending similar video files to watch"],
    pricingModels: ["Data Ingested per GB", "Model Training hours", "Recommendation requests volume (per 1,000)"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["recommendations", "personalization", "suggest products", "personalize"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/personalize/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1170,
    comparisonTags: ["Recommendation System", "API AI Service"]
  },
  {
    serviceCode: "forecast",
    name: "Amazon Forecast",
    slug: "amazon-forecast",
    categorySlug: "machine-learning",
    shortDescription: "Time-series forecasting service based on ML.",
    fullDescription: "Amazon Forecast is a fully managed service that uses machine learning to deliver highly accurate time-series forecasts, predicting future trends based on historical logs.",
    characteristics: ["Automated forecasting models search", "Deep time-series analytics algorithms", "Serverless query endpoints scaling"],
    features: ["Historical dataset upload hooks", "AutoML algorithm selector checks", "Predictor evaluation metrics reports", "Forecast data exporting routines"],
    useCases: ["Predicting product warehouse inventory demands", "Forecasting server network capacity usage trends", "Predicting financial transaction pipeline volumes"],
    pricingModels: ["Forecast Data Points generated", "Model Training hours"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["forecast", "predict trends", "demand forecasting", "time series ml"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/forecast/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1180,
    comparisonTags: ["Predictive Analytics", "API AI Service"]
  },
  {
    serviceCode: "textract",
    name: "Amazon Textract",
    slug: "amazon-textract",
    categorySlug: "machine-learning",
    shortDescription: "Extract text, handwriting, and data from documents.",
    fullDescription: "Amazon Textract is a machine learning service that automatically extracts text, handwriting, and data from scanned documents, identifying tabular structures and form blocks.",
    characteristics: ["Advanced OCR layout processors", "Form and table structure recognitions", "No custom model training required"],
    features: ["Table cells grid structure extracts", "Key-Value form field detections", "Queries document analysis interface", "Liveness document checking integrations"],
    useCases: ["Parsing credit card/bank statements tables", "Extracting key values from tax form sheets", "Reading handwritten user applications images"],
    pricingModels: ["Pages analyzed volume", "Table extraction feature additions", "Queries feature additions"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["ocr", "textract", "pdf parse", "handwriting read", "extract tables"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/textract/",
    isFeatured: true,
    status: "GA",
    displayOrder: 1190,
    comparisonTags: ["Document Processing API", "API AI Service"]
  },
  {
    serviceCode: "monitron",
    name: "Amazon Monitron",
    slug: "amazon-monitron",
    categorySlug: "machine-learning",
    shortDescription: "End-to-end system for equipment anomaly detection.",
    fullDescription: "Amazon Monitron is an end-to-end system that uses machine learning to detect anomalous behavior in industrial machinery, providing sensors and gateway hardware.",
    characteristics: ["Complete hardware-software package", "Vibration and temperature telemetry analysis", "Easy industrial machine tracking dashboards"],
    features: ["Monitron hardware sensor units", "Monitron gateway devices mappings", "Mobile dashboard alarm alerts app", "Machine failure predictive ML algorithms"],
    useCases: ["Predicting cooling fan engine failures", "Monitoring conveyor belt bearing vibrations", "Tracking factory machinery temperatures anomalies"],
    pricingModels: ["Monitron Device Purchase Fee", "Monitron Service usage subscription per Sensor"],
    relatedServices: [{ name: "AWS Systems Manager", slug: "aws-systems-manager" }],
    keywords: ["monitron", "industrial iot", "predictive maintenance", "vibration sensor"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/monitron/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1200,
    comparisonTags: ["IoT Solution", "Predictive Maintenance"]
  },
  {
    serviceCode: "deepracer",
    name: "AWS DeepRacer",
    slug: "aws-deepracer",
    categorySlug: "machine-learning",
    shortDescription: "1/18th scale autonomous model car driven by RL.",
    fullDescription: "AWS DeepRacer is a 1/18th scale autonomous model car designed to help developers learn reinforcement learning (RL) through hands-on model training.",
    characteristics: ["Reinforcement learning educational platform", "3D virtual simulator dashboards", "Physical scale model vehicle option"],
    features: ["Reward function Python editor console", "DeepRacer League leaderboard integrations", "Virtual training tracks environments", "Model export to physical car memory"],
    useCases: ["Developer training reinforcement learning modules", "Hosting corporate developer racing leagues", "Academic artificial intelligence workshops"],
    pricingModels: ["DeepRacer Virtual Training hours", "Physical DeepRacer Car purchase price"],
    relatedServices: [{ name: "Amazon SageMaker", slug: "amazon-sagemaker" }],
    keywords: ["deepracer", "reinforcement learning", "autonomous car", "rl model"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/deepracer/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1210,
    comparisonTags: ["Reinforcement Learning Platform"]
  },
  {
    serviceCode: "deeplens",
    name: "AWS DeepLens",
    slug: "aws-deeplens",
    categorySlug: "machine-learning",
    shortDescription: "Deep learning enabled video camera for developers.",
    fullDescription: "AWS DeepLens is a deep learning-enabled video camera for developers to learn computer vision, offering built-in model hosting and video streams.",
    characteristics: ["Developer hardware video camera", "Local computer vision model processing", "Deep AWS ML integration"],
    features: ["Built-in model execution engines", "VPC camera stream routing", "SageMaker model export support", "Sample code templates"],
    useCases: ["Developer computer vision prototyping", "Object tracking physical tests", "Academic camera tracking labs"],
    pricingModels: ["DeepLens hardware camera unit price", "No extra software charge (pay for ECR/SageMaker assets)"],
    relatedServices: [{ name: "Amazon SageMaker", slug: "amazon-sagemaker" }],
    keywords: ["camera", "deeplens", "computer vision hardware", "video ml"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/deeplens/",
    isFeatured: false,
    status: "Deprecated",
    displayOrder: 1220,
    comparisonTags: ["Computer Vision Hardware", "Developer Kit"]
  },
  {
    serviceCode: "panorama",
    name: "AWS Panorama",
    slug: "aws-panorama",
    categorySlug: "machine-learning",
    shortDescription: "Add computer vision to existing on-premises cameras.",
    fullDescription: "AWS Panorama is a machine learning appliance and software development kit (SDK) that allows organizations to bring computer vision to on-premises IP cameras.",
    characteristics: ["On-premises hardware appliance deployment", "Local IP camera feeds processing", "Central AWS Console software management"],
    features: ["Panorama Appliance hardware unit", "Panorama SDK software container deployment", "VPC local network routing links", "Computer vision model processing filters"],
    useCases: ["Industrial factory safety compliance camera scans", "Retail shop layout customer foot-traffic analyses", "Security gate license plate scanning automation"],
    pricingModels: ["Panorama Hardware Appliance purchase cost", "Active Panorama Software Device fee"],
    relatedServices: [{ name: "Amazon SageMaker", slug: "amazon-sagemaker" }],
    keywords: ["panorama", "ip camera cv", "hardware cv", "appliance computer vision"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/panorama/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1230,
    comparisonTags: ["Computer Vision Hardware", "On-Premises Infrastructure"]
  },
  {
    serviceCode: "qdeveloper",
    name: "Amazon Q Developer",
    slug: "amazon-q-developer",
    categorySlug: "machine-learning",
    shortDescription: "Generative AI-powered conversational development assistant.",
    fullDescription: "Amazon Q Developer (incorporating CodeWhisperer capabilities) is a generative AI assistant that writes, tests, and refactors application source code inside development IDEs.",
    characteristics: ["Interactive IDE code editor sidecar", "Supports major programming languages", "Adheres to security scanning parameters"],
    features: ["Inline code auto-completions", "Full application function generations", "Vulnerability code scans reports", "Refactoring chat conversations dashboards"],
    useCases: ["Accelerating coding boilerplate speed", "Refactoring database connection class scripts", "Scanning application code for security flaws"],
    pricingModels: ["Free Tier (Developer IDE Plugin)", "Amazon Q Professional user subscription"],
    relatedServices: [{ name: "AWS Cloud9", slug: "aws-cloud9" }],
    keywords: ["q developer", "codewhisperer", "ai coding", "copilot write code", "code builder"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/amazonq/latest/developer-guide/what-is-q.html",
    isFeatured: true,
    status: "GA",
    displayOrder: 1240,
    comparisonTags: ["Generative AI Platform", "Code Assistant"]
  },
  {
    serviceCode: "healthlake",
    name: "AWS HealthLake",
    slug: "aws-healthlake",
    categorySlug: "machine-learning",
    shortDescription: "Secure, FHIR-compliant storage and analytics for health data.",
    fullDescription: "AWS HealthLake is a HIPAA-eligible service that enables healthcare providers, health insurance companies, and pharmaceutical companies to store, transform, and analyze health data.",
    characteristics: ["FHIR data standard compliance", "PII/PHI secure data vault controls", "Medical natural language text extraction"],
    features: ["FHIR database table formats support", "Integrated document text analytics check", "KMS-backed database encryption keys", "VPC private network endpoint connections"],
    useCases: ["Consolidating medical patient history FHIR databases", "Extracting clinical diagnoses from scanned doctor letters", "Analyzing historical patient files trends"],
    pricingModels: ["FHIR Data Storage per GB Monthly", "HealthLake Query scanned data"],
    relatedServices: [{ name: "Amazon Comprehend", slug: "amazon-comprehend" }],
    keywords: ["healthlake", "fhir", "medical data", "hipaa cloud", "medical analytics"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/healthlake/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1250,
    comparisonTags: ["Data Lake", "Medical Database", "HIPAA Storage"]
  },
  {
    serviceCode: "healthscribe",
    name: "AWS HealthScribe",
    slug: "aws-healthscribe",
    categorySlug: "machine-learning",
    shortDescription: "Generate clinical notes from patient-clinician conversations.",
    fullDescription: "AWS HealthScribe is a generative AI-powered service that automatically generates clinical notes by analyzing patient-clinician consultations audio recordings.",
    characteristics: ["Generative AI note compilation", "HIPAA compliance data protection", "Medical speech-to-text accuracy"],
    features: ["Automated doctor consultation transcript summaries", "Medical term parsing and highlighting", "Reference transcript trace links", "Speaker role split markers (Doctor/Patient)"],
    useCases: ["Generating patient checkup EHR notes from audio", "Transcribing and summarizing doctor patient chat records", "Automating medical database input filings"],
    pricingModels: ["Doctor-patient consultation audio duration minutes"],
    relatedServices: [{ name: "Amazon Transcribe", slug: "amazon-transcribe" }, { name: "Amazon Bedrock", slug: "amazon-bedrock" }],
    keywords: ["healthscribe", "doctor notes", "clinical transcript", "medical scribe", "medical voice"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/healthscribe/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1260,
    comparisonTags: ["Generative AI Platform", "Speech Recognition API"]
  },
  {
    serviceCode: "devopsguru",
    name: "Amazon DevOps Guru",
    slug: "amazon-devops-guru",
    categorySlug: "machine-learning",
    shortDescription: "ML-powered cloud application operations anomaly monitor.",
    fullDescription: "Amazon DevOps Guru is a fully managed operations service that makes it easy for developers and operators to improve application availability by detecting operational issues.",
    characteristics: ["Fully managed operations anomaly tracker", "Machine Learning log pattern analyzers", "Proactive system issue recommendations"],
    features: ["CloudWatch metrics logs anomaly checks", "CloudFormation stacks structural tracking", "DevOps alert dashboard panels", "Systems Manager Incident integration"],
    useCases: ["Detecting unusual RDS database CPU spikes", "Identifying application memory leaks dynamically", "Reporting network latency routing anomalies"],
    pricingModels: ["Active resource evaluated per Month"],
    relatedServices: [{ name: "Amazon CloudWatch", slug: "amazon-cloudwatch" }, { name: "AWS Systems Manager", slug: "aws-systems-manager" }],
    keywords: ["devops guru", "ops monitor", "anomalous metrics", "ops engine", "mlops"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/devops-guru/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1270,
    comparisonTags: ["DevOps Monitoring", "Operational AI"]
  },
  {
    serviceCode: "lookoutvision",
    name: "Amazon Lookout for Vision",
    slug: "amazon-lookout-for-vision",
    categorySlug: "machine-learning",
    shortDescription: "Detect visual defects in industrial products using CV.",
    fullDescription: "Amazon Lookout for Vision is a machine learning service that helps identify visual defects in industrial products, analyzing camera images of factory assembly lines.",
    characteristics: ["Industrial quality visual checks", "Low sample training requirements", "Fast image analysis API speeds"],
    features: ["Defect anomaly detection templates", "Custom defect model training datasets", "Visual dashboard defect registers", "Local Panorama appliance integration support"],
    useCases: ["Finding cracks in silicon wafer chips photos", "Detecting missing components on circuit board lines", "Identifying surface paint scratches on manufactured parts"],
    pricingModels: ["Lookout for Vision Model Training hour", "Model Inference execution hour"],
    relatedServices: [{ name: "AWS Panorama", slug: "aws-panorama" }],
    keywords: ["lookout vision", "visual defect", "factory camera scan", "defect detector"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/lookout-for-vision/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1280,
    comparisonTags: ["Computer Vision API", "API AI Service"]
  },
  {
    serviceCode: "lookoutmetrics",
    name: "Amazon Lookout for Metrics",
    slug: "amazon-lookout-for-metrics",
    categorySlug: "machine-learning",
    shortDescription: "Detect anomalies in metrics and identify root causes.",
    fullDescription: "Amazon Lookout for Metrics uses machine learning to automatically detect and diagnose anomalies in your business and operational metrics without ML experience.",
    characteristics: ["Multi-metric correlation engines", "Automated anomaly trigger thresholds", "Root cause trace analyzer"],
    features: ["Metric source connector links (S3, RDS, Salesforce)", "Anomaly dashboard visualization charts", "SNS notification channel alerts hook", "Feedback tuning inputs interface"],
    useCases: ["Detecting sudden drop in checkout cart transactions", "Monitoring unusual server traffic volume spikes", "Identifying drop-offs in corporate advertising click metrics"],
    pricingModels: ["Metrics evaluated volume per Month"],
    relatedServices: [{ name: "Amazon CloudWatch", slug: "amazon-cloudwatch" }],
    keywords: ["lookout metrics", "business anomaly", "anomalous data check", "metric scan"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/lookout-for-metrics/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1290,
    comparisonTags: ["Predictive Analytics", "Operational AI"]
  },
  {
    serviceCode: "lookoutequipment",
    name: "Amazon Lookout for Equipment",
    slug: "amazon-lookout-for-equipment",
    categorySlug: "machine-learning",
    shortDescription: "Predictive maintenance service for industrial sensors.",
    fullDescription: "Amazon Lookout for Equipment analyzes historical data from your industrial sensors (like vibration, temperature, pressure) to build predictive models for equipment.",
    characteristics: ["Multi-sensor time-series model engines", "Managed industrial machine tracking", "Predictive maintenance reports generator"],
    features: ["Sensor data CSV ingestion links", "Custom sensor model validation pipelines", "Anomalous event prediction registers", "Console machine health graphs"],
    useCases: ["Predicting paper mill rollers mechanical failures", "Monitoring wind turbine telemetry sensor systems", "Tracking oil pump motor telemetry health"],
    pricingModels: ["Sensor Data Ingested volume per GB", "Model Training hours", "Model Inference active hours"],
    relatedServices: [{ name: "Amazon S3", slug: "amazon-s3" }],
    keywords: ["lookout equipment", "predictive maintenance", "vibration sensor model", "industrial sensor"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/lookout-for-equipment/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1300,
    comparisonTags: ["IoT Solution", "Predictive Maintenance"]
  },
  {
    serviceCode: "codeguru",
    name: "Amazon CodeGuru",
    slug: "amazon-codeguru",
    categorySlug: "machine-learning",
    shortDescription: "Automated code reviews and performance profiling.",
    fullDescription: "Amazon CodeGuru is a developer tool that provides intelligent recommendations for improving code quality and identifying an application's most expensive lines of code.",
    characteristics: ["ML-driven static code analyzer", "Automated execution profile tracker", "Developer workflow integration plugins"],
    features: ["CodeGuru Reviewer repository scanners", "CodeGuru Profiler host agent loops", "CPU performance cost hot-spot graphs", "AWS security best-practices check"],
    useCases: ["Finding thread concurrency bugs in code", "Identifying CPU-expensive database queries code", "Automated code review validations in pull requests"],
    pricingModels: ["Reviewer repository lines scanned", "Profiler active Agent hours"],
    relatedServices: [{ name: "AWS CodeCommit", slug: "aws-code-commit" }],
    keywords: ["codeguru", "code review", "code profiler", "performance tune"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/codeguru/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1310,
    comparisonTags: ["Code Assistant", "DevOps Infrastructure"]
  },
  {
    serviceCode: "frauddetector",
    name: "Amazon Fraud Detector",
    slug: "amazon-fraud-detector",
    categorySlug: "machine-learning",
    shortDescription: "Fully managed service to detect online fraud.",
    fullDescription: "Amazon Fraud Detector is a fully managed service that makes it easy to identify potentially fraudulent online activities, such as online payment fraud and fake account creation.",
    characteristics: ["Tailored fraud prediction models", "Real-time decision checking APIs", "Dynamic rule execution filters"],
    features: ["Historical fraud dataset upload hooks", "AutoML fraud model builder engines", "Fraud rule threshold builders Console", "Real-time API response scores"],
    useCases: ["Checking web signup email registrations for bots", "Evaluating credit card checkout charge risk", "Detecting trial abuse signups attempts"],
    pricingModels: ["Fraud Prediction checks volume", "Model Training hours", "Model hosting hours"],
    relatedServices: [{ name: "Amazon SES", slug: "amazon-ses" }],
    keywords: ["fraud detector", "fraud checker", "payment check", "signup check", "risk scanner"],
    awsDocumentationUrl: "https://docs.aws.amazon.com/frauddetector/",
    isFeatured: false,
    status: "GA",
    displayOrder: 1320,
    comparisonTags: ["Fraud Prevention", "API AI Service"]
  }
];
